COMMERCE-1056
liferay/com-liferay-commerce pull request #1157
Opened 2019-07-12 14:00 UTC by Commando18

2019-07-12 14:00 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2019-07-12 14:00 UTC, Commando18 commented
ci:test

2019-07-12 14:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/121/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-20.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/121/jenkins-report.html">here</a>.</b></p>

2019-07-12 14:30 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 25 minutes 10 seconds 184 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/a2af1d21c2e3a5a24a38fca81ebc5ca52416b158">a2af1d21c2e3a5a24a38fca81ebc5ca52416b158</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-1.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/67//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-1.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/67//testReport">here</a>.</h5></div></html>

2019-07-12 15:08 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test - 2 out of 6 jobs passed in 1 hour 7 minutes 20 seconds 433 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/a2af1d21c2e3a5a24a38fca81ebc5ca52416b158">a2af1d21c2e3a5a24a38fca81ebc5ca52416b158</a></p>2 out of 6 jobs PASSED<div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/121/"><strike><strong>test-subrepository-acceptance-pullrequest(7.1.x)</strong></strike></a></li><li><a href="https://test-1-9.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/223/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-9.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/222/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</strong></strike></a></li><li><a href="https://test-1-9.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/224/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</strong></strike></a></li></ul></div><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-15.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/22/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-1.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/67/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-20.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/121/jenkins-report.html">here</a>.</h5><hr/><h4>Failures (upstream comparison is not available):</h4><ol><li><div><h5><a href="https://test-1-9.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/222/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-9.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/222//consoleText">AXIS_VARIABLE=0,label_exp=!master #222</a><pre><code>     [echo] * What went wrong:
     [echo] Execution failed for task ':apps:commerce:commerce-address-web:compileJSP'.
     [echo] &gt; Compilation failed; see the compiler error output for details.
     [echo] 
     [echo] * Try:
     [echo] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [echo] 
     [echo] * Exception is:
     [echo] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:commerce:commerce-address-web:compileJSP'.
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
     [echo] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
     [echo] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
     [echo] 	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
     [echo] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
     [echo] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)</code></pre></div></li></ol></div></li><li><div><h5><a href="https://test-1-9.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/223/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>2 Tests Passed.<br/>2 Tests Failed.</p></div><ol><li><div><a href="https://test-1-9.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/223//consoleText">AXIS_VARIABLE=0,label_exp=!master #223</a><ol><li><div><a href="https://test-1-9.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/223//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog">PortalLogAssertorTest.testScanXMLLog</a><pre><code>junit.framework.AssertionFailedError: 
Declarative Service Unsatisfied Component Checker check result: 
Bundle {id: 422, name: com.liferay.commerce.frontend.impl, version: 1.0.14}
	Declarative Service {id: 1727, name: com.liferay.commerce.frontend.internal.template.soy.renderer.SoyRendererImpl, unsatisfied references: 
		{name: _soyTemplateResourcesProvider, target: null}
	}
	Declarative Service {id: 1726, name: com.liferay.commerce.frontend.internal.template.soy.renderer.SoyComponentRendererImpl, unsatisfied references: 
		{name: _soyRenderer, target: null}
	}
Bundle {id: 496, name: com.liferay.commerce.theme.minium.impl, version: 2.0.7}
	Declarative Service {id: 2429, name: com.liferay.commerce.theme.minium.internal.product.renderer.list.MiniumCPCompareListRenderer, unsatisfied references: 
		{name: _soyComponentRenderer, target: null}
	}
	Declarative Service {id: 2431, name: com.liferay.commerce.theme.minium.internal.product.renderer.list.entry.MiniumCPContentListEntryRenderer, unsatisfied references: 
		{name: _soyComponentRenderer, target: null}
	}
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:172)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:98)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:88)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.life...</code></pre></div></li><li><div><a href="https://test-1-9.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/223//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PortalSmoke_Smoke_">LocalFile.PortalSmoke#Smoke</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-20/1562940086813/test-subrepository-acceptance-pullrequest(7.1.x)/121/functional-smoke-tomcat90-mysql57-jdk8/0/0/LocalFile.PortalSmoke_Smoke/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-20/1562940086813/test-subrepository-acceptance-pullrequest(7.1.x)/121/functional-smoke-tomcat90-mysql57 [...]

2019-12-10 00:36 UTC, ethanbustad requested changes
Just the language thing, and the rebase. I tried to rebase it locally, but there've been significant changes to this package since the PR was made, so the conflicts are pretty nasty. Takes a bit of reworking. Just a heads-up.

2019-12-10 00:36 UTC, ethanbustad commented on commerce-lang/src/main/resources/content/Language.properties
> +italy=Italy
we should use the OOTB portal keys for this -- `country.italy`, `country.united-states`, etc.

2019-12-11 00:03 UTC, ethanbustad commented
Rebased and sent along to https://github.com/liferay/com-liferay-commerce/pull/1787. Note that I also adjusted the starters a bit to match changes that've been made in that package since this PR was sent, and switched to using portal language keys.

2019-12-11 00:03 UTC, closed without merging