Account Management fixes/changes (Add activate / deactive)
liferay/com-liferay-commerce pull request #1237
Opened 2019-08-02 01:02 UTC by alecsloan

2019-08-02 01:02 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2019-08-02 16:11 UTC, alecsloan commented
ci:test

2019-08-02 16:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/71/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/71/jenkins-report.html">here</a>.</b></p>

2019-08-02 16:44 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 29 minutes 2 seconds 460 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/3b536af6f8a6dfdc4398924855fb60920b532691">3b536af6f8a6dfdc4398924855fb60920b532691</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [echo] java.lang.Exception: Found 4 formatting issues:
     [echo] 1: Missing parentheses around the left hand side argument of the '||' operator: ./commerce-account-service/src/main/java/com/liferay/commerce/account/internal/util/CommerceAccountHelperImpl.java 119 (Checkstyle:MissingParenthesesCheck)
     [echo] 2: ./commerce-account-service/src/main/java/com/liferay/commerce/account/internal/util/CommerceAccountHelperImpl.java expected:&lt;...ountId);
     [echo] 		}
     [echo] 
     [echo] 		if ([(currentCommerceAccountId &lt;= 0)] || !commerceAccount...&gt; but was:&lt;...ountId);
     [echo] 		}
     [echo] 
     [echo] 		if ([currentCommerceAccountId &lt;= 0] || !commerceAccount...&gt;
     [echo] 3: ./commerce-account-service/src/main/java/com/liferay/commerce/account/service/impl/CommerceAccountServiceImpl.java expected:&lt;...}
     [echo] 
     [echo] 		return 0;
     [echo] 	}
     [echo] 
     [echo] 	[@Override
     [echo] 	public CommerceAccount setActive(long commerceAccountId, boolean active)
     [echo] 		throws PortalException {
     [echo] 
     [echo] 		_commerceAccountModelResourcePermission.check(
     [echo] 			getPermissionChecker(), commerceAccountId, ActionKeys.UPDATE);
     [echo] 
     [echo] 		return commerceAccountLocalService.setActive(commerceAccountId, active);
     [echo] 	}
     [echo] 
     [echo] 	public CommerceAccount updateCommerceAccount(
     [echo] 			long commerceAccountId, String name, boolean logo, byte[] logoBytes,
     [echo] 			String email, String taxId, boolean active,
     [echo] 			ServiceContext serviceContext)
     [echo] 		throws PortalException {
     [echo] 
     [echo] 		_commerceAccountModelResourcePermission.check(
     [echo] 			getPermissionChecker(), commerceAccountId, ActionKeys.UPDATE);
     [echo] 
     [echo] 		return commerceAccountLocalService.updateCommerceAccount(
     [echo] 			commerceAccountId, name, logo, logoBytes, email, taxId, active,
     [echo] 			serviceContext);
     [echo] 	}
     [echo] 
     [echo] 	@Override
     [echo] 	public CommerceAccount upsertCommerceAccount(
     [echo] 			String name, long parentCommerceAccountId, boolean logo,
     [echo] 			byte[] logoBytes, String email, String taxId, int type,
     [echo] 			boolean active, String externalReferenceCode,
     [echo] 			ServiceContext serviceContext)
     [echo] 		throws PortalException {
     [echo] 
     [echo] 		PermissionChecker permissionChecker = getPermissionChecker();
     [echo] </code></pre></li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/139//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/139//testReport">here</a>.</h5></div></html>

2019-08-02 17:05 UTC, alecsloan commented
ci:test

2019-08-02 17:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/132/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-20.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/132/jenkins-report.html">here</a>.</b></p>

2019-08-02 17:33 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 24 minutes 26 seconds 917 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/3b536af6f8a6dfdc4398924855fb60920b532691">3b536af6f8a6dfdc4398924855fb60920b532691</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-19.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/105//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-19.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/105//testReport">here</a>.</h5></div></html>

2019-08-02 18:13 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test - 6 out of 6 jobs passed in 1 hour 6 minutes 54 seconds 95 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/3b536af6f8a6dfdc4398924855fb60920b532691">3b536af6f8a6dfdc4398924855fb60920b532691</a></p>6 out of 6 jobs PASSED<details><summary><strong>6 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/132/">test-subrepository-acceptance-pullrequest(7.1.x)</a></li><li><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/455/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/454/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/456/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/70/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-19.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/105/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-20.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/132/jenkins-report.html">here</a>.</h5></details></html>

2019-09-20 10:20 UTC, marco-leo commented on commerce-account-web/src/main/java/com/liferay/commerce/account/web/internal/frontend/CommerceAccountClayTable.java
> +		if (PortalPermissionUtil.contains(
check if you can update the account

2019-09-20 10:22 UTC, marco-leo commented on commerce-theme-minium/commerce-theme-minium-impl/src/main/resources/META-INF/resources/action_menus/MiniumActionsMenu.soy
> +					<svg class="commerce-icon minium-action-toggle__open"
svg source in the soy?

2019-09-20 16:35 UTC, alecsloan commented
ci:test

2019-09-20 16:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/164/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-20.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/164/jenkins-report.html">here</a>.</b></p>

2019-09-20 16:48 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 10 minutes 38 seconds 983 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/179cc61dd25354987532464bb79d5f060965cc3f">179cc61dd25354987532464bb79d5f060965cc3f</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :x:<pre><code>     [echo] * What went wrong:
     [echo] Execution failed for task ':apps:commerce:commerce-api:baseline'.
     [echo] &gt; Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal-7.1.x/tools/sdk/dist/com.liferay.commerce.api-9.3.0.jar against /opt/dev/projects/github/liferay-portal-7.1.x/.gradle/caches/modules-2/files-2.1/com.liferay.commerce/com.liferay.commerce.api/9.2.0/a3cf4a52aed7d6e0f22b783942f74ebfe3c3464f/com.liferay.commerce.api-9.2.0.jar
     [echo] 
     [echo] * Try:
     [echo] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [echo] 
     [echo] * Exception is:
     [echo] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:commerce:commerce-api:baseline'.
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
     [echo] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
     [echo] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
     [echo] 	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
     [echo] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)</code></pre></li><li>central-requirements-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/128//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>7 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/128//testReport">here</a>.</h5></div></html>

2019-09-20 17:08 UTC, alecsloan commented
ci:test

2019-09-20 17:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/162/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/162/jenkins-report.html">here</a>.</b></p>

2019-09-20 17:43 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 26 minutes 43 seconds 428 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/179cc61dd25354987532464bb79d5f060965cc3f">179cc61dd25354987532464bb79d5f060965cc3f</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [echo] java.lang.Exception: Found 2 formatting issues:
     [echo] 1: Unnecessary semi colon: ./commerce-service/src/main/java/com/liferay/commerce/service/impl/CommerceOrderServiceImpl.java 831 (Checkstyle:SemiColonCheck)
     [echo] 2: ./commerce-service/src/main/java/com/liferay/commerce/service/impl/CommerceOrderServiceImpl.java expected:&lt;...onUtil.contains(
     [echo] 			[	getPermissionChecker(),
     [echo] 				CommerceAccountActionKeys.MANAGE_ALL_ACCOUNTS)) {
     [echo] 
     [echo] 			commerceAccountIds =
     [echo] 				_commerceAccountHelper.getUserCommerceAccountIds(
     [echo] 					getUserId(), groupId)];
     [echo] 		}
     [echo] 
     [echo] 		return comm...&gt; but was:&lt;...onUtil.contains(
     [echo] 			[getPermissionChecker(),
     [echo] 			CommerceAccountActionKeys.MANAGE_ALL_ACCOUNTS)) {
     [echo] 
     [echo] 			commerceAccountIds =
     [echo] 				_commerceAccountHelper.getUserCommerceAccountIds(
     [echo] 					getUserId(), groupId);];
     [echo] 		}
     [echo] 
     [echo] 		return comm...&gt;
     [echo] 
     [echo] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:438)
     [echo] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:266)
     [echo] 
     [echo] FAILURE: Build failed with an exception.
     [echo] 
     [echo] * What went wrong:
     [echo] Execution failed for task ':checkSourceFormatting'.
     [echo] &gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [echo] 
     [echo] * Try:
     [echo] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [echo] 
     [echo] * Exception is:
     [echo] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':checkSourceFormatting'.
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
     [echo] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)</code></pre></li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/129//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/129//testReport">here</a>.</h5></div></html>

2019-09-26 20:09 UTC, ethanbustad commented
@alecsloan validation errors to fix here

2019-09-26 21:21 UTC, alecsloan commented
ci:test

2019-09-26 21:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/97/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-4.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/97/jenkins-report.html">here</a>.</b></p>

2019-09-26 21:46 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 21 minutes 31 seconds 770 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/35d786d27bd94ebe0a6fea7507e486f3f91be58d">35d786d27bd94ebe0a6fea7507e486f3f91be58d</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/104//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/104//testReport">here</a>.</h5></div></html>

2019-09-26 22:24 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test - 13 out of 13 jobs passed in 1 hour 2 minutes 34 seconds 265 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/35d786d27bd94ebe0a6fea7507e486f3f91be58d">35d786d27bd94ebe0a6fea7507e486f3f91be58d</a></p>13 out of 13 jobs PASSED<details><summary><strong>13 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/97/">test-subrepository-acceptance-pullrequest(7.1.x)</a></li><li><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/744/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/590/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/676/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/724/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/737/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/725/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/482/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/760/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/481/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/761/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></li><li><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/130/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/104/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/97/jenkins-report.html">here</a>.</h5></details></html>

2019-09-27 17:31 UTC, ethanbustad requested changes
Hey, not sure whether this feedback is for @FabioDiegoMastrorilli or @alecsloan , but there's a few things it'd be good to address here.

EDIT: Oh, never mind, this isn't the PR from Fabio 😝 .

2019-09-27 17:31 UTC, ethanbustad commented on commerce-account-admin-web/src/main/java/com/liferay/commerce/account/admin/web/internal/portlet/action/EditCommerceAccountMVCActionCommand.java
> +				ParamUtil.getString(actionRequest, "commerceAccountIds"), 0L);
This should be `ParamUtil.getLongValues` rather than `StringUtil.split(ParamUtil.getString...`

2019-09-27 17:31 UTC, ethanbustad commented on commerce-account-admin-web/src/main/resources/META-INF/resources/view.jsp
> +		function <portlet:namespace />activateCommerceAccounts() {
Function declarations should be sorted alphabetically.

2019-09-27 17:31 UTC, ethanbustad commented on commerce-theme-minium/commerce-theme-minium-site-initializer/src/main/resources/com/liferay/commerce/theme/minium/site/initializer/internal/dependencies/layouts.json
> +	}
don't we need a comma here?

2019-09-27 19:16 UTC, alecsloan commented on commerce-theme-minium/commerce-theme-minium-site-initializer/src/main/resources/com/liferay/commerce/theme/minium/site/initializer/internal/dependencies/layouts.json
> +	}
yes

2019-09-27 19:17 UTC, alecsloan commented
ci:test

2019-09-27 19:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/98/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-4.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/98/jenkins-report.html">here</a>.</b></p>

2019-09-27 19:43 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 22 minutes 4 seconds 645 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/9a000d847405fe55149d2900f4caff8118494cd8">9a000d847405fe55149d2900f4caff8118494cd8</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [echo] java.lang.Exception: Found 1 formatting issues:
     [echo] 1: ./commerce-account-admin-web/src/main/java/com/liferay/commerce/account/admin/web/internal/portlet/action/EditCommerceAccountMVCActionCommand.java expected:&lt;...commerceAccountIds =[ ParamUtil.getLongValues(
     [echo] 				]actionRequest, "comm...&gt; but was:&lt;...commerceAccountIds =[
     [echo] 				ParamUtil.getLongValues(]actionRequest, "comm...&gt;
     [echo] 
     [echo] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:438)
     [echo] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:266)
     [echo] 
     [echo] FAILURE: Build failed with an exception.
     [echo] 
     [echo] * What went wrong:
     [echo] Execution failed for task ':checkSourceFormatting'.
     [echo] &gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [echo] 
     [echo] * Try:
     [echo] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [echo] 
     [echo] * Exception is:
     [echo] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':checkSourceFormatting'.
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
     [echo] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
     [echo] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
     [echo] 	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
     [echo] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)</code></pre></li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/207//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/207//testReport">here</a>.</h5></div></html>

2019-09-27 19:53 UTC, alecsloan commented
ci:test

2019-09-27 19:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/168/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-5.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/168/jenkins-report.html">here</a>.</b></p>

2019-09-27 20:15 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 18 minutes 11 seconds 150 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/9a000d847405fe55149d2900f4caff8118494cd8">9a000d847405fe55149d2900f4caff8118494cd8</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/172//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/172//testReport">here</a>.</h5></div></html>

2019-09-27 20:55 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test - 13 out of 13 jobs passed in 1 hour 1 minute 51 seconds 834 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/9a000d847405fe55149d2900f4caff8118494cd8">9a000d847405fe55149d2900f4caff8118494cd8</a></p>13 out of 13 jobs PASSED<details><summary><strong>13 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/168/">test-subrepository-acceptance-pullrequest(7.1.x)</a></li><li><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/898/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/475/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/476/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/473/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/474/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-13.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/487/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/899/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/729/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-13.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/486/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/568/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/71/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/172/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-5.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/168/jenkins-report.html">here</a>.</h5></details></html>

2019-09-30 20:10 UTC, ethanbustad requested changes
Looks like you accidentally committed a couple of `.patch` files that shouldn't be here. Also just a couple other minor changes to make.

2019-09-30 20:10 UTC, ethanbustad commented on commerce-frontend-api/src/main/java/com/liferay/commerce/frontend/ClayTableAction.java
> +		_cssClasses = "";
Should be `StringPool.BLANK` rather than `""`.

2019-09-30 20:10 UTC, ethanbustad commented on commerce-frontend-api/src/main/java/com/liferay/commerce/frontend/ClayTableAction.java
> +		_cssClasses = "";
Also, it'd be better to have this constructor simply call the new constructor, with the default value passed in -- that way it's obvious there's only that simple difference between the constructors (these ones are pretty simple so it's not much different at the moment, but if they get any more complicated in the future the difference would be significant).

2019-10-07 16:27 UTC, alecsloan commented
ci:test

2019-10-07 16:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/172/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/172/jenkins-report.html">here</a>.</b></p>

2019-10-07 16:39 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 10 minutes 8 seconds 155 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/fa8174a94a593653a535cb1a38984d907f449938">fa8174a94a593653a535cb1a38984d907f449938</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :x:<pre><code>     [echo] * What went wrong:
     [echo] Execution failed for task ':apps:commerce:commerce-frontend-api:baseline'.
     [echo] &gt; Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal-7.1.x/tools/sdk/dist/com.liferay.commerce.frontend.api-1.2.1.jar against /opt/dev/projects/github/liferay-portal-7.1.x/.gradle/caches/modules-2/files-2.1/com.liferay.commerce/com.liferay.commerce.frontend.api/1.2.0/acbad4e4ca5d8840b98b92d37db259b3b3d8d347/com.liferay.commerce.frontend.api-1.2.0.jar
     [echo] 
     [echo] * Try:
     [echo] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [echo] 
     [echo] * Exception is:
     [echo] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:commerce:commerce-frontend-api:baseline'.
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
     [echo] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
     [echo] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
     [echo] 	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
     [echo] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)</code></pre></li><li>central-requirements-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/164//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>7 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/164//testReport">here</a>.</h5></div></html>

2019-10-07 18:59 UTC, alecsloan commented
ci:test

2019-10-07 19:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/43/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/43/jenkins-report.html">here</a>.</b></p>

2019-10-07 19:22 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 19 minutes 7 seconds 434 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/fa8174a94a593653a535cb1a38984d907f449938">fa8174a94a593653a535cb1a38984d907f449938</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/192//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/192//testReport">here</a>.</h5></div></html>

2019-10-07 19:29 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test - 1 out of 3 jobs passed in 30 minutes 5 seconds 924 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/fa8174a94a593653a535cb1a38984d907f449938">fa8174a94a593653a535cb1a38984d907f449938</a></p>1 out of 3 jobs PASSED<div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/43/"><strike><strong>test-subrepository-acceptance-pullrequest(7.1.x)</strong></strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/91/"><strike><strong>test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</strong></strike></a></li></ul></div><details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/192/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/43/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-19.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/91/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-19.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/AXIS_VARIABLE=tomcat,label_exp=!master/91//consoleText">AXIS_VARIABLE=tomcat,label_exp=!master #91</a><pre><code>[artifact:install] [INFO] Installing /opt/dev/projects/github/liferay-portal-7.1.x/util-taglib/util-taglib.jar to /opt/dev/projects/github/liferay-portal-7.1.x/.m2/com/liferay/portal/com.liferay.util.taglib/3.4.8-SNAPSHOT/com.liferay.util.taglib-3.4.8-SNAPSHOT.jar
[artifact:install] [INFO] Installing /opt/dev/projects/github/liferay-portal-7.1.x/util-taglib/util-taglib-sources.jar to /opt/dev/projects/github/liferay-portal-7.1.x/.m2/com/liferay/portal/com.liferay.util.taglib/3.4.8-SNAPSHOT/com.liferay.util.taglib-3.4.8-SNAPSHOT-sources.jar
   [delete] Deleting: /opt/dev/projects/github/liferay-portal-7.1.x/util-taglib/pom.xml
[propertyfile] Updating property file: /opt/dev/projects/github/liferay-portal-7.1.x/.gradle/gradle.properties
     [echo] RSYNCING BUNDLE
     [exec] Warning: Permanently added 'test-1-0,172.16.0.50' (RSA) to the list of known hosts.
     [exec] Warning: Permanently added 'test-1-0,172.16.0.50' (RSA) to the list of known hosts.
     [exec] rsync: change_dir "/opt/java/jenkins/userContent/bundles/test-portal-acceptance-upstream(7.1.x)/1148" failed: No such file or directory (2)
     [exec] rsync: change_dir "/opt/java/jenkins/userContent/bundles/test-portal-acceptance-upstream(7.1.x)/1148" failed: No such file or directory (2)
     [exec] rsync: change_dir "/opt/java/jenkins/userContent/bundles/test-portal-acceptance-upstream(7.1.x)/1148" failed: No such file or directory (2)
     [exec] rsync: change_dir "/opt/java/jenkins/userContent/bundles/test-portal-acceptance-upstream(7.1.x)/1148" failed: No such file or directory (2)
     [exec] rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1650) [Receiver=3.1.2]
     [exec] rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1650) [Receiver=3.1.2]
     [exec] rsync: [Receiver] write error: Broken pipe (32)
     [exec] rsync: [Receiver] write error: Broken pipe (32)
   [delete] Deleting: /opt/dev/projects/github/liferay-jenkins-ee/commands/20191007192918294
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:742: exec returned: 23

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:11074: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:742: exec returned: 23</code></pre></div></li></ol></div></li></ol></details></html>

2019-10-07 19:31 UTC, alecsloan commented
ci:test

2019-10-07 19:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/174/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-20.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/174/jenkins-report.html">here</a>.</b></p>

2019-10-07 20:00 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 26 minutes 772 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/fa8174a94a593653a535cb1a38984d907f449938">fa8174a94a593653a535cb1a38984d907f449938</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/165//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/165//testReport">here</a>.</h5></div></html>

2019-10-07 20:28 UTC, ethanbustad requested changes

2019-10-07 20:28 UTC, ethanbustad commented on commerce-account-web/src/main/java/com/liferay/commerce/account/web/internal/frontend/CommerceAccountClayTable.java
> +		PortletURL activateURL = PortletURLFactoryUtil.create(
Should use a `_portletURLFactory` reference here instead of static util.

2019-10-07 20:28 UTC, ethanbustad commented on commerce-account-service/src/main/java/com/liferay/commerce/account/internal/util/CommerceAccountHelperImpl.java
> +		if ((currentCommerceAccountId <= 0) || !commerceAccount.isActive()) {
`(currentCommerceAccountId <= 0)` should probably now be a null check, since `fetchCommerceAccount` could return null.

2019-10-07 20:47 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test - 11 out of 13 jobs passed in 1 hour 16 minutes 316 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/fa8174a94a593653a535cb1a38984d907f449938">fa8174a94a593653a535cb1a38984d907f449938</a></p>11 out of 13 jobs PASSED<div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/174/"><strike><strong>test-subrepository-acceptance-pullrequest(7.1.x)</strong></strike></a></li><li><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/800/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>11 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/579/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/767/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/578/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-13.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/494/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/580/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-13.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/496/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-13.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/495/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/784/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/768/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></li><li><a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/62/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/165/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-20.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/174/jenkins-report.html">here</a>.</h5><hr/><h4>Failures (upstream comparison is not available):</h4><ol><li><div><h5><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/800/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>2 Tests Passed.<br/>2 Tests Failed.</p></div><ol><li><div><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/800//consoleText">AXIS_VARIABLE=0,label_exp=!master #800</a><ol><li><div><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/800//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog">PortalLogAssertorTest.testScanXMLLog</a><pre><code>junit.framework.AssertionFailedError: 
com.liferay.portal.kernel.exception.PortalException: Impossible to load https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml
com.liferay.portal.kernel.exception.PortalException: Impossible to load https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml
	at com.liferay.commerce.currency.internal.util.ECBExchangeRateProvider.getExchangeRate(ECBExchangeRateProvider.java:83)
	at com.liferay.commerce.currency.service.impl.CommerceCurrencyLocalServiceImpl.updateExchangeRate(CommerceCurrencyLocalServiceImpl.java:391)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:153)
	at com.liferay.portal.spring.transaction.DefaultTransactionExecutor._execute(DefaultTransactionExecutor.java:203)
	at com.liferay.portal.spring.transaction.DefaultTransactionExecutor.execute(DefaultTransactionExecutor.java:94)
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:130)
	at com.liferay.portal.spring.aop.RetryAdvice.invoke(RetryAdvice.java:47)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:130)
	at com.liferay.portal.service.ServiceContextAdvice.invoke(ServiceContextAdvice.java:39)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:130)...</code></pre></div></li><li><div><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/800//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PortalSmoke_Smoke_">LocalFile.PortalSmoke#Smoke</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-20/1570476711301/test-subrepository-acceptance-pullrequest(7.1.x)/174/functional-smoke-tomcat90-mysql57-jdk8/0/0/LocalFile.PortalSmoke_Smoke/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-20/1570476711301/test-subrepository-acceptance-pullrequest(7.1.x)/174/functional-smoke-tomcat90-mysql57-jdk8/0/0/LocalFile.PortalSmoke_Smoke/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-20/1570476711301/test-subrepository-acceptance-pullrequest(7.1.x)/174/functional-smoke-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li></ol></details></html>

2019-10-07 21:18 UTC, alecsloan commented
ci:test

2019-10-07 21:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/102/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-4.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/102/jenkins-report.html">here</a>.</b></p>

2019-10-07 21:42 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 18 minutes 55 seconds 274 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/fa8174a94a593653a535cb1a38984d907f449938">fa8174a94a593653a535cb1a38984d907f449938</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/193//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/193//testReport">here</a>.</h5></div></html>

2019-10-07 21:49 UTC, alecsloan commented
Force push reflects minor changes that Ethan requested.

2019-10-07 22:23 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test - 13 out of 13 jobs passed in 1 hour 3 minutes 596 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/fa8174a94a593653a535cb1a38984d907f449938">fa8174a94a593653a535cb1a38984d907f449938</a></p>13 out of 13 jobs PASSED<details><summary><strong>13 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/102/">test-subrepository-acceptance-pullrequest(7.1.x)</a></li><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/505/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/504/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-13.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/497/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/502/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/503/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/506/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/786/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/785/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/503/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-13.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/498/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></li><li><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/63/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/193/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/102/jenkins-report.html">here</a>.</h5></details></html>

2019-10-07 22:24 UTC, marco-leo commented
@ethanbustad green for you?

2019-10-08 18:00 UTC, ethanbustad approved these changes

2019-10-08 19:42 UTC, merged