COMMERCE-1738 added check on array emptiness
liferay/com-liferay-commerce pull request #1379
Opened 2019-09-13 09:46 UTC by andrea-ale-sbarra

2019-09-13 09:46 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2019-09-13 09:46 UTC, andrea-ale-sbarra commented
ci:test

2019-09-13 09:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/159/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-20.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/159/jenkins-report.html">here</a>.</b></p>

2019-09-13 10:09 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 19 minutes 38 seconds 686 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/eb88b7733d3bfcecb241763a6513ba393be0336e">eb88b7733d3bfcecb241763a6513ba393be0336e</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/106//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/106//testReport">here</a>.</h5></div></html>

2019-09-13 10:43 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test - 6 out of 6 jobs passed in 57 minutes 24 seconds 215 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/eb88b7733d3bfcecb241763a6513ba393be0336e">eb88b7733d3bfcecb241763a6513ba393be0336e</a></p>6 out of 6 jobs PASSED<details><summary><strong>6 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/159/">test-subrepository-acceptance-pullrequest(7.1.x)</a></li><li><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/616/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/553/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/617/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/78/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/106/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-20.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/159/jenkins-report.html">here</a>.</h5></details></html>

2019-09-16 19:06 UTC, ethanbustad requested changes

2019-09-16 19:06 UTC, ethanbustad commented on commerce-payment-web/src/main/java/com/liferay/commerce/payment/web/internal/display/context/CommercePaymentMethodGroupRelsDisplayContext.java
> +			results.sort(
Hey @andrea-ale-sbarra, let's have a call about this tomorrow. I think this isn't the right fix.

2019-09-18 07:56 UTC, andrea-ale-sbarra commented
ci:tets

2019-09-18 07:57 UTC, andrea-ale-sbarra commented
ci:test

2019-09-18 07:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-1.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/82/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-1.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/82/jenkins-report.html">here</a>.</b></p>

2019-09-18 08:27 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 23 minutes 9 seconds 619 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/2fbfe5a1c5e11d030a823c1a61055b28e4971327">2fbfe5a1c5e11d030a823c1a61055b28e4971327</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/88//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/88//testReport">here</a>.</h5></div></html>

2019-09-18 09:09 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test - 6 out of 6 jobs passed in 1 hour 11 minutes 23 seconds 259 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/2fbfe5a1c5e11d030a823c1a61055b28e4971327">2fbfe5a1c5e11d030a823c1a61055b28e4971327</a></p>6 out of 6 jobs PASSED<details><summary><strong>6 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-1.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/82/">test-subrepository-acceptance-pullrequest(7.1.x)</a></li><li><a href="https://test-1-19.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/602/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/601/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-19.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/603/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></li><li><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/86/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/88/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/82/jenkins-report.html">here</a>.</h5></details></html>

2019-09-18 22:23 UTC, ethanbustad requested changes
Nice, @andrea-ale-sbarra, the only problem I see is we need to assign the result of the `ListUtil.sort` call back to the `results` variable -- otherwise, _if_ it's an unmodifiable list, we won't have access to the sorted result. (If the list is modifiable, then obviously the sort will be done on the original list, so we'll have access to the sort in that case.)

2019-09-19 07:40 UTC, andrea-ale-sbarra commented
ci:test

2019-09-19 07:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/35/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/35/jenkins-report.html">here</a>.</b></p>

2019-09-19 08:20 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 34 minutes 12 seconds 514 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/2fbfe5a1c5e11d030a823c1a61055b28e4971327">2fbfe5a1c5e11d030a823c1a61055b28e4971327</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/151//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/151//testReport">here</a>.</h5></div></html>

2019-09-19 09:23 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test - 6 out of 6 jobs passed in 1 hour 41 minutes 33 seconds 149 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/2fbfe5a1c5e11d030a823c1a61055b28e4971327">2fbfe5a1c5e11d030a823c1a61055b28e4971327</a></p>6 out of 6 jobs PASSED<details><summary><strong>6 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/35/">test-subrepository-acceptance-pullrequest(7.1.x)</a></li><li><a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/621/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/620/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/622/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></li><li><a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/78/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/151/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/35/jenkins-report.html">here</a>.</h5></details></html>

2019-09-20 21:01 UTC, ethanbustad approved these changes

2019-09-24 21:00 UTC, merged