COMMERCE-1961 Reset form validation if they're changing to an existing address
liferay/com-liferay-commerce pull request #1389
Opened 2019-09-16 18:41 UTC by alecsloan

2019-09-16 18:41 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2019-09-16 18:41 UTC, alecsloan commented
ci:test

2019-09-16 18:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/81/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-4.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/81/jenkins-report.html">here</a>.</b></p>

2019-09-16 18:48 UTC, ethanbustad approved these changes

2019-09-16 18:50 UTC, ethanbustad requested changes

2019-09-16 18:50 UTC, ethanbustad commented on commerce-checkout-web/src/main/resources/META-INF/resources/checkout_step/address.jsp
> +					Liferay.Form.get("<portlet:namespace />fm").formValidator.validate();
Actually can you change these to single quotes? Looks like every other JS string in this file is single-quoted, so it'd be great to keep it consistent.

2019-09-16 19:08 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 21 minutes 26 seconds 853 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/35bc62f331acdd6cc6464f398d0616438ef80bd5">35bc62f331acdd6cc6464f398d0616438ef80bd5</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/142//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/142//testReport">here</a>.</h5></div></html>

2019-09-16 19:15 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test - 1 out of 3 jobs passed in 31 minutes 29 seconds 614 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/35bc62f331acdd6cc6464f398d0616438ef80bd5">35bc62f331acdd6cc6464f398d0616438ef80bd5</a></p>1 out of 3 jobs PASSED<div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/81/"><strike><strong>test-subrepository-acceptance-pullrequest(7.1.x)</strong></strike></a></li><li><a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/48/"><strike><strong>test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</strong></strike></a></li></ul></div><details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/142/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/81/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/48/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/AXIS_VARIABLE=tomcat,label_exp=!master/48//consoleText">AXIS_VARIABLE=tomcat,label_exp=!master #48</a><div><p>Please fix <strong>semantic versioning</strong> on <strong><a href="https://github.com/alecsloan/com-liferay-commerce/tree/COMMERCE-1961">alecsloan/COMMERCE-1961</a></strong><pre><code>     [exec] 	~   class      com.liferay.portal.kernel.template.TemplateHandlerRegistryUtil
     [exec] 		+   annotated  aQute.bnd.annotation.ProviderType
     [exec] 	+   version    7.2.0
     [exec] 	-   version    7.2.1
     [exec] * com.liferay.portal.kernel.upgrade.util             CHANGED    7.0.0      7.0.1      7.0.2      VERSION INCREASE REQUIRED
     [exec] 	~   class      com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil
     [exec] 		+   annotated  aQute.bnd.annotation.ProviderType
     [exec] 	+   version    7.0.0
     [exec] 	-   version    7.0.1
     [exec] * com.liferay.portal.kernel.words                    CHANGED    1.0.0      1.0.1      1.0.2      VERSION INCREASE REQUIRED
     [exec] 	~   class      com.liferay.portal.kernel.words.WordsUtil
     [exec] 		+   annotated  aQute.bnd.annotation.ProviderType
     [exec] 	+   version    1.0.0
     [exec] 	-   version    1.0.1
     [exec] * com.liferay.portal.kernel.xml                      CHANGED    7.0.0      7.0.1      7.0.2      VERSION INCREASE REQUIRED
     [exec] 	~   class      com.liferay.portal.kernel.xml.SAXReaderUtil
     [exec] 		+   annotated  aQute.bnd.annotation.ProviderType
     [exec] 	+   version    7.0.0
     [exec] 	-   version    7.0.1
     [exec] * com.liferay.portal.kernel.zip                      CHANGED    6.4.0      6.4.1      6.4.2      VERSION INCREASE REQUIRED
     [exec] 	~   class      com.liferay.portal.kernel.zip.ZipReaderFactoryUtil
     [exec] 		+   annotated  aQute.bnd.annotation.ProviderType
     [exec] 	~   class      com.liferay.portal.kernel.zip.ZipWriterFactoryUtil
     [exec] 		+   annotated  aQute.bnd.annotation.ProviderType
     [exec] 	+   version    6.4.0
     [exec] 	-   version    6.4.1
     [exec] * com.liferay.trash.kernel.util                      CHANGED    1.0.0      1.0.1      1.0.2      VERSION INCREASE REQUIRED
     [exec] 	~   class      com.liferay.trash.kernel.util.TrashUtil
     [exec] 		+   annotated  aQute.bnd.annotation.ProviderType
     [exec] 	+   version    1.0.0
     [exec] 	-   version    1.0.1
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal-7.1.x/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal-7.1.x/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/2.119.1/5e8932c382eeec8f29a856c28d7c68cc7685e8/com.liferay.portal.kernel-2.119.1.jar</code></pre></p></div></div></li></ol></div></li></ol></details></html>

2019-09-16 19:47 UTC, ethanbustad commented
ugh, baseline issues in portal. gonna just have to wait for them to be resolved I think

2019-09-17 09:39 UTC, alecsloan commented
ci:test

2019-09-17 09:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/161/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/161/jenkins-report.html">here</a>.</b></p>

2019-09-17 10:01 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 20 minutes 9 seconds 342 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/35bc62f331acdd6cc6464f398d0616438ef80bd5">35bc62f331acdd6cc6464f398d0616438ef80bd5</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/144//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/144//testReport">here</a>.</h5></div></html>

2019-09-17 10:43 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test - 6 out of 6 jobs passed in 1 hour 3 minutes 35 seconds 46 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/35bc62f331acdd6cc6464f398d0616438ef80bd5">35bc62f331acdd6cc6464f398d0616438ef80bd5</a></p>6 out of 6 jobs PASSED<details><summary><strong>6 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/161/">test-subrepository-acceptance-pullrequest(7.1.x)</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/720/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/719/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/611/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></li><li><a href="https://test-1-6.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/67/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/144/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/161/jenkins-report.html">here</a>.</h5></details></html>

2019-09-17 13:14 UTC, merged