COMMERCE-619 product subscriptions
liferay/com-liferay-commerce pull request #139
Opened 2018-09-10 13:32 UTC by luca-pellizzon

@marco-leo here the right branch based PR.

2018-09-10 13:32 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2018-09-10 13:32 UTC, luca-pellizzon commented
ci:test

2018-09-10 13:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/24/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-22.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/24/jenkins-report.html">here</a>.</b></p>

2018-09-10 13:53 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 16 minutes 53 seconds 915 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/053db72762d6527d7019878d7b655ec5dbd256d0">053db72762d6527d7019878d7b655ec5dbd256d0</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :white_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :white_check_mark:</li><li>subrepository-pmd-jdk8 -  :white_check_mark:</li><li>subrepository-source-format-jdk8 -  :white_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/16//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>3 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/16//testReport">here</a>.</h5></div></html>

2018-09-10 15:23 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test - 6 out of 6 jobs passed in 1 hour 50 minutes 26 seconds 951 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/053db72762d6527d7019878d7b655ec5dbd256d0">053db72762d6527d7019878d7b655ec5dbd256d0</a></p>6 out of 6 jobs PASSED<details><summary><strong>6 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/24/">test-subrepository-acceptance-pullrequest(7.1.x)</a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/4/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/8/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/32/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql56-jdk8</a></li><li><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/7/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/16/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-22.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/24/jenkins-report.html">here</a>.</h5></details></html>

2018-09-10 20:01 UTC, ethanbustad requested changes
Could you also include a buildLang commit, @luca-pellizzon?

2018-09-10 20:01 UTC, ethanbustad commented on commerce-product-api/src/main/java/com/liferay/commerce/product/constants/CPConstants.java
> +	public static final String SUBSCRIPTION_DAYS = "day";
Shouldn't this be called `SUBSCRIPTION_DAY` (to match the other names)?

2018-09-10 20:01 UTC, ethanbustad commented on commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/servlet/taglib/ui/CPInstanceSubscriptionInfoScreenNavigationEntry.java
> + * @author Alessio Antonio Rendina
Did you mean to list Alessio as the author here?

2018-09-10 20:01 UTC, ethanbustad commented on commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/display/context/CPDefinitionSubscriptionInfoDisplayContext.java
> + * @author Pellizzon Luca
Not sure whether this was intentional, but elsewhere you've listed your authorship as "Luca Pellizzon". I think consistency would be good, whichever way you want it.

2018-09-10 20:01 UTC, ethanbustad commented on commerce-product-service/service.xml
> +		<column name="subscriptionEnabled" type="boolean" />
Can you sort these new fields above the `status*` fields? By convention, `status`, `statusByUserId`, `statusByUserName`, and `statusDate` should be the last fields on a table.

2018-09-10 20:01 UTC, ethanbustad commented on commerce-product-service/service.xml
> +		<column name="subscriptionEnabled" type="boolean" />
These as well.

2018-09-10 20:01 UTC, ethanbustad commented on commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/portlet/action/EditCPDefinitionMVCActionCommand.java
> +
Don't need this extra newline on line 451.

2018-09-10 20:01 UTC, ethanbustad commented on commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/portlet/action/EditCPDefinitionMVCActionCommand.java
> +		ServiceContext serviceContext = ServiceContextFactory.getInstance(
This should probably go after all the `ParamUtil` variables, since it's used last in the `_cpDefinitionService.updateSubscriptionInfo` method call.

2018-09-10 20:01 UTC, ethanbustad commented on commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/portlet/action/EditCPInstanceMVCActionCommand.java
> +		ServiceContext serviceContext = ServiceContextFactory.getInstance(
Same note on sorting and newlines here as in `EditCPDefinitionMVCActionCommand.java`.

2018-09-11 10:26 UTC, luca-pellizzon commented
ci:retest

2018-09-11 10:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/3/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-9.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/3/jenkins-report.html">here</a>.</b></p>

2018-09-11 10:57 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 20 minutes 37 seconds 497 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/053db72762d6527d7019878d7b655ec5dbd256d0">053db72762d6527d7019878d7b655ec5dbd256d0</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :x:<pre><code>     [echo] Download http://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.upload.api/2.0.0/com.liferay.upload.api-2.0.0.jar
     [echo] :apps:commerce:commerce-product-catalog-rule-web:compileJava
     [echo] :apps:commerce:commerce-product-content-category-web:compileJava
     [echo] :apps:commerce:commerce-product-content-search-web:compileJava
     [echo] Download http://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.portal.search.web.api/2.0.0/com.liferay.portal.search.web.api-2.0.0.pom
     [echo] Download http://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/commerce/com.liferay.commerce.product.taglib/1.0.0/com.liferay.commerce.product.taglib-1.0.0.pom
     [echo] Download http://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.portal.search.web.api/2.0.0/com.liferay.portal.search.web.api-2.0.0.jar
     [echo] Download http://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/commerce/com.liferay.commerce.product.taglib/1.0.0/com.liferay.commerce.product.taglib-1.0.0.jar
     [echo] :apps:commerce:commerce-product-content-web:compileJava
     [echo] Download http://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/commerce/com.liferay.commerce.cart.taglib/1.0.0/com.liferay.commerce.cart.taglib-1.0.0.pom
     [echo] Download http://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/commerce/com.liferay.commerce.cart.taglib/1.0.0/com.liferay.commerce.cart.taglib-1.0.0.jar
     [echo] :apps:commerce:commerce-product-definitions-web:compileJava
     [echo] Download http://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.asset.api/1.0.0/com.liferay.asset.api-1.0.0.pom
     [echo] Download http://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.trash.taglib/3.0.0/com.liferay.trash.taglib-3.0.0.pom
     [echo] Download http://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.asset.api/1.0.0/com.liferay.asset.api-1.0.0.jar
     [echo] Download http://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.trash.taglib/3.0.0/com.liferay.trash.taglib-3.0.0.jar
     [echo] :apps:commerce:commerce-product-definitions-web:compileJava FAILED
     [echo] 
     [echo] BUILD FAILED
     [echo] 
     [echo] </code></pre></li><li>subrepository-semantic-versioning-jdk8 -  :x:<pre><code>     [echo] :apps:commerce:commerce-product-content-category-web:jar
     [echo] :apps:commerce:commerce-product-content-category-web:baseline
     [echo] :apps:commerce:commerce-product-content-category-web:syncVersions
     [echo] :apps:commerce:commerce-product-content-search-web:compileJava
     [echo] :apps:commerce:commerce-product-content-search-web:buildCSS UP-TO-DATE
     [echo] :apps:commerce:commerce-product-content-search-web:processResources
     [echo] :apps:commerce:commerce-product-content-search-web:transpileJS SKIPPED
     [echo] :apps:commerce:commerce-product-content-search-web:configJSModules SKIPPED
     [echo] :apps:commerce:commerce-product-content-search-web:copyLibs SKIPPED
     [echo] :apps:commerce:commerce-product-content-search-web:mergeLang
     [echo] :apps:commerce:commerce-product-content-search-web:replaceSoyTranslation UP-TO-DATE
     [echo] :apps:commerce:commerce-product-content-search-web:wrapSoyAlloyTemplate SKIPPED
     [echo] :apps:commerce:commerce-product-content-search-web:classes
     [echo] :apps:commerce:commerce-product-content-search-web:jar
     [echo] :apps:commerce:commerce-product-content-search-web:baseline
     [echo] :apps:commerce:commerce-product-content-search-web:syncVersions
     [echo] :apps:commerce:commerce-product-content-web:compileJava
     [echo] :apps:commerce:commerce-product-content-web:buildCSS
     [echo] Using native Sass compiler
     [echo] Parsed /META-INF/resources/product_publisher/css/main.scss in 371ms
     [echo] :apps:commerce:commerce-product-content-web:processResources
     [echo] :apps:commerce:commerce-product-content-web:transpileJS SKIPPED
     [echo] :apps:commerce:commerce-product-content-web:configJSModules SKIPPED
     [echo] :apps:commerce:commerce-product-content-web:copyLibs SKIPPED
     [echo] :apps:commerce:commerce-product-content-web:mergeLang
     [echo] :apps:commerce:commerce-product-content-web:replaceSoyTranslation UP-TO-DATE
     [echo] :apps:commerce:commerce-product-content-web:wrapSoyAlloyTemplate SKIPPED
     [echo] :apps:commerce:commerce-product-content-web:classes
     [echo] :apps:commerce:commerce-product-content-web:jar
     [echo] :apps:commerce:commerce-product-content-web:baseline
     [echo] :apps:commerce:commerce-product-content-web:syncVersions
     [echo] :apps:commerce:commerce-product-definitions-web:compileJava FAILED
     [echo] 
     [echo] BUILD FAILED
     [echo] 
     [echo] </code></pre></li></ul><h5>For full console, click <a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/8//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><h5>No tests were run.</h5></div></html>

2018-09-13 13:57 UTC, luca-pellizzon commented
check https://github.com/liferay/com-liferay-commerce/pull/141

2018-09-13 13:57 UTC, closed without merging