COMMERCE-1844 Auto import regions of main countries out of box
liferay/com-liferay-commerce pull request #1484
Opened 2019-10-07 14:45 UTC by riccardo-alberti

Added auto import regions for: ESP, CHN, CUW, FIN, FRA, DEU, ISR, HUN, JPN, BRA, GBR, IND, CAN, KOR, RUS, AUS, MEX, IDN, NLD, TUR, CHE, SAU, ARG, POL

2019-10-07 14:46 UTC, riccardo-alberti commented
ci:test

2019-10-07 18:23 UTC, ethanbustad commented
Hey @riccardo-alberti, you'll need to follow these steps before CI will respond to test commands: https://grow.liferay.com/people/Pull+Request+Tester+for+Liferay+Developers.

2019-10-07 18:43 UTC, ethanbustad approved these changes
Nice job, @riccardo-alberti ! Looks great. We could consider reducing duplication in the `CommerceRegionsStarter`s, but they're already slim enough that this isn't particularly important in my mind. Nicely done!

2019-10-07 18:44 UTC, ethanbustad commented
And congratulations on your first Commerce PR! 🎉 🚀

2019-10-07 18:46 UTC, marco-leo commented
@riccardo-alberti @ethanbustad  I would like to create a base class or a Util, as looks like most of the json parsing code is duplicated.  What do you think?

2019-10-07 18:53 UTC, ethanbustad commented
> @riccardo-alberti @ethanbustad I would like to create a base class or a Util, as looks like most of the json parsing code is duplicated. What do you think?

Yeah a base class was my first thought as well -- it just requires a bit of boilerplate still that way. But I think it'd be great to reduce duplication however we can.

2019-10-07 19:00 UTC, riccardo-alberti commented
> > @riccardo-alberti @ethanbustad I would like to create a base class or a Util, as looks like most of the json parsing code is duplicated. What do you think?
> 
> Yeah a base class was my first thought as well -- it just requires a bit of boilerplate still that way. But I think it'd be great to reduce duplication however we can.

Yep agreed... i'll work on this

2019-10-07 20:04 UTC, marco-leo commented
ci:test

2019-10-07 20:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/104/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/104/jenkins-report.html">here</a>.</b></p>

2019-10-07 20:28 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 20 minutes 18 seconds 50 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/fa8174a94a593653a535cb1a38984d907f449938">fa8174a94a593653a535cb1a38984d907f449938</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/105//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/105//testReport">here</a>.</h5></div></html>

2019-10-07 21:10 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test - 11 out of 13 jobs passed in 1 hour 5 minutes 44 seconds 869 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/fa8174a94a593653a535cb1a38984d907f449938">fa8174a94a593653a535cb1a38984d907f449938</a></p>11 out of 13 jobs PASSED<div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/104/"><strike><strong>test-subrepository-acceptance-pullrequest(7.1.x)</strong></strike></a></li><li><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/674/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</strong></strike></a></li></ul></div><details><summary><strong>11 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/501/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/745/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/607/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/743/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/744/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/608/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/673/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/746/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/502/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/74/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/105/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/104/jenkins-report.html">here</a>.</h5><hr/><h4>Failures (upstream comparison is not available):</h4><ol><li><div><h5><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/674/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></h5><div><h6>Job Results:</h6><p>2 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=1,label_exp=!master/674//consoleText">AXIS_VARIABLE=1,label_exp=!master #674</a><pre><code>    [junit] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
    [junit] 	at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:969)
    [junit] 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
    [junit] 	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1393)
    [junit] 	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1382)
    [junit] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    [junit] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
    [junit] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
    [junit] 	at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:969)
    [junit] 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
    [junit] 	at org.apache.catalina.core.StandardService.stopInternal(StandardService.java:475)
    [junit] 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
    [junit] 	at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:990)
    [junit] 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
    [junit] 	at org.apache.catalina.startup.Catalina.stop(Catalina.java:707)
    [junit] 	at org.apache.catalina.startup.Catalina.start(Catalina.java:669)
    [junit] 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:350)
    [junit] 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)
    [junit] 
    [junit] 
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanOSGiLog(PortalLogAssertorTest.java:81)
    [junit] 
    [junit] 
    [junit] Test com.liferay.portal.log.assertor.PortalLogAssertorTest FAILED
[stopwatch] [test.cmd: 2.509 sec]
     [exec] Shutting down MySQL..[  OK  ]
[stopwatch] [run.batch.test.action: 13:52.118 sec]
     [echo] 
      [get] Getting: http://test-1-16/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=1,label_exp=!master/674//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal-7.1.x/20191007210928513.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal-7.1.x/20191007210928513.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal-7.1.x/null129279541.properties</code></pre></div></li></ol></div></li></ol></details></html>

2019-10-09 21:16 UTC, ethanbustad requested changes

2019-10-09 21:16 UTC, ethanbustad commented on commerce-service/src/main/java/com/liferay/commerce/internal/starter/ArgentinaCommerceRegionsStarter.java
> +	private static final String layoutsPath =
@riccardo-alberti these `layoutsPath` fields should be `_LAYOUTS_PATH` -- that's our naming convention for private constants.

2019-10-09 21:16 UTC, ethanbustad commented on commerce-service/src/main/java/com/liferay/commerce/internal/starter/CommerceRegionsStarterBase.java
> +public class CommerceRegionsStarterBase {
Should be called `BaseCommerceRegionsStarter`, and in my opinion it should be `abstract` and implement `CommerceRegionsStarter`, to make it clearer how this class is intended to be used.

2019-10-09 21:16 UTC, ethanbustad commented on commerce-service/src/main/java/com/liferay/commerce/internal/starter/CommerceRegionsStarterBase.java
> +	private CommerceCountry getCommerceCountry(long companyId, int isoCode)
`private` method names should start with an underscore -- i.e. `_getCommerceCountry`. Same for the other private methods below.

2019-10-10 03:37 UTC, ethanbustad commented
ci:test

2019-10-10 03:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/181/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/181/jenkins-report.html">here</a>.</b></p>

2019-10-10 04:04 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 23 minutes 9 seconds 692 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/147f756649235a7a80afa4996de847fa85be157f">147f756649235a7a80afa4996de847fa85be157f</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [echo] java.lang.Exception: Found 34 formatting issues:
     [echo] 1: private constant 'layoutsPath' of type 'String' must match pattern '^_[A-Z0-9][_A-Z0-9]*$': ./commerce-service/src/main/java/com/liferay/commerce/internal/starter/ArgentinaCommerceRegionsStarter.java 47 (Checkstyle:ConstantNameCheck)
     [echo] 2: private constant 'layoutsPath' of type 'String' must match pattern '^_[A-Z0-9][_A-Z0-9]*$': ./commerce-service/src/main/java/com/liferay/commerce/internal/starter/AustraliaCommerceRegionsStarter.java 47 (Checkstyle:ConstantNameCheck)
     [echo] 3: private constant 'layoutsPath' of type 'String' must match pattern '^_[A-Z0-9][_A-Z0-9]*$': ./commerce-service/src/main/java/com/liferay/commerce/internal/starter/BrazilCommerceRegionsStarter.java 46 (Checkstyle:ConstantNameCheck)
     [echo] 4: private constant 'layoutsPath' of type 'String' must match pattern '^_[A-Z0-9][_A-Z0-9]*$': ./commerce-service/src/main/java/com/liferay/commerce/internal/starter/CanadaCommerceRegionsStarter.java 46 (Checkstyle:ConstantNameCheck)
     [echo] 5: private constant 'layoutsPath' of type 'String' must match pattern '^_[A-Z0-9][_A-Z0-9]*$': ./commerce-service/src/main/java/com/liferay/commerce/internal/starter/ChinaCommerceRegionsStarter.java 46 (Checkstyle:ConstantNameCheck)
     [echo] 6: Missing copyright: ./commerce-service/src/main/java/com/liferay/commerce/internal/starter/CommerceRegionsStarterBase.java (SourceCheck:CopyrightCheck)
     [echo] 7: Private method 'getCommerceCountry' must match pattern '^_[a-z0-9][_a-zA-Z0-9]*$|readObject|writeObject': ./commerce-service/src/main/java/com/liferay/commerce/internal/starter/CommerceRegionsStarterBase.java 40 (Checkstyle:MethodNameCheck)
     [echo] 8: Private method 'getCommerceRegionsJSONArray' must match pattern '^_[a-z0-9][_a-zA-Z0-9]*$|readObject|writeObject': ./commerce-service/src/main/java/com/liferay/commerce/internal/starter/CommerceRegionsStarterBase.java 47 (Checkstyle:MethodNameCheck)
     [echo] 9: Private method 'init' must match pattern '^_[a-z0-9][_a-zA-Z0-9]*$|readObject|writeObject': ./commerce-service/src/main/java/com/liferay/commerce/internal/starter/CommerceRegionsStarterBase.java 58 (Checkstyle:MethodNameCheck)
     [echo] 10: Private method 'parseAndAddCommerceRegions' must match pattern '^_[a-z0-9][_a-zA-Z0-9]*$|readObject|writeObject': ./commerce-service/src/main/java/com/liferay/commerce/internal/starter/CommerceRegionsStarterBase.java 68 (Checkstyle:MethodNameCheck)</code></pre></li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/170//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/170//testReport">here</a>.</h5></div></html>

2019-10-10 12:53 UTC, marco-leo commented
ci:test

2019-10-10 13:04 UTC, marco-leo requested changes

2019-10-10 13:04 UTC, marco-leo commented on commerce-service/src/main/java/com/liferay/commerce/internal/starter/BaseCommerceRegionsStarter.java
> +		_init(
@riccardo-alberti no need to init

2019-10-10 13:04 UTC, marco-leo commented on commerce-service/src/main/java/com/liferay/commerce/internal/starter/BaseCommerceRegionsStarter.java
> +	protected void start(
@riccardo-alberti never pass refernce in method, use constructor

2019-10-10 13:04 UTC, marco-leo commented on commerce-service/src/main/java/com/liferay/commerce/internal/starter/BaseCommerceRegionsStarter.java
> +	private CommerceCountryLocalService _commerceCountryLocalService;
@riccardo-alberti maybe is better to use -dsannotations-options: inherit

2019-10-10 13:04 UTC, marco-leo commented on commerce-service/src/main/java/com/liferay/commerce/internal/starter/BaseCommerceRegionsStarter.java
> +	private CommerceCountry _getCommerceCountry(long companyId, int isoCode)
@riccardo-alberti no need to wrap one 1 line in one method

2019-10-10 13:04 UTC, marco-leo commented on commerce-service/src/main/java/com/liferay/commerce/internal/starter/BaseCommerceRegionsStarter.java
> +		_parseAndAddCommerceRegions(
_importCommerceRegions

2019-10-10 13:04 UTC, marco-leo commented on commerce-service/src/main/java/com/liferay/commerce/internal/starter/BaseCommerceRegionsStarter.java
> +	protected void start(
The start method will be public and will implement th eone from the interface

2019-10-10 13:04 UTC, marco-leo commented on commerce-service/src/main/java/com/liferay/commerce/internal/starter/BrazilCommerceRegionsStarter.java
> +	private static final String _LAYOUTS_PATH =
@riccardo-alberti  the base class will have an abstact method getFilePath, thos classes willovveride just that method

2019-10-10 13:19 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 22 minutes 29 seconds 627 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/147f756649235a7a80afa4996de847fa85be157f">147f756649235a7a80afa4996de847fa85be157f</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [echo] java.lang.Exception: Found 34 formatting issues:
     [echo] 1: private constant 'layoutsPath' of type 'String' must match pattern '^_[A-Z0-9][_A-Z0-9]*$': ./commerce-service/src/main/java/com/liferay/commerce/internal/starter/ArgentinaCommerceRegionsStarter.java 47 (Checkstyle:ConstantNameCheck)
     [echo] 2: private constant 'layoutsPath' of type 'String' must match pattern '^_[A-Z0-9][_A-Z0-9]*$': ./commerce-service/src/main/java/com/liferay/commerce/internal/starter/AustraliaCommerceRegionsStarter.java 47 (Checkstyle:ConstantNameCheck)
     [echo] 3: private constant 'layoutsPath' of type 'String' must match pattern '^_[A-Z0-9][_A-Z0-9]*$': ./commerce-service/src/main/java/com/liferay/commerce/internal/starter/BrazilCommerceRegionsStarter.java 46 (Checkstyle:ConstantNameCheck)
     [echo] 4: private constant 'layoutsPath' of type 'String' must match pattern '^_[A-Z0-9][_A-Z0-9]*$': ./commerce-service/src/main/java/com/liferay/commerce/internal/starter/CanadaCommerceRegionsStarter.java 46 (Checkstyle:ConstantNameCheck)
     [echo] 5: private constant 'layoutsPath' of type 'String' must match pattern '^_[A-Z0-9][_A-Z0-9]*$': ./commerce-service/src/main/java/com/liferay/commerce/internal/starter/ChinaCommerceRegionsStarter.java 46 (Checkstyle:ConstantNameCheck)
     [echo] 6: Missing copyright: ./commerce-service/src/main/java/com/liferay/commerce/internal/starter/CommerceRegionsStarterBase.java (SourceCheck:CopyrightCheck)
     [echo] 7: Private method 'getCommerceCountry' must match pattern '^_[a-z0-9][_a-zA-Z0-9]*$|readObject|writeObject': ./commerce-service/src/main/java/com/liferay/commerce/internal/starter/CommerceRegionsStarterBase.java 40 (Checkstyle:MethodNameCheck)
     [echo] 8: Private method 'getCommerceRegionsJSONArray' must match pattern '^_[a-z0-9][_a-zA-Z0-9]*$|readObject|writeObject': ./commerce-service/src/main/java/com/liferay/commerce/internal/starter/CommerceRegionsStarterBase.java 47 (Checkstyle:MethodNameCheck)
     [echo] 9: Private method 'init' must match pattern '^_[a-z0-9][_a-zA-Z0-9]*$|readObject|writeObject': ./commerce-service/src/main/java/com/liferay/commerce/internal/starter/CommerceRegionsStarterBase.java 58 (Checkstyle:MethodNameCheck)
     [echo] 10: Private method 'parseAndAddCommerceRegions' must match pattern '^_[a-z0-9][_a-zA-Z0-9]*$|readObject|writeObject': ./commerce-service/src/main/java/com/liferay/commerce/internal/starter/CommerceRegionsStarterBase.java 68 (Checkstyle:MethodNameCheck)</code></pre></li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/193//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/193//testReport">here</a>.</h5></div></html>

2019-10-10 15:31 UTC, riccardo-alberti commented
ci:test

2019-10-10 17:14 UTC, ethanbustad commented
ci:test

2019-10-10 17:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/141/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/141/jenkins-report.html">here</a>.</b></p>

2019-10-10 17:40 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 23 minutes 10 seconds 191 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/dbe4d076023ed9192dfb219a60edba712db78246">dbe4d076023ed9192dfb219a60edba712db78246</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/124//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/124//testReport">here</a>.</h5></div></html>

2019-10-10 17:44 UTC, ethanbustad approved these changes
Beautiful.

2019-10-10 18:39 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test - 13 out of 13 jobs passed in 1 hour 24 minutes 41 seconds 476 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/dbe4d076023ed9192dfb219a60edba712db78246">dbe4d076023ed9192dfb219a60edba712db78246</a></p>13 out of 13 jobs PASSED<details><summary><strong>13 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/141/">test-subrepository-acceptance-pullrequest(7.1.x)</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/814/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/813/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/534/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/811/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/812/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/816/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-10.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/265/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/815/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/535/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/487/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></li><li><a href="https://test-1-1.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/59/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/124/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/141/jenkins-report.html">here</a>.</h5></details></html>

2019-10-10 20:55 UTC, marco-leo commented
@riccardo-alberti Good job and congratulation on your first contribution to Liferay Commerce!

2019-10-10 20:56 UTC, merged