Commerce 1453 (SF fixes from Luca)
liferay/com-liferay-commerce pull request #1497
Opened 2019-10-09 19:10 UTC by alecsloan

From #1172

2019-10-09 19:10 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2019-10-09 19:10 UTC, alecsloan commented
ci:test

2019-10-09 19:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/182/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-5.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/182/jenkins-report.html">here</a>.</b></p>

2019-10-09 19:26 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 13 minutes 5 seconds 360 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/a3bd90ff8d9b593848a9a3291d738d5d5731415a">a3bd90ff8d9b593848a9a3291d738d5d5731415a</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :x:<pre><code>     [echo] * What went wrong:
     [echo] Execution failed for task ':apps:commerce:commerce-product-definitions-web:compileJSP'.
     [echo] &gt; Compilation failed; see the compiler error output for details.
     [echo] 
     [echo] * Try:
     [echo] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [echo] 
     [echo] * Exception is:
     [echo] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:commerce:commerce-product-definitions-web:compileJSP'.
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
     [echo] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
     [echo] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
     [echo] 	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
     [echo] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
     [echo] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)</code></pre></li><li>central-requirements-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/190//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>7 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/190//testReport">here</a>.</h5></div></html>

2019-10-09 20:53 UTC, alecsloan commented
ci:test

2019-10-09 20:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-1.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/99/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-1.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/99/jenkins-report.html">here</a>.</b></p>

2019-10-09 21:14 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 18 minutes 596 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/a3bd90ff8d9b593848a9a3291d738d5d5731415a">a3bd90ff8d9b593848a9a3291d738d5d5731415a</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/191//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/191//testReport">here</a>.</h5></div></html>

2019-10-09 21:55 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test - 13 out of 13 jobs passed in 1 hour 1 minute 24 seconds 360 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/a3bd90ff8d9b593848a9a3291d738d5d5731415a">a3bd90ff8d9b593848a9a3291d738d5d5731415a</a></p>13 out of 13 jobs PASSED<details><summary><strong>13 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-1.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/99/">test-subrepository-acceptance-pullrequest(7.1.x)</a></li><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/530/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/956/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-6.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/593/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/955/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/378/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/957/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/633/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/625/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/379/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/817/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></li><li><a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/91/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/191/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/99/jenkins-report.html">here</a>.</h5></details></html>

2019-10-10 19:14 UTC, ethanbustad commented
@alecsloan requires another rebase :(

2019-10-10 19:15 UTC, alecsloan commented
I'll rebase when @marco-leo's ready to merge ;)

2019-10-10 19:55 UTC, ethanbustad requested changes

2019-10-10 19:55 UTC, ethanbustad commented on commerce-catalog-web/src/main/java/com/liferay/commerce/catalog/web/internal/display/context/BaseCommerceCatalogDisplayContext.java
> +	protected final CommerceCatalogRequestHelper requestHelper;
`CommerceCatalogRequestHelper requestHelper` should be `CommerceCatalogRequestHelper commerceCatalogRequestHelper`

2019-10-10 19:55 UTC, ethanbustad commented on commerce-channel-web/src/main/java/com/liferay/commerce/channel/web/internal/display/context/BaseCommerceChannelDisplayContext.java
> +	protected final CommerceChannelRequestHelper requestHelper;
`CommerceCatalogRequestHelper requestHelper` should be `CommerceCatalogRequestHelper commerceCatalogRequestHelper`

2019-10-10 19:55 UTC, ethanbustad commented on commerce-item-selector-web/src/main/java/com/liferay/commerce/item/selector/web/internal/display/context/BaseCommerceItemSelectorViewDisplayContext.java
> +	protected final CommerceItemSelectorRequestHelper requestHelper;
`CommerceCatalogRequestHelper requestHelper` should be `CommerceCatalogRequestHelper commerceCatalogRequestHelper`

2019-10-10 19:55 UTC, ethanbustad commented on commerce-order-content-web/src/main/java/com/liferay/commerce/order/content/web/internal/display/context/CommerceOrderContentDisplayContext.java
> +	private final CommerceOrderRequestHelper _cpRequestHelper;
`CommerceOrderRequestHelper _cpRequestHelper` should be `CommerceOrderRequestHelper _commerceOrderRequestHelper`

2019-10-10 19:55 UTC, ethanbustad commented on commerce-product-content-search-web/src/main/java/com/liferay/commerce/product/content/search/web/internal/display/context/CPSearchResultsDisplayContext.java
> +	private final CPSearchResultsRequestHelper _cpRequestHelper;
`CPSearchResultsRequestHelper _cpRequestHelper` should be `CPSearchResultsRequestHelper _cpSearchResultsRequestHelper`

2019-10-10 19:55 UTC, ethanbustad commented on commerce-product-content-web/src/main/java/com/liferay/commerce/product/content/web/internal/display/context/CPCompareContentDisplayContext.java
> +	private final CPContentRequestHelper _cpRequestHelper;
`CPContentRequestHelper _cpRequestHelper` should be `CPContentRequestHelper _cpContentRequestHelper`

2019-10-10 19:55 UTC, ethanbustad commented on commerce-product-content-web/src/main/java/com/liferay/commerce/product/content/web/internal/display/context/CPCompareContentMiniDisplayContext.java
> +	private final CPContentRequestHelper _cpRequestHelper;
`CPContentRequestHelper _cpRequestHelper` should be `CPContentRequestHelper _cpContentRequestHelper`

2019-10-10 19:55 UTC, ethanbustad commented on commerce-product-item-selector-web/src/main/java/com/liferay/commerce/product/item/selector/web/internal/display/context/BaseCPItemSelectorViewDisplayContext.java
> +	protected final CPItemSelectorRequestHelper requestHelper;
`CPItemSelectorRequestHelper requestHelper` should be `CPItemSelectorRequestHelper cpItemSelectorRequestHelper`

2019-10-10 19:55 UTC, ethanbustad commented on commerce-product-options-web/src/main/java/com/liferay/commerce/product/options/web/internal/display/context/BaseCPOptionsDisplayContext.java
> +	protected final CPOptionsRequestHelper requestHelper;
`CPOptionsRequestHelper requestHelper` should be `CPOptionsRequestHelper cpOptionsRequestHelper`

2019-10-10 19:55 UTC, ethanbustad commented on commerce-shipment-web/src/main/java/com/liferay/commerce/shipment/web/internal/display/context/BaseCommerceShipmentDisplayContext.java
> +	protected final CommerceShipmentRequestHelper requestHelper;
`CommerceShipmentRequestHelper requestHelper` should be `CommerceShipmentRequestHelper commerceShipmentRequestHelper`

2019-10-10 19:55 UTC, ethanbustad commented on commerce-subscription-web/src/main/java/com/liferay/commerce/subscription/web/internal/display/context/CommerceSubscriptionContentDisplayContext.java
> +	private final CommerceSubscriptionRequestHelper _cpRequestHelper;
`CommerceSubscriptionRequestHelper _cpRequestHelper` should be `CommerceSubscriptionRequestHelper _commerceSubscriptionRequestHelper`

2019-10-10 19:55 UTC, ethanbustad commented on commerce-subscription-web/src/main/java/com/liferay/commerce/subscription/web/internal/display/context/CommerceSubscriptionEntryDisplayContext.java
> +	private final CommerceSubscriptionRequestHelper _cpRequestHelper;
`CommerceSubscriptionRequestHelper _cpRequestHelper` should be `CommerceSubscriptionRequestHelper _commerceSubscriptionRequestHelper`

2019-10-10 19:55 UTC, ethanbustad commented on commerce-price-list-web/src/main/java/com/liferay/commerce/price/list/web/internal/display/context/BaseCommercePriceListDisplayContext.java
> +	protected CommercePriceListRequestHelper requestHelper;
`CommercePriceListRequestHelper requestHelper` should be `CommercePriceListRequestHelper commercePriceListRequestHelper`

2019-10-10 19:55 UTC, ethanbustad commented on commerce-product-content-search-web/src/main/java/com/liferay/commerce/product/content/search/web/internal/portlet/action/CPSearchResultsConfigurationAction.java
> +		CPSearchResultsRequestHelper cpRequestHelper =
`CPSearchResultsRequestHelper cpRequestHelper` should be `CPSearchResultsRequestHelper cpSearchResultsRequestHelper`

2019-10-10 19:55 UTC, ethanbustad commented on commerce-product-definitions-api/src/main/java/com/liferay/commerce/product/definitions/display/context/BaseCPDefinitionsDisplayContext.java
> +	protected final CPDefinitionRequestHelper requestHelper;
same

2019-10-10 19:55 UTC, ethanbustad commented on commerce-product-definitions-api/src/main/java/com/liferay/commerce/product/definitions/display/context/BaseCPDefinitionsSearchContainerDisplayContext.java
> +			getManagementBarFilterItem(WorkflowConstants.STATUS_EXPIRED));
If order matters here, we should add blank lines in between each `add` to make that clear

2019-10-10 19:57 UTC, ethanbustad commented
Oops, @luca-pellizzon @marco-leo, we had some duplicated efforts. My bad. I had already removed the `commerce-product-service` exports under a different ticket in this PR: https://github.com/liferay/com-liferay-commerce/pull/1486. I like some of these changes better than the ones I made, so @marco-leo feel free to just merge this one (or take a look and see what solutions you like better -- we could always do a mix of the 2, too).

2019-10-12 09:53 UTC, marco-leo commented
Sorry, too risky to merge this pull, too many changed introduces, difficult to track

2019-10-12 09:53 UTC, closed without merging

2019-10-12 09:55 UTC, marco-leo commented
@ethanbustad @luca-pellizzon  if we want those changes in we should send smaller PRs. At this point pull like these can't be merged