COMMERCE-1453 Remove SF suppressions for CommerceRegionsStarter and CommerceShippingOriginLocator
liferay/com-liferay-commerce pull request #1513
Opened 2019-10-11 00:23 UTC by alecsloan

2019-10-11 00:23 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2019-10-11 00:24 UTC, alecsloan commented
ci:test

2019-10-11 00:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/238/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/238/jenkins-report.html">here</a>.</b></p>

2019-10-11 00:36 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 9 minutes 9 seconds 109 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/ae7cbe5b686e4a044d58c90a973037b2d0a8cb32">ae7cbe5b686e4a044d58c90a973037b2d0a8cb32</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :x:<pre><code>     [echo] * What went wrong:
     [echo] Execution failed for task ':apps:commerce:commerce-api:baseline'.
     [echo] &gt; Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal-7.1.x/tools/sdk/dist/com.liferay.commerce.api-9.4.0.jar against /opt/dev/projects/github/liferay-portal-7.1.x/.gradle/caches/modules-2/files-2.1/com.liferay.commerce/com.liferay.commerce.api/9.3.0/20763e4380b76f3325ddf8b807da4e9ddc6f5e3f/com.liferay.commerce.api-9.3.0.jar
     [echo] 
     [echo] * Try:
     [echo] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [echo] 
     [echo] * Exception is:
     [echo] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:commerce:commerce-api:baseline'.
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
     [echo] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
     [echo] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
     [echo] 	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
     [echo] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)</code></pre></li><li>central-requirements-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/195//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>7 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/195//testReport">here</a>.</h5></div></html>

2019-10-11 10:02 UTC, marco-leo commented
ci:test

2019-10-11 10:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/26/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/26/jenkins-report.html">here</a>.</b></p>

2019-10-11 10:19 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 10 minutes 38 seconds 158 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/78a50697be7db2312ba759ed4ff925aae4db9107">78a50697be7db2312ba759ed4ff925aae4db9107</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :x:<pre><code>  &lt;redirector errorproperty="error.property" outputproperty="output.property" /&gt;
&lt;/exec&gt;
     [echo] 
      [for] subrepository-semantic-versioning-jdk8: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:27: Subrepository task FAILED: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-test-batch.xml:5576: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-common.xml:1043: Unable to execute Gradle task: baseline.
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:120: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:13: Keepgoing execution: 1 of 3 iterations failed.
[beanshell] 4565 GitHub API calls out of 5000 remain. GitHub API call limit will reset in 35 minutes 37 seconds 168 ms.
[beanshell]     https://api.github.com/repos/liferay/com-liferay-commerce/pulls/1513
[beanshell] Executing commands: cat /tmp/-625784324.txt | mail -v -s "CI Failure has occurred" -r "ci_failure_notification" "qa-slave-verify-fail@liferay.com"
     [echo] A CI failure has occurred. QA Engineering has been notified. Please try again later or contact QA Engineering for an update.

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:11113: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:127: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:120: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:13: Keepgoing execution: 1 of 3 iterations failed.</code></pre></li><li>central-requirements-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/219//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>7 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/219//testReport">here</a>.</h5></div></html>

2019-10-11 16:20 UTC, alecsloan commented
ci:test

2019-10-11 16:20 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-1.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/103/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-1.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/103/jenkins-report.html">here</a>.</b></p>

2019-10-11 16:43 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 21 minutes 6 seconds 997 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/fea80e793c58f81de5c1152e70775c225b073a5a">fea80e793c58f81de5c1152e70775c225b073a5a</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-1.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/110//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-1.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/110//testReport">here</a>.</h5></div></html>

2019-10-11 17:33 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test - 13 out of 13 jobs passed in 1 hour 12 minutes 57 seconds 296 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/fea80e793c58f81de5c1152e70775c225b073a5a">fea80e793c58f81de5c1152e70775c225b073a5a</a></p>13 out of 13 jobs PASSED<details><summary><strong>13 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-1.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/103/">test-subrepository-acceptance-pullrequest(7.1.x)</a></li><li><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/639/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/767/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/490/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/638/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/766/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/640/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/769/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/768/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-15.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/348/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/848/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></li><li><a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/59/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-1.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/110/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/103/jenkins-report.html">here</a>.</h5></details></html>

2019-10-11 17:48 UTC, ethanbustad requested changes

2019-10-11 17:48 UTC, ethanbustad commented on commerce-service/src/main/java/com/liferay/commerce/internal/starter/BaseCommerceRegionsStarter.java
>  				serviceContext.getCompanyId(), getCountryIsoCode());
`serviceContext.getCompanyId()` will return `0` here as is. needs a little revamp

2019-10-11 18:56 UTC, alecsloan commented
ci:test

2019-10-11 18:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/113/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/113/jenkins-report.html">here</a>.</b></p>

2019-10-11 19:19 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 20 minutes 7 seconds 286 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/fea80e793c58f81de5c1152e70775c225b073a5a">fea80e793c58f81de5c1152e70775c225b073a5a</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :x:<pre><code> [sync-dir] 0 files synchronized in 292ms
     [echo] Executing Gradle task: pmdMain
     [echo] 
     [echo] 
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;exec dir="/opt/dev/projects/github/liferay-portal-7.1.x/modules/apps/commerce" executable="/opt/dev/projects/github/liferay-portal-7.1.x/gradlew" failonerror="true"&gt;
  &lt;arg value="pmdTest" /&gt;
  &lt;arg value="pmdTestIntegration" /&gt;
  &lt;arg value="--max-workers=4" /&gt;
  &lt;arg value="--no-daemon" /&gt;
  &lt;arg value="--profile" /&gt;
  &lt;arg value="--project-cache-dir=/opt/dev/projects/github/liferay-portal-7.1.x/.gradle" /&gt;
  &lt;arg value="--refresh-dependencies" /&gt;
  &lt;arg value="--stacktrace" /&gt;
  &lt;arg value="-Dapp.server.parent.dir=/opt/dev/projects/github/liferay-portal-7.1.x/bundles" /&gt;
  &lt;arg value="-Dforced.cache.enabled=true" /&gt;
  &lt;arg value="-Dliferay.home=/opt/dev/projects/github/liferay-portal-7.1.x/bundles" /&gt;
  &lt;arg value="-Dliferay.ssl.context.enabled=true" /&gt;
  &lt;arg value="-Dorg.gradle.internal.http.connectionTimeout=120000" /&gt;
  &lt;arg value="-Dorg.gradle.internal.http.socketTimeout=120000" /&gt;
  &lt;arg value="-Dpatcher.hotfix.dirs=" /&gt;
  &lt;arg value="-Dpatcher.hotfix.qualifier=" /&gt;
  &lt;arg line="pmdMain" /&gt;
  &lt;env key="GRADLE_OPTS" value="-Dhttp.nonProxyHosts=&amp;quot;cloud*|files.liferay.org.es|it.liferay.com|localhost|mirrors-no-cache.lax.liferay.com|release*|test*&amp;quot; -Dhttp.proxyHost=squid.lax.liferay.com -Dhttp.proxyPort=3128 -server -verbose:gc -Xloggc:/tmp/ant-gc.log -Xms1024m -Xmx3072m -Xss2m -Xverify:none -XX:+DisableExplicitGC -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintGCCause -XX:+PrintGCDetails -XX:+UseParallelOldGC -XX:HeapDumpPath=/tmp/ant-oom-heap-dump.bin -XX:MaxNewSize=512m -XX:MaxMetaspaceSize=512m -XX:MaxTenuringThreshold=0 -XX:NewSize=256m -XX:MetaspaceSize=100m -XX:SurvivorRatio=65536 -XX:TargetSurvivorRatio=0" /&gt;
  &lt;redirector errorproperty="error.property" outputproperty="output.property" /&gt;
&lt;/exec&gt;
     [echo] 
      [for] subrepository-pmd-jdk8: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:27: Subrepository task FAILED: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-test-batch.xml:5544: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-common.xml:1043: Unable to execute Gradle task: pmdMain.
     [echo] </code></pre></li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [echo] java.lang.Exception: Found 6 formatting issues:
     [echo] 1: Unnecessary semi colon: ./commerce-discount-service/src/main/java/com/liferay/commerce/discount/service/impl/CommerceDiscountLocalServiceImpl.java 411 (Checkstyle:SemiColonCheck)
     [echo] 2: Variable 'now' is unused: ./commerce-product-service/src/main/java/com/liferay/commerce/product/service/impl/CPDefinitionLocalServiceImpl.java 1503 (Checkstyle:UnusedVariableCheck)
     [echo] 3: Variable 'now' is unused: ./commerce-product-service/src/main/java/com/liferay/commerce/product/service/impl/CPDefinitionLocalServiceImpl.java 1607 (Checkstyle:UnusedVariableCheck)
     [echo] 4: Variable 'now' is unused: ./commerce-product-service/src/main/java/com/liferay/commerce/product/service/impl/CPInstanceLocalServiceImpl.java 807 (Checkstyle:UnusedVariableCheck)
     [echo] 5: Variable 'now' is unused: ./commerce-product-service/src/main/java/com/liferay/commerce/product/service/impl/CPInstanceLocalServiceImpl.java 837 (Checkstyle:UnusedVariableCheck)
     [echo] 6: Variable 'now' is unused: ./commerce-product-service/src/main/java/com/liferay/commerce/product/service/impl/CPInstanceLocalServiceImpl.java 925 (Checkstyle:UnusedVariableCheck)
     [echo] 
     [echo] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:438)
     [echo] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:266)
     [echo] 
     [echo] FAILURE: Build failed with an exception.
     [echo] 
     [echo] * What went wrong:
     [echo] Execution failed for task ':checkSourceFormatting'.
     [echo] &gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [echo] 
     [echo] * Try:
     [echo] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [echo] 
     [echo] * Exception is:
     [echo] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':checkSourceFormatting'.
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
     [echo] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)</code></pre></li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/221//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/221//testReport">here</a>.</h5></div></html>

2019-10-11 19:36 UTC, alecsloan commented
ci:test

@marco-leo @ethanbustad Please re-review my last 2 commits

2019-10-11 19:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/144/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-17.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/144/jenkins-report.html">here</a>.</b></p>

2019-10-11 20:02 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 23 minutes 9 seconds 187 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/fea80e793c58f81de5c1152e70775c225b073a5a">fea80e793c58f81de5c1152e70775c225b073a5a</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/50//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/50//testReport">here</a>.</h5></div></html>

2019-10-11 20:41 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test - 10 out of 13 jobs passed in 1 hour 4 minutes 53 seconds 551 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/fea80e793c58f81de5c1152e70775c225b073a5a">fea80e793c58f81de5c1152e70775c225b073a5a</a></p>10 out of 13 jobs PASSED<div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/144/"><strike><strong>test-subrepository-acceptance-pullrequest(7.1.x)</strong></strike></a></li><li><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/976/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/510/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</strong></strike></a></li></ul></div><details><summary><strong>10 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-13.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/509/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/794/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/508/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/793/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-15.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/350/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/795/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-6.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/607/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/977/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/93/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/50/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/144/jenkins-report.html">here</a>.</h5><hr/><h4>Failures (upstream comparison is not available):</h4><ol><li><div><h5><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/976/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>1 Test Passed.<br/>3 Tests Failed.</p></div><ol><li><div><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/976//consoleText">AXIS_VARIABLE=0,label_exp=!master #976</a><ol><li><div><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/976//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog">PortalLogAssertorTest.testScanXMLLog</a><pre><code>junit.framework.AssertionFailedError: 
bundle com.liferay.commerce.service:5.3.0 (480)[com.liferay.commerce.internal.starter.ArgentinaCommerceRegionsStarter(2369)] : findField: Suitable but non-accessible field _commerceCountryLocalService in class com.liferay.commerce.internal.starter.BaseCommerceRegionsStarter, subclass of component class com.liferay.commerce.internal.starter.ArgentinaCommerceRegionsStarter 
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:172)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:98)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:88)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog(PortalLogAssertorTest.java:86)
</code></pre></div></li><li><div><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/976//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanOSGiLog">PortalLogAssertorTest.testScanOSGiLog</a><pre><code>junit.framework.AssertionFailedError: 
Portal log assert failure, OSGi log found: /opt/dev/projects/github/liferay-portal-7.1.x/bundles/osgi/state/1570825680426.log:
!SESSION 2019-10-11 20:29:45.662 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US

!ENTRY com.liferay.commerce.service 4 0 2019-10-11 20:29:45.662
!MESSAGE bundle com.liferay.commerce.service:5.3.0 (480)[com.liferay.commerce.internal.starter.ArgentinaCommerceRegionsStarter(2369)] : findField: Suitable but non-accessible field _commerceCountryLocalService in class com.liferay.commerce.internal.starter.BaseCommerceRegionsStarter, subclass of component class com.liferay.commerce.internal.starter.ArgentinaCommerceRegionsStarter

!ENTRY com.liferay.commerce.service 4 0 2019-10-11 20:29:45.665
!MESSAGE bundle com.liferay.commerce.service:5.3.0 (480)[com.liferay.commerce.internal.starter.ArgentinaCommerceRegionsStarter(2369)] : findField: Suitable but non-accessible field _commerceRegionLocalService in class com.liferay.commerce.internal.starter.BaseCommerceRegionsStarter, subclass of component class com.liferay.commerce.internal.starter.ArgentinaCommerceRegionsStarter

!ENTRY com.liferay.commerce.service 4 0 2019-10-11 20:29:45.666
!MESSAGE bundle com.liferay.commerce.service:5.3.0 (480)[com.liferay.commerce.internal.starter.ArgentinaCommerceRegionsStarter(2369)] : findField: Sui...</code></pre></div></li><li><div><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/976//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PortalSmoke_Smoke_">LocalFile.PortalSmoke#Smoke</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-17/1570822618263/test-subrepository-acceptance-pullrequest(7.1.x)/144/functional-smoke-tomcat90-mysql57-jdk8/0/0/LocalFile.PortalSmoke_Smoke/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-17/1570822618263/test-subrepository-acceptance-pullrequest(7.1.x)/144/functional-smoke-tomcat90-mysql57-jdk8/0/0/LocalFile.PortalSmoke_Smoke/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-17/1570822618263/test-subrepo [...]

2019-10-11 21:47 UTC, alecsloan commented
ci:test

2019-10-11 21:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/244/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/244/jenkins-report.html">here</a>.</b></p>

2019-10-11 22:18 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 25 minutes 5 seconds 444 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/fea80e793c58f81de5c1152e70775c225b073a5a">fea80e793c58f81de5c1152e70775c225b073a5a</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/175//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/175//testReport">here</a>.</h5></div></html>

2019-10-11 23:01 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test - 10 out of 13 jobs passed in 1 hour 12 minutes 29 seconds 398 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/fea80e793c58f81de5c1152e70775c225b073a5a">fea80e793c58f81de5c1152e70775c225b073a5a</a></p>10 out of 13 jobs PASSED<div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/244/"><strike><strong>test-subrepository-acceptance-pullrequest(7.1.x)</strong></strike></a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/638/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/647/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</strong></strike></a></li></ul></div><details><summary><strong>10 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/646/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/741/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/637/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/702/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/540/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/599/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/639/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/493/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/56/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/175/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/244/jenkins-report.html">here</a>.</h5><hr/><h4>Failures (upstream comparison is not available):</h4><ol><li><div><h5><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/638/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>1 Test Passed.<br/>3 Tests Failed.</p></div><ol><li><div><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/638//consoleText">AXIS_VARIABLE=0,label_exp=!master #638</a><ol><li><div><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/638//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog">PortalLogAssertorTest.testScanXMLLog</a><pre><code>junit.framework.AssertionFailedError: 
bundle com.liferay.commerce.service:5.3.0 (480)[com.liferay.commerce.internal.starter.ArgentinaCommerceRegionsStarter(2369)] : findField: Suitable but non-accessible field _commerceCountryLocalService in class com.liferay.commerce.internal.starter.BaseCommerceRegionsStarter, subclass of component class com.liferay.commerce.internal.starter.ArgentinaCommerceRegionsStarter 
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:172)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:98)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:88)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog(PortalLogAssertorTest.java:86)
</code></pre></div></li><li><div><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/638//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanOSGiLog">PortalLogAssertorTest.testScanOSGiLog</a><pre><code>junit.framework.AssertionFailedError: 
Portal log assert failure, OSGi log found: /opt/dev/projects/github/liferay-portal-7.1.x/bundles/osgi/state/1570834102398.log:
!SESSION 2019-10-11 22:50:05.137 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US

!ENTRY com.liferay.commerce.service 4 0 2019-10-11 22:50:05.138
!MESSAGE bundle com.liferay.commerce.service:5.3.0 (480)[com.liferay.commerce.internal.starter.ArgentinaCommerceRegionsStarter(2369)] : findField: Suitable but non-accessible field _commerceCountryLocalService in class com.liferay.commerce.internal.starter.BaseCommerceRegionsStarter, subclass of component class com.liferay.commerce.internal.starter.ArgentinaCommerceRegionsStarter

!ENTRY com.liferay.commerce.service 4 0 2019-10-11 22:50:05.140
!MESSAGE bundle com.liferay.commerce.service:5.3.0 (480)[com.liferay.commerce.internal.starter.ArgentinaCommerceRegionsStarter(2369)] : findField: Suitable but non-accessible field _commerceRegionLocalService in class com.liferay.commerce.internal.starter.BaseCommerceRegionsStarter, subclass of component class com.liferay.commerce.internal.starter.ArgentinaCommerceRegionsStarter

!ENTRY com.liferay.commerce.service 4 0 2019-10-11 22:50:05.141
!MESSAGE bundle com.liferay.commerce.service:5.3.0 (480)[com.liferay.commerce.internal.starter.ArgentinaCommerceRegionsStarter(2369)] : findField: Sui...</code></pre></div></li><li><div><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/638//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PortalSmoke_Smoke_">LocalFile.PortalSmoke#Smoke</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-11/1570830557807/test-subrepository-acceptance-pullrequest(7.1.x)/244/functional-smoke-tomcat90-mysql57-jdk8/0/0/LocalFile.PortalSmoke_Smoke/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-11/1570830557807/test-subrepository-acceptance-pullrequest(7.1.x)/244/functional-smoke-tomcat90-mysql57-jdk8/0/0/LocalFile.PortalSmoke_Smoke/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-11/1570830557807/test-subrepos [...]

2019-10-14 21:33 UTC, ethanbustad commented
☝️ @alecsloan I think this failure could be from commit https://github.com/liferay/com-liferay-commerce/pull/1513/commits/7d90eae7669df6209477e565a04aa337f62d8f0e, though I'm not sure exactly why it's failing atm

2019-12-02 10:38 UTC, merged