COMMERCE-2261 fix commerce payment engine test
liferay/com-liferay-commerce pull request #1527
Opened 2019-10-15 13:12 UTC by riccardo-alberti

2019-10-15 13:12 UTC, riccardo-alberti commented
ci:test

2019-10-15 13:41 UTC, marco-leo commented
ci:test

2019-10-15 13:41 UTC, marco-leo commented
@riccardo-alberti your CI user is still not configured properly

2019-10-15 13:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/131/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-18.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/131/jenkins-report.html">here</a>.</b></p>

2019-10-15 14:08 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 22 minutes 56 seconds 874 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/7df77193b865d5c31c43100ca61f3e004044f57b">7df77193b865d5c31c43100ca61f3e004044f57b</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [echo] java.lang.Exception: Found 45 formatting issues:
     [echo] 1: There should be an empty line before assigning value to variable '_liferayPortletRequest'. See https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/line_breaks.markdown: ./commerce-checkout-web/src/main/java/com/liferay/commerce/checkout/web/internal/display/context/CheckoutDisplayContext.java 46 (Checkstyle:MissingEmptyLineCheck)
     [echo] 2: There should be an empty line before assigning value to variable '_httpServletRequest'. See https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/line_breaks.markdown: ./commerce-checkout-web/src/main/java/com/liferay/commerce/checkout/web/internal/display/context/OrderConfirmationCheckoutStepDisplayContext.java 47 (Checkstyle:MissingEmptyLineCheck)
     [echo] 3: There should be an empty line before assigning value to variable '_wrapperId'. See https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/line_breaks.markdown: ./commerce-frontend-impl/src/main/java/com/liferay/commerce/frontend/internal/template/soy/renderer/SoyComponentRendererHelper.java 57 (Checkstyle:MissingEmptyLineCheck)
     [echo] 4: There should be an empty line before assigning value to variable '_httpServletRequest'. See https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/line_breaks.markdown: ./commerce-media-impl/src/main/java/com/liferay/commerce/media/internal/display/context/CommerceMediaDefaultImageDisplayContext.java 52 (Checkstyle:MissingEmptyLineCheck)
     [echo] 5: There should be a line break after 'commerceInventoryWarehouse.getCommerceInventoryWarehouseId(),': ./commerce-payment-test/src/testIntegration/java/com/liferay/commerce/payment/engine/test/CommercePaymentEngineTest.java 142 (Checkstyle:LineBreakAfterCommaCheck)
     [echo] 6: There should be a line break after 'commerceInventoryWarehouse.getCommerceInventoryWarehouseId(),': ./commerce-payment-test/src/testIntegration/java/com/liferay/commerce/payment/engine/test/CommercePaymentEngineTest.java 214 (Checkstyle:LineBreakAfterCommaCheck)
     [echo] 7: Parameter '_group' must match pattern '^[a-z][a-zA-Z0-9]*$': ./commerce-payment-test/src/testIntegration/java/com/liferay/commerce/payment/test/util/CommerceTestUtil.java 106 (Checkstyle:ParameterNameCheck)</code></pre></li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/178//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/178//testReport">here</a>.</h5></div></html>

2019-10-15 19:50 UTC, riccardo-alberti commented
ci:test

2019-10-15 19:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/46/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/46/jenkins-report.html">here</a>.</b></p>

2019-10-15 20:10 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 15 minutes 16 seconds 567 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/7df77193b865d5c31c43100ca61f3e004044f57b">7df77193b865d5c31c43100ca61f3e004044f57b</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :x:<pre><code>     [echo] 696 actionable tasks: 578 executed, 118 up-to-date
     [echo] Gradle build finished at 2019-10-15 20:09:58.553.
     [echo] 
     [echo] See the profiling report at: file:///opt/dev/projects/github/liferay-portal-7.1.x/modules/apps/commerce/build/reports/profile/profile-2019-10-15-20-04-35.html
     [echo] A fine-grained performance profile is available: use the --scan option.
     [echo] 
      [for] subrepository-semantic-versioning-jdk8: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:27: Subrepository task FAILED: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-test-batch.xml:5576: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-common.xml:1043: Unable to execute Gradle task: baseline.
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:120: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:13: Keepgoing execution: 1 of 3 iterations failed.
[beanshell] 4914 GitHub API calls out of 5000 remain. GitHub API call limit will reset in 56 minutes 4 seconds 102 ms.
[beanshell]     https://api.github.com/repos/liferay/com-liferay-commerce/pulls/1527
[beanshell] Executing commands: cat /tmp/1894978915.txt | mail -v -s "CI Failure has occurred" -r "ci_failure_notification" "qa-slave-verify-fail@liferay.com"
     [echo] A CI failure has occurred. QA Engineering has been notified. Please try again later or contact QA Engineering for an update.

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:11120: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:127: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:120: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:13: Keepgoing execution: 1 of 3 iterations failed.</code></pre></li><li>central-requirements-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/144//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>7 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/144//testReport">here</a>.</h5></div></html>

2019-10-15 21:06 UTC, marco-leo commented
ci:test

2019-10-15 21:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/143/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/143/jenkins-report.html">here</a>.</b></p>

2019-10-15 21:08 UTC, ethanbustad commented
@riccardo-alberti the failure now is that a version increase is required in `commerce-test-util`, which can be generated with `gw baseline` (keep running this command until it succeeds). You can tell because of the full console:
> For full console, click [here](https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/144//consoleText).

I always check there if the error message isn't clear.

2019-10-15 21:24 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 15 minutes 1 second 770 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/31ae63341a062efc1fb581be3c5e557901e8d0c9">31ae63341a062efc1fb581be3c5e557901e8d0c9</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :x:<pre><code>     [echo] 696 actionable tasks: 578 executed, 118 up-to-date
     [echo] Gradle build finished at 2019-10-15 21:24:23.189.
     [echo] 
     [echo] See the profiling report at: file:///opt/dev/projects/github/liferay-portal-7.1.x/modules/apps/commerce/build/reports/profile/profile-2019-10-15-21-19-08.html
     [echo] A fine-grained performance profile is available: use the --scan option.
     [echo] 
      [for] subrepository-semantic-versioning-jdk8: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:27: Subrepository task FAILED: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-test-batch.xml:5576: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-common.xml:1043: Unable to execute Gradle task: baseline.
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:120: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:13: Keepgoing execution: 1 of 3 iterations failed.
[beanshell] 4451 GitHub API calls out of 5000 remain. GitHub API call limit will reset in 41 minutes 13 seconds 379 ms.
[beanshell]     https://api.github.com/repos/liferay/com-liferay-commerce/pulls/1527
[beanshell] Executing commands: cat /tmp/-1226977918.txt | mail -v -s "CI Failure has occurred" -r "ci_failure_notification" "qa-slave-verify-fail@liferay.com"
     [echo] A CI failure has occurred. QA Engineering has been notified. Please try again later or contact QA Engineering for an update.

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:11120: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:127: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:120: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:13: Keepgoing execution: 1 of 3 iterations failed.</code></pre></li><li>central-requirements-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/114//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>7 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/114//testReport">here</a>.</h5></div></html>

2019-10-15 21:49 UTC, ethanbustad requested changes

2019-10-15 21:49 UTC, ethanbustad commented on commerce-payment-test/src/testIntegration/java/com/liferay/commerce/payment/engine/test/CommercePaymentEngineTest.java
> +	private CommerceChannelRelLocalService _commerceChannelRelServ;
Should be named `CommerceChannelRelLocalService _commerceChannelRelLocalService`, for clarity/consistency.

2019-10-15 21:49 UTC, ethanbustad commented on commerce-test-util/src/main/java/com/liferay/commerce/test/util/TestCommerceContext.java
> -
this empty line is required -- all classes should have an empty line before the closing brace.

2019-10-15 21:49 UTC, ethanbustad commented on commerce-test-util/src/main/java/com/liferay/commerce/test/util/CommerceTestUtil.java
> +
There's some extra whitespace added in a few places in this file.

2019-10-15 21:49 UTC, ethanbustad commented on commerce-test-util/src/main/java/com/liferay/commerce/test/util/CommerceTestUtil.java
> +			commerceOrder);
Put as many parameters on a single line as fit in 80 columns. Source formatter should flag anything like this that doesn't conform to standards. (Same with the other whitespace issues in this PR, I think.) So in general, try to be sure to run `gw formatSource` before sending a PR (and you could follow that with `gw checkSourceFormatting` to make sure you got everything).

2019-10-16 07:05 UTC, riccardo-alberti commented
ci:test

2019-10-16 07:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/23/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-9.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/23/jenkins-report.html">here</a>.</b></p>

2019-10-16 07:33 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 24 minutes 59 seconds 478 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/31ae63341a062efc1fb581be3c5e557901e8d0c9">31ae63341a062efc1fb581be3c5e557901e8d0c9</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [echo] java.lang.Exception: Found 8 formatting issues:
     [echo] 1: There should be a line break after 'commerceOrder.getCommerceCurrency(),': ./commerce-test-util/src/main/java/com/liferay/commerce/test/util/CommerceTestUtil.java 127 (Checkstyle:LineBreakAfterCommaCheck)
     [echo] 2: There should be a line break after 'user,': ./commerce-test-util/src/main/java/com/liferay/commerce/test/util/CommerceTestUtil.java 128 (Checkstyle:LineBreakAfterCommaCheck)
     [echo] 3: There should be a line break after 'group,': ./commerce-test-util/src/main/java/com/liferay/commerce/test/util/CommerceTestUtil.java 129 (Checkstyle:LineBreakAfterCommaCheck)
     [echo] 4: There should be a line break after 'commerceOrder.getCommerceCurrency(),': ./commerce-test-util/src/main/java/com/liferay/commerce/test/util/CommerceTestUtil.java 214 (Checkstyle:LineBreakAfterCommaCheck)
     [echo] 5: There should be a line break after 'null,': ./commerce-test-util/src/main/java/com/liferay/commerce/test/util/CommerceTestUtil.java 215 (Checkstyle:LineBreakAfterCommaCheck)
     [echo] 6: There should be a line break after 'null,': ./commerce-test-util/src/main/java/com/liferay/commerce/test/util/CommerceTestUtil.java 216 (Checkstyle:LineBreakAfterCommaCheck)
     [echo] 7: ./commerce-test-util/src/main/java/com/liferay/commerce/test/util/TestCommerceContext.java expected:&lt;... User _contextUser;
     [echo] [
     [echo] ]}&gt; but was:&lt;... User _contextUser;
     [echo] []}&gt;
     [echo] 8: Truncated message :
     [echo] ./commerce-test-util/src/main/java/com/liferay/commerce/test/util/CommerceTestUtil.java expected:&lt;....test.util;
     [echo] 
     [echo] import [com.liferay.commerce.account.model.CommerceAccount;
     [echo] import com.liferay.commerce.account.service.CommerceAccountLocalServiceUtil;
     [echo] import com.liferay.commerce.context.CommerceContext;
     [echo] import com.liferay.commerce.currency.model.CommerceCurrency;
     [echo] import com.liferay.commerce.currency.test.util.CommerceCurrencyTestUtil;
     [echo] import com.liferay.commerce.inventory.model.CommerceInventoryWarehouse;
     [echo] import com.liferay.commerce.model.CPDefinitionInventory;
     [echo] import com.liferay.commerce.model.CommerceAddress;
     [echo] import com.liferay.commerce.model.CommerceCountry;
     [echo] import com.liferay.commerce.model.CommerceOrder;
     [echo] import com.liferay.commerce.model.CommerceOrderItem;
     [echo] import com.liferay.commerce.model.CommerceRegion;</code></pre></li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/130//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/130//testReport">here</a>.</h5></div></html>

2019-10-28 17:51 UTC, closed without merging