COMMERCE-2262 Minium gallery moved to Clay and React
liferay/com-liferay-commerce pull request #1529
Opened 2019-10-15 14:06 UTC by gcmznt

2019-10-15 14:06 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2019-10-15 19:43 UTC, ethanbustad requested changes

2019-10-15 19:43 UTC, ethanbustad commented on commerce-frontend-js/src/main/resources/META-INF/resources/js/gallery/_gallery.scss
> +  .loading-animation {
selectors should be sorted alphabetically -- I think that would be:

    .gallery-overlay
    .gallery-thumbnails
    .loading-animation
    .main-image
    .next, .prev
    .next
    .prev

2019-10-15 19:43 UTC, ethanbustad commented on commerce-frontend-js/src/main/resources/META-INF/resources/js/gallery/Gallery.es.js
> +    this.closeFullscreen = this.closeFullscreen.bind(this);
these should probably be alphabetized

2019-10-15 19:43 UTC, ethanbustad commented on commerce-frontend-js/dev/public/gallery.html
> +	-->
can you remove this comment? AFAIU, it doesn't add any value here (talked this over with Fabio recently on a similar PR -- feel free to ping me or him if you disagree)

2019-10-16 22:56 UTC, ethanbustad approved these changes
Just one more alphabetizing change to make -- after that, I'll stop complaining :)

2019-10-16 22:56 UTC, ethanbustad commented on commerce-frontend-js/src/main/resources/META-INF/resources/js/gallery/entry.dev.es.js
> +    bigUrl: getImgUrl(img, 1600)
This should probably be sorted higher now.....

2019-10-18 08:34 UTC, gcmznt commented
ci:test

2019-10-18 08:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/184/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-20.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/184/jenkins-report.html">here</a>.</b></p>

2019-10-18 08:58 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 20 minutes 7 seconds 724 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/31ae63341a062efc1fb581be3c5e557901e8d0c9">31ae63341a062efc1fb581be3c5e557901e8d0c9</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [echo] java.lang.Exception: Found 1 formatting issues:
     [echo] 1: ./commerce-frontend-js/dev/public/gallery.html expected:&lt;...me="theme-color" /&gt;
     [echo] [
     [echo] 	&lt;title&gt;Gallery component&lt;/title&gt;
     [echo] 
     [echo] 	&lt;link href="https://cdn.jsdelivr.net/npm/clay/lib/css/atlas.css" rel="stylesheet" /&gt;
     [echo] &lt;/head&gt;
     [echo] ]
     [echo] &lt;body&gt;
     [echo] 	&lt;div class=...&gt; but was:&lt;...me="theme-color" /&gt;
     [echo] [	&lt;title&gt;Gallery component&lt;/title&gt;
     [echo] 	&lt;link href="https://cdn.jsdelivr.net/npm/clay/lib/css/atlas.css" rel="stylesheet" /&gt;
     [echo] &lt;/head&gt;]
     [echo] &lt;body&gt;
     [echo] 	&lt;div class=...&gt;
     [echo] 
     [echo] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:438)
     [echo] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:266)
     [echo] 
     [echo] FAILURE: Build failed with an exception.
     [echo] 
     [echo] * What went wrong:
     [echo] Execution failed for task ':checkSourceFormatting'.
     [echo] &gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [echo] 
     [echo] * Try:
     [echo] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [echo] 
     [echo] * Exception is:
     [echo] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':checkSourceFormatting'.
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
     [echo] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
     [echo] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)</code></pre></li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-1.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/112//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-1.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/112//testReport">here</a>.</h5></div></html>

2019-10-18 09:10 UTC, gcmznt commented
ci:test

2019-10-18 09:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/134/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-18.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/134/jenkins-report.html">here</a>.</b></p>

2019-10-18 09:39 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 26 minutes 36 seconds 247 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/31ae63341a062efc1fb581be3c5e557901e8d0c9">31ae63341a062efc1fb581be3c5e557901e8d0c9</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [echo] java.lang.Exception: Found 1 formatting issues:
     [echo] 1: ./commerce-frontend-js/dev/public/gallery.html expected:&lt;...me="theme-color" /&gt;
     [echo] [
     [echo] 	&lt;title&gt;Gallery component&lt;/title&gt;
     [echo] 
     [echo] 	&lt;link href="https://cdn.jsdelivr.net/npm/clay/lib/css/atlas.css" rel="stylesheet" /&gt;
     [echo] &lt;/head&gt;
     [echo] ]
     [echo] &lt;body&gt;
     [echo] 	&lt;div class=...&gt; but was:&lt;...me="theme-color" /&gt;
     [echo] [	&lt;title&gt;Gallery component&lt;/title&gt;
     [echo] 	&lt;link href="https://cdn.jsdelivr.net/npm/clay/lib/css/atlas.css" rel="stylesheet" /&gt;
     [echo] &lt;/head&gt;]
     [echo] &lt;body&gt;
     [echo] 	&lt;div class=...&gt;
     [echo] 
     [echo] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:438)
     [echo] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:266)
     [echo] 
     [echo] FAILURE: Build failed with an exception.
     [echo] 
     [echo] * What went wrong:
     [echo] Execution failed for task ':checkSourceFormatting'.
     [echo] &gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [echo] 
     [echo] * Try:
     [echo] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [echo] 
     [echo] * Exception is:
     [echo] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':checkSourceFormatting'.
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
     [echo] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
     [echo] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)</code></pre></li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/149//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/149//testReport">here</a>.</h5></div></html>

2019-10-18 15:16 UTC, gcmznt commented
ci:test

2019-10-18 15:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/189/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-5.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/189/jenkins-report.html">here</a>.</b></p>

2019-10-18 15:43 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 20 minutes 49 seconds 825 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/31ae63341a062efc1fb581be3c5e557901e8d0c9">31ae63341a062efc1fb581be3c5e557901e8d0c9</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [echo] java.lang.Exception: Found 1 formatting issues:
     [echo] 1: ./commerce-frontend-js/dev/public/gallery.html expected:&lt;...lesheet" /&gt;
     [echo] &lt;/head&gt;
     [echo] [
     [echo] ]&lt;body&gt;
     [echo] 	&lt;div class="...&gt; but was:&lt;...lesheet" /&gt;
     [echo] &lt;/head&gt;
     [echo] []&lt;body&gt;
     [echo] 	&lt;div class="...&gt;
     [echo] 
     [echo] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:438)
     [echo] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:266)
     [echo] 
     [echo] FAILURE: Build failed with an exception.
     [echo] 
     [echo] * What went wrong:
     [echo] Execution failed for task ':checkSourceFormatting'.
     [echo] &gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [echo] 
     [echo] * Try:
     [echo] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [echo] 
     [echo] * Exception is:
     [echo] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':checkSourceFormatting'.
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
     [echo] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
     [echo] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
     [echo] 	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
     [echo] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)</code></pre></li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/231//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/231//testReport">here</a>.</h5></div></html>

2019-10-18 15:53 UTC, gcmznt commented
ci:test

2019-10-18 15:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/186/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-20.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/186/jenkins-report.html">here</a>.</b></p>

2019-10-18 16:20 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 23 minutes 36 seconds 292 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/31ae63341a062efc1fb581be3c5e557901e8d0c9">31ae63341a062efc1fb581be3c5e557901e8d0c9</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [echo] * What went wrong:
     [echo] Execution failed for task ':apps:commerce:commerce-frontend-js:packageRunCheckFormat'.
     [echo] &gt; java.io.IOException: Process '[/opt/dev/projects/github/liferay-portal-7.1.x/modules/apps/commerce/build/node/bin/node, /opt/dev/projects/github/liferay-portal-7.1.x/modules/apps/commerce/build/node/lib/node_modules/npm/bin/npm-cli.js, --production, false, --registry, http://mirrors.lax.liferay.com:4873, --loglevel, warn, --progress, true, run-script, checkFormat]' finished with non-zero exit value 1
     [echo] 
     [echo] * Try:
     [echo] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [echo] 
     [echo] * Exception is:
     [echo] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:commerce:commerce-frontend-js:packageRunCheckFormat'.
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
     [echo] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
     [echo] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
     [echo] 	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
     [echo] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)</code></pre></li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/204//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/204//testReport">here</a>.</h5></div></html>

2019-10-18 17:23 UTC, gcmznt commented
@marco-leo I cannot understand why this build fails. What can I do to make it pass?

2019-10-18 17:49 UTC, ethanbustad commented
Sorry, @gcmznt , this PR does not look like a fun time :(. Looking at the `For full console, click here.` link, I think this is the relevant error message:

     /opt/dev/projects/github/liferay-portal-7.1.x/modules/apps/commerce/commerce-frontend-js/src/main/resources/META-INF/resources/js/gallery/Gallery.es.js
     142:4  error  Expected object keys to be in natural ascending order. 'thumbnailUrl' should be before 'title'     sort-keys
     143:4  error  Expected object keys to be in natural ascending order. 'smallUrl' should be before 'thumbnailUrl'  sort-keys

     /opt/dev/projects/github/liferay-portal-7.1.x/modules/apps/commerce/commerce-frontend-js/src/main/resources/META-INF/resources/js/gallery/MainImage.js
     37:2  error  Expected object keys to be in natural ascending order. 'src' should be before 'title'  sort-keys

     /opt/dev/projects/github/liferay-portal-7.1.x/modules/apps/commerce/commerce-frontend-js/src/main/resources/META-INF/resources/js/gallery/Thumbnail.js
     36:2  error  Expected object keys to be in natural ascending order. 'src' should be before 'title'  sort-keys

     /opt/dev/projects/github/liferay-portal-7.1.x/modules/apps/commerce/commerce-frontend-js/src/main/resources/META-INF/resources/js/gallery/Thumbnails.js
     32:4  error  Expected object keys to be in natural ascending order. 'thumbnailUrl' should be before 'title'  sort-keys

     /opt/dev/projects/github/liferay-portal-7.1.x/modules/apps/commerce/commerce-frontend-js/src/main/resources/META-INF/resources/js/gallery/entry.dev.es.js
     19:3  error  Expected object keys to be in natural ascending order. 'thumbnailUrl' should be before 'title'     sort-keys
     20:3  error  Expected object keys to be in natural ascending order. 'smallUrl' should be before 'thumbnailUrl'  sort-keys

2019-10-18 19:27 UTC, gcmznt commented
ci:test

Thanks @ethanbustad

2019-10-18 19:28 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/197/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-23.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/197/jenkins-report.html">here</a>.</b></p>

2019-10-18 19:53 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 22 minutes 55 seconds 566 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/31ae63341a062efc1fb581be3c5e557901e8d0c9">31ae63341a062efc1fb581be3c5e557901e8d0c9</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/122//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/122//testReport">here</a>.</h5></div></html>

2019-10-18 20:37 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test - 13 out of 13 jobs passed in 1 hour 10 minutes 11 seconds 579 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/31ae63341a062efc1fb581be3c5e557901e8d0c9">31ae63341a062efc1fb581be3c5e557901e8d0c9</a></p>13 out of 13 jobs PASSED<details><summary><strong>13 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/197/">test-subrepository-acceptance-pullrequest(7.1.x)</a></li><li><a href="https://test-1-6.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/612/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/661/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/390/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/521/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/518/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/657/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/658/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-19.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/662/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/719/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/720/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></li><li><a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/82/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/122/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-23.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/197/jenkins-report.html">here</a>.</h5></details></html>

2019-10-19 16:27 UTC, marco-leo commented
@FabioDiegoMastrorilli @gcmznt How does the css loading works?  who will load that css in the page?

2019-10-19 17:16 UTC, merged