COMMERCE-619
liferay/com-liferay-commerce pull request #155
Opened 2018-09-24 16:01 UTC by marco-leo

https://issues.liferay.com/browse/COMMERCE-619

As a catalog manager I want to enable subscription on a Product

//cc @Commando18 @luca-pellizzon

2018-09-24 16:01 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2018-09-24 16:10 UTC, marco-leo commented
ci:test

2018-09-24 16:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-1.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/19/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-1.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/19/jenkins-report.html">here</a>.</b></p>

2018-09-24 16:30 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 11 minutes 40 seconds 710 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/0052274b6b10abd596376751918abb37ad5df1a9">0052274b6b10abd596376751918abb37ad5df1a9</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :white_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :x:<pre><code>     [echo] :apps:commerce:commerce-product-definitions-web:transpileJSRunning 'build'...
     [echo] Compiling soy
     [echo] Finished compiling soy
     [echo] Building to format: amd
     [echo] Finished building to format: amd
     [echo] Finished 'build'...
     [echo] 
     [echo] :apps:commerce:commerce-product-definitions-web:downloadLiferayModuleConfigGenerator SKIPPED
     [echo] :apps:commerce:commerce-product-definitions-web:configJSModules
     [echo] :apps:commerce:commerce-product-definitions-web:copyLibs SKIPPED
     [echo] :apps:commerce:commerce-product-definitions-web:mergeLang
     [echo] :apps:commerce:commerce-product-definitions-web:replaceSoyTranslation
     [echo] :apps:commerce:commerce-product-definitions-web:wrapSoyAlloyTemplate SKIPPED
     [echo] :apps:commerce:commerce-product-definitions-web:classes
     [echo] :apps:commerce:commerce-product-definitions-web:jar
     [echo] :apps:commerce:commerce-product-definitions-web:baseline
     [echo] [Baseline Report] Mode: diff (persisted)
     [echo] [Baseline Warning] Bundle Version Change Recommended: 1.1.0
     [echo]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [echo] = ================================================== ========== ========== ========== ========== ==========
     [echo] * com.liferay.commerce.product.definitions.web.servlet.taglib.ui MINOR      1.0.0      1.0.0      1.1.0      VERSION INCREASE REQUIRED
     [echo] 	&amp;lt;   class      com.liferay.commerce.product.definitions.web.servlet.taglib.ui.CPDefinitionScreenNavigationConstants
     [echo] 		+   field      ENTRY_KEY_SUBSCRIPTION
     [echo] 			+   access     final
     [echo] 			+   access     static
     [echo] 			+   constant   subscription
     [echo] 			+   return     java.lang.String
     [echo] 	&amp;lt;   class      com.liferay.commerce.product.definitions.web.servlet.taglib.ui.CPInstanceScreenNavigationConstants
     [echo] 		+   field      ENTRY_KEY_SUBSCRIPTION_OVERRIDE
     [echo] 			+   access     final
     [echo] 			+   access     static
     [echo] 			+   constant   subscription-override
     [echo] 			+   return     java.lang.String
     [echo] :apps:commerce:commerce-product-definitions-web:baseline FAILED
     [echo] :apps:commerce:commerce-product-definitions-web:syncVersions
     [echo] Updated package-lock.json
     [echo] Updated package.json
     [echo] 
     [echo] BUILD FAILED
     [echo] 
     [echo] </code></pre></li></ul><h5>For full console, click <a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/9//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><h5>No tests were run.</h5></div></html>

2018-09-24 21:45 UTC, marco-leo commented
ci:test

2018-09-24 23:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/22/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/22/jenkins-report.html">here</a>.</b></p>

2018-09-24 23:55 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 17 minutes 59 seconds 821 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/0052274b6b10abd596376751918abb37ad5df1a9">0052274b6b10abd596376751918abb37ad5df1a9</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :white_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :white_check_mark:</li><li>subrepository-pmd-jdk8 -  :white_check_mark:</li><li>subrepository-source-format-jdk8 -  :white_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/16//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>3 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/16//testReport">here</a>.</h5></div></html>

2018-09-25 00:48 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test - 2 out of 3 jobs passed in 1 hour 16 minutes 11 seconds 372 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/0052274b6b10abd596376751918abb37ad5df1a9">0052274b6b10abd596376751918abb37ad5df1a9</a></p>2 out of 3 jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-6.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/22/"><strike><strong>test-subrepository-acceptance-pullrequest(7.1.x)</strong></strike></a></li></ul></div><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-1.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/5/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/16/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/22/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-6.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/22/">test-subrepository-acceptance-pullrequest(7.1.x)</a></h5><div><h6>Job Results:</h6><p>2 Jobs Passed.<br/>1 Job Failed.</p></div><div><p>POSHI Test Failure: <strong>Execution failed for task ':writePoshiProperties'.</strong></p><pre><code>     [exec] Exception in thread "main" java.lang.Exception
     [exec] 	at com.liferay.poshi.runner.PoshiRunnerValidation._throwExceptions(PoshiRunnerValidation.java:1767)
     [exec] 	at com.liferay.poshi.runner.PoshiRunnerValidation.validate(PoshiRunnerValidation.java:98)
     [exec] 	at com.liferay.poshi.runner.PoshiRunnerContext.main(PoshiRunnerContext.java:280)
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':writePoshiProperties'.
     [exec] &amp;gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [exec] </code></pre></div></div></li></ol></details></html>

2018-09-25 21:13 UTC, ethanbustad requested changes
Other than that one language property, looks really great!

2018-09-25 21:13 UTC, ethanbustad commented on commerce-lang/src/main/resources/content/Language.properties
> +max-subscription-cycles-number=Max Subscriptions Cycles
Should be `Max Subscription Cycles` rather than `Max Subscriptions Cycles`.

2018-10-10 13:10 UTC, closed without merging