Commerce 2256
liferay/com-liferay-commerce pull request #1562
Opened 2019-10-22 12:29 UTC by andrea-ale-sbarra

2019-10-22 12:29 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2019-10-22 12:29 UTC, andrea-ale-sbarra commented
ci:test

2019-10-22 12:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/175/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/175/jenkins-report.html">here</a>.</b></p>

2019-10-22 12:57 UTC, andrea-ale-sbarra commented
Hi @marco-leo , this PR applies the changes requested by @ethanbustad as well. Again please let me know about the commit messages.. Also I didn't made the change that manages the duplicated records for the tuples identified by "commerceInventoryWarehouseId"  and "sku"

2019-10-22 12:57 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 23 minutes 7 seconds 384 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/596d2aaca6fc6badbbdd759665120559fb1feedb">596d2aaca6fc6badbbdd759665120559fb1feedb</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/184//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/184//testReport">here</a>.</h5></div></html>

2019-10-22 13:45 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test - 11 out of 13 jobs passed in 1 hour 13 minutes 30 seconds 963 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/596d2aaca6fc6badbbdd759665120559fb1feedb">596d2aaca6fc6badbbdd759665120559fb1feedb</a></p>11 out of 13 jobs PASSED<div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/175/"><strike><strong>test-subrepository-acceptance-pullrequest(7.1.x)</strong></strike></a></li><li><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/539/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</strong></strike></a></li></ul></div><details><summary><strong>11 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/734/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/733/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/538/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/731/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/732/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/736/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/737/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/735/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/540/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></li><li><a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/95/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/184/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/175/jenkins-report.html">here</a>.</h5><hr/><h4>Failures (upstream comparison is not available):</h4><ol><li><div><h5><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/539/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</a></h5><div><h6>Job Results:</h6><p>1 Test Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/539//consoleText">AXIS_VARIABLE=0,label_exp=!master #539</a><ol><li><div><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/539//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CommerceFrontStore_ViewStoreFrontSimpleProduct_">LocalFile.CommerceFrontStore#ViewStoreFrontSimpleProduct</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-3/1571747555466/test-subrepository-acceptance-pullrequest(7.1.x)/175/subrepository-functional-tomcat90-mysql57-jdk8/6/0/LocalFile.CommerceFrontStore_ViewStoreFrontSimpleProduct/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-3/1571747555466/test-subrepository-acceptance-pullrequest(7.1.x)/175/subrepository-functional-tomcat90-mysql57-jdk8/6/0/LocalFile.CommerceFrontStore_ViewStoreFrontSimpleProduct/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-3/1571747555466/test-subrepository-acceptance-pullrequest(7.1.x)/175/subrepository-functional-tomcat90-mysql57-jdk8/6/0/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li></ol></details></html>

2019-10-22 17:59 UTC, ethanbustad requested changes

2019-10-22 17:59 UTC, ethanbustad commented on commerce-inventory-service/src/main/java/com/liferay/commerce/inventory/service/impl/CommerceInventoryWarehouseItemLocalServiceImpl.java
> +					"Sku code already associated to this Warehouse");
should be `"...associated with..."`, not `"...associated to..."`

2019-10-23 13:10 UTC, andrea-ale-sbarra commented
ci:test

2019-10-23 13:11 UTC, andrea-ale-sbarra commented
Hi @ethanbustad , I've just fixed the typo you told me. BTW Thank you!

2019-10-23 13:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/150/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/150/jenkins-report.html">here</a>.</b></p>

2019-10-23 13:39 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 24 minutes 26 seconds 461 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/7823f4eee3fe92e16fff8ea5782a97df1d3f9994">7823f4eee3fe92e16fff8ea5782a97df1d3f9994</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/185//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/185//testReport">here</a>.</h5></div></html>

2019-10-23 13:55 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test - 1 out of 3 jobs passed in 43 minutes 55 seconds 620 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/7823f4eee3fe92e16fff8ea5782a97df1d3f9994">7823f4eee3fe92e16fff8ea5782a97df1d3f9994</a></p>1 out of 3 jobs PASSED<div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-6.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/150/"><strike><strong>test-subrepository-acceptance-pullrequest(7.1.x)</strong></strike></a></li><li><a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/83/"><strike><strong>test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</strong></strike></a></li></ul></div><details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/185/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/150/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/83/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/AXIS_VARIABLE=tomcat,label_exp=!master/83//consoleText">AXIS_VARIABLE=tomcat,label_exp=!master #83</a><pre><code>     [exec] &gt; Task :apps:commerce:commerce-shipping-engine-fedex:compileJava FAILED
     [exec] 5593 actionable tasks: 829 executed, 4764 up-to-date
     [exec] Gradle build finished at 2019-10-23 13:54:48.531.
     [exec] 
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-test-subrepository-acceptance-pullrequest-dist.xml:321: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:657: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:5003: exec returned: 1

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:11097: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-test-subrepository-acceptance-pullrequest-dist.xml:321: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:657: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:5003: exec returned: 1

Total time: 14 minutes 35 seconds
Build step 'Execute shell' marked build as failure
Recording test results
[PostBuildScript] - Executing post build scripts.
define: [LabelParameterValue: NODE_NAME=cloud-10-0-110-25]
Triggering projects: verification-node
[liferay-jenkins-ee] \$ /bin/bash -e -x /tmp/jenkins4381410424428189704.sh
+ echo 'Update the workspace repository for post-build steps.'
Update the workspace repository for post-build steps.
+ git clean -d -f -x
Removing .ssh/
Removing git/
Removing liferay/
Removing reset.repository.log
Removing start.properties
Removing test-results/
+ git reset --hard
HEAD is now at 699e16c LRCI-694 Remove test-1-11, test-1-12, test-1-13, test-1-18, test-1-20 from blacklist
+ set +e
+ git show-ref --verify --quiet refs/heads/master-temp-1571837998141
+ VERIFY_BRANCH_RESULT=0
+ set -e
+ [[ 0 == 0 ]]
+ git checkout master-temp-1571837998141
Already on 'master-temp-1571837998141'
+ git log -n 1
commit 699e16c022f683320cacf6c232235a6b86162f09
Author: pyoo47 &lt;peter.yoo@liferay.com&gt;
Date:   Tue Oct 22 12:14:35 2019 -0700

    LRCI-694 Remove test-1-11, test-1-12, test-1-13, test-1-18, test-1-20 from blacklist
+ echo 'Exit shell.'
Exit shell.</code></pre></div></li></ol></div></li></ol></details></html>

2019-10-25 18:25 UTC, ethanbustad commented
ci:test
tests should be fixed in upstream now

2019-10-25 18:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/208/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-5.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/208/jenkins-report.html">here</a>.</b></p>

2019-10-25 18:53 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 24 minutes 57 seconds 333 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/fcdbb7a76849c112f5888f4e0b9f71d1beae6a95">fcdbb7a76849c112f5888f4e0b9f71d1beae6a95</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/117//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/117//testReport">here</a>.</h5></div></html>

2019-10-25 19:42 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:default - 13 out of 13 jobs passed in 1 hour 16 minutes 30 seconds 485 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/fcdbb7a76849c112f5888f4e0b9f71d1beae6a95">fcdbb7a76849c112f5888f4e0b9f71d1beae6a95</a></p><details><summary><strong>ci:test:default - 13 out of 13 jobs PASSED</strong></summary><details><summary><strong>13 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/208/">test-subrepository-acceptance-pullrequest(7.1.x)</a></li><li><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/562/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/554/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/593/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/794/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/1043/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/795/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-1.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/555/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/742/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/854/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/555/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/97/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/117/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details></details><h5>For more details click <a href="https://test-1-5.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/208/jenkins-report.html">here</a>.</h5></details></html>

2019-11-05 19:49 UTC, ethanbustad approved these changes

2019-11-06 23:31 UTC, merged