Commerce 2036 Catalog enpoints now support Filter and Sort
liferay/com-liferay-commerce pull request #1593
Opened 2019-10-25 14:51 UTC by andrea-ale-sbarra

2019-10-25 14:51 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2019-10-25 14:51 UTC, andrea-ale-sbarra commented
ci:test

2019-10-25 14:52 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/300/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-22.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/300/jenkins-report.html">here</a>.</b></p>

2019-10-25 15:19 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 24 minutes 36 seconds 670 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/7823f4eee3fe92e16fff8ea5782a97df1d3f9994">7823f4eee3fe92e16fff8ea5782a97df1d3f9994</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/241//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/241//testReport">here</a>.</h5></div></html>

2019-10-25 16:07 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test - 11 out of 13 jobs passed in 1 hour 14 minutes 58 seconds 896 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/7823f4eee3fe92e16fff8ea5782a97df1d3f9994">7823f4eee3fe92e16fff8ea5782a97df1d3f9994</a></p>11 out of 13 jobs PASSED<div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/300/"><strike><strong>test-subrepository-acceptance-pullrequest(7.1.x)</strong></strike></a></li><li><a href="https://test-1-6.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/620/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</strong></strike></a></li></ul></div><details><summary><strong>11 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/673/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/676/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/622/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/675/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/672/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-6.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/621/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/740/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/677/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/674/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></li><li><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/82/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/241/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-22.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/300/jenkins-report.html">here</a>.</h5><hr/><h4>Failures (upstream comparison is not available):</h4><ol><li><div><h5><a href="https://test-1-6.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/620/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</a></h5><div><h6>Job Results:</h6><p>1 Test Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-6.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/620//consoleText">AXIS_VARIABLE=0,label_exp=!master #620</a><ol><li><div><a href="https://test-1-6.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/620//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CommerceFrontStore_ViewStoreFrontSimpleProduct_">LocalFile.CommerceFrontStore#ViewStoreFrontSimpleProduct</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-22/1572015163599/test-subrepository-acceptance-pullrequest(7.1.x)/300/subrepository-functional-tomcat90-mysql57-jdk8/6/0/LocalFile.CommerceFrontStore_ViewStoreFrontSimpleProduct/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-22/1572015163599/test-subrepository-acceptance-pullrequest(7.1.x)/300/subrepository-functional-tomcat90-mysql57-jdk8/6/0/LocalFile.CommerceFrontStore_ViewStoreFrontSimpleProduct/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-22/1572015163599/test-subrepository-acceptance-pullrequest(7.1.x)/300/subrepository-functional-tomcat90-mysql57-jdk8/6/0/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li></ol></details></html>

2019-10-25 18:10 UTC, ethanbustad commented
ci:test
tests should be fixed in upstream now

2019-10-25 18:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-1.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/104/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-1.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/104/jenkins-report.html">here</a>.</b></p>

2019-10-25 18:42 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 27 minutes 41 seconds 990 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/fcdbb7a76849c112f5888f4e0b9f71d1beae6a95">fcdbb7a76849c112f5888f4e0b9f71d1beae6a95</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/114//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/114//testReport">here</a>.</h5></div></html>

2019-10-25 19:26 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test - 13 out of 13 jobs passed in 1 hour 16 minutes 738 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/fcdbb7a76849c112f5888f4e0b9f71d1beae6a95">fcdbb7a76849c112f5888f4e0b9f71d1beae6a95</a></p>13 out of 13 jobs PASSED<details><summary><strong>13 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-1.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/104/">test-subrepository-acceptance-pullrequest(7.1.x)</a></li><li><a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/397/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/679/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/588/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/931/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/849/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/804/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/850/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/559/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/747/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/560/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></li><li><a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/98/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/114/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/104/jenkins-report.html">here</a>.</h5></details></html>

2019-10-25 21:08 UTC, ethanbustad requested changes

2019-10-25 21:08 UTC, ethanbustad commented on headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/odata/entity/v1_0/SpecificationEntityModel.java
> +				locale -> "title_".concat(LocaleUtil.toLanguageId(locale)))
Should probably use `LocalizationUtil.getLocalizedName` for this

2019-10-28 09:21 UTC, andrea-ale-sbarra commented
ci.test

2019-10-28 10:13 UTC, andrea-ale-sbarra commented
Hi @ethanbustad , I've applied your change request, but after that I have this error message in the logs:
`2019-10-28 10:09:30.792 ERROR [fileinstall-/Users/andrea/Documents/work/src/bundles/osgi/modules][LogService:93] Error while starting bundle: file:/Users/andrea/Documents/work/src/bundles/osgi/modules/com.liferay.headless.commerce.admin.catalog.impl.jar
org.osgi.framework.BundleException: Could not resolve module: com.liferay.headless.commerce.admin.catalog.impl [932]_  Unresolved requirement: Import-Package: com.liferay.headless.commerce.admin.catalog.resource.v1_0; version="[3.0.0,4.0.0)"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1263)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1236)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1225)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:515)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316)
2019-10-28 10:09:30.793 INFO  [fileinstall-/Users/andrea/Documents/work/src/bundles/osgi/modules][BundleStartStopLogger:39] STARTED com.liferay.headless.commerce.admin.catalog.api_5.0.0 [933]
2019-10-28 10:10:21.366 INFO  [fileinstall-/Users/andrea/Documents/work/src/bundles/osgi/modules][BundleStartStopLogger:39] STARTED com.liferay.headless.commerce.admin.catalog.impl_1.0.12 [934]
`
and I can't figure it out what is the cause. Any ideas? Anyway the change seems to be working though.

Thanks!

2019-10-28 20:17 UTC, ethanbustad commented
@andrea-ale-sbarra from the error message, it actually looks like it's not a problem to me. It looks like what happened was:

1) `com.liferay.headless.commerce.admin.catalog.impl` deployed, but `com.liferay.headless.commerce.admin.catalog.api` hadn't been deployed yet, so the Impl module failed to register
2) `com.liferay.headless.commerce.admin.catalog.api` deployed and registered
3) `com.liferay.headless.commerce.admin.catalog.impl` registered now that the API module was registered

So I think everything is ok. Let me know if you still have unresolved questions on this.

2019-10-31 09:53 UTC, andrea-ale-sbarra commented
ci:test

2019-10-31 09:54 UTC, andrea-ale-sbarra commented
this PR now solves also COMMERCE-2215

2019-10-31 10:20 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 21 minutes 11 seconds 762 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/f8b4ae86eb3da22d26e26c3d1c6c00738b6760a1">f8b4ae86eb3da22d26e26c3d1c6c00738b6760a1</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/55//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/55//testReport">here</a>.</h5></div></html>

2019-10-31 11:41 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:default - 3 out of 13 jobs passed in 1 hour 46 minutes 22 seconds 470 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/f8b4ae86eb3da22d26e26c3d1c6c00738b6760a1">f8b4ae86eb3da22d26e26c3d1c6c00738b6760a1</a></p><details><summary><strong>ci:test:default - 3 out of 13 jobs PASSED</strong></summary><div><h4>10 Failed Jobs:</h4><ul><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/252/"><strike><strong>test-subrepository-acceptance-pullrequest(7.1.x)</strong></strike></a></li><li><a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/417/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/873/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/773/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/786/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</strong></strike></a></li><li><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/1088/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</strong></strike></a></li><li><a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/787/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</strong></strike></a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/880/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</strong></strike></a></li><li><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/587/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</strong></strike></a></li><li><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/774/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</strong></strike></a></li></ul></div><details><summary><strong>3 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/1087/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/99/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/55/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details></details><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/252/jenkins-report.html">here</a>.</h5><hr/><h4>Failures (upstream comparison is not available):</h4><ol><li><div><h5><a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/417/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/417//consoleText">AXIS_VARIABLE=0,label_exp=!master #417</a><div><p>Startup error: <strong>Unresolved Requirement(s)</strong></p><pre><code>     [exec] 	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:425)
     [exec] 	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1577)
     [exec] 	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
     [exec] 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
     [exec] 	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:424)
     [exec] 	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:367)
     [exec] 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:929)
     [exec] 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:831)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     [exec] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1377)
     [exec] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1367)
     [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
     [exec] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
     [exec] 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:902)
     [exec] 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     [exec] 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:423)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     [exec] 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:928)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     [exec] 	at org.apache.catalina.startup.Catalina.start(Catalina.java:634)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:350)
     [exec] 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)</code></pre></div></div></li></ol></div></li><li><div><h5><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/873/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/873//consoleText">AXIS_VARIABLE=0,label_exp=!master #873</a><div><p>Startup error: <strong>Unresolved Requirement(s)</strong></p><pre><code>     [exec] 	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:425)
     [exec] 	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1577)
     [exec] 	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
     [exec] 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
      [...]

2019-11-01 03:05 UTC, ethanbustad commented
ci:test

2019-11-01 03:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/130/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/130/jenkins-report.html">here</a>.</b></p>

2019-11-01 03:33 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 24 minutes 6 seconds 498 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/03a66d693f8eeab135933e18aa1126a40c2be4a5">03a66d693f8eeab135933e18aa1126a40c2be4a5</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-19.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/144//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-19.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/144//testReport">here</a>.</h5></div></html>

2019-11-01 04:31 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:default - 11 out of 13 jobs passed in 1 hour 25 minutes 1 second 186 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/03a66d693f8eeab135933e18aa1126a40c2be4a5">03a66d693f8eeab135933e18aa1126a40c2be4a5</a></p><details><summary><strong>ci:test:default - 11 out of 13 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/130/"><strike><strong>test-subrepository-acceptance-pullrequest(7.1.x)</strong></strike></a></li><li><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/1000/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</strong></strike></a></li></ul></div><details><summary><strong>11 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/720/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-15.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/388/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-15.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/389/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-15.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/387/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/719/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/830/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/596/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/776/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/721/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></li><li><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/114/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-19.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/144/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details></details><h5>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/130/jenkins-report.html">here</a>.</h5><hr/><h4>Failures (upstream comparison is not available):</h4><ol><li><div><h5><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/1000/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</a></h5><div><h6>Job Results:</h6><p>1 Test Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/1000//consoleText">AXIS_VARIABLE=0,label_exp=!master #1000</a><ol><li><div><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/1000//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CommerceFrontStore_ViewStoreFrontSimpleProduct_">LocalFile.CommerceFrontStore#ViewStoreFrontSimpleProduct</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-7/1572577612217/test-subrepository-acceptance-pullrequest(7.1.x)/130/subrepository-functional-tomcat90-mysql57-jdk8/6/0/LocalFile.CommerceFrontStore_ViewStoreFrontSimpleProduct/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-7/1572577612217/test-subrepository-acceptance-pullrequest(7.1.x)/130/subrepository-functional-tomcat90-mysql57-jdk8/6/0/LocalFile.CommerceFrontStore_ViewStoreFrontSimpleProduct/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-7/1572577612217/test-subrepository-acceptance-pullrequest(7.1.x)/130/subrepository-functional-tomcat90-mysql57-jdk8/6/0/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li></ol></details></html>

2019-11-05 19:54 UTC, ethanbustad approved these changes

2019-11-12 22:13 UTC, merged