COMMERCE-2261 fixed order pricelist subscription shipment test classes and related utilities
liferay/com-liferay-commerce pull request #1595
Opened 2019-10-25 15:51 UTC by riccardo-alberti

To be merged after #1589

2019-10-25 15:51 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2019-10-25 15:52 UTC, riccardo-alberti commented
ci:test

2019-10-25 15:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/190/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-20.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/190/jenkins-report.html">here</a>.</b></p>

2019-10-25 16:18 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 23 minutes 2 seconds 100 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/7823f4eee3fe92e16fff8ea5782a97df1d3f9994">7823f4eee3fe92e16fff8ea5782a97df1d3f9994</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :x:<pre><code>     [echo] &gt; Task :apps:commerce:commerce-shipping-engine-fixed-service:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-shipping-engine-fixed-test:pmdTestIntegration
     [echo] &gt; Task :apps:commerce:commerce-shipping-engine-fixed-web:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-shipping-origin-locator:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-shipping-origin-locator-api:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-shipping-web:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-subscription-web:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-taglib:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-tax-api:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-tax-engine-fixed-api:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-tax-engine-fixed-service:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-tax-engine-fixed-test:pmdTestIntegration
     [echo] &gt; Task :apps:commerce:commerce-tax-engine-fixed-web:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-tax-service:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-tax-test:pmdTestIntegration
     [echo] &gt; Task :apps:commerce:commerce-tax-web:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-test:pmdTestIntegration FAILED
     [echo] 18 actionable tasks: 18 executed
     [echo] Gradle build finished at 2019-10-25 16:15:13.050.
     [echo] 
     [echo] See the profiling report at: file:///opt/dev/projects/github/liferay-portal-7.1.x/modules/apps/commerce/build/reports/profile/profile-2019-10-25-16-14-54.html
     [echo] A fine-grained performance profile is available: use the --scan option.
     [echo] 
      [for] subrepository-pmd-jdk8: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:27: Subrepository task FAILED: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-test-batch.xml:5587: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-common.xml:1046: Unable to execute Gradle task: pmdMain.
     [echo] </code></pre></li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [echo] java.lang.Exception: Found 5 formatting issues:
     [echo] 1: Reference to method 'addWarehouseCommerceChannelRel' does not need 'CommerceTestUtil.': ./commerce-test-util/src/main/java/com/liferay/commerce/test/util/CommerceTestUtil.java 254 (Checkstyle:SelfReferenceCheck)
     [echo] 2: Add the string 'from ' to the previous literal string: ./commerce-test/src/testIntegration/java/com/liferay/commerce/internal/util/test/CommerceShippingHelperTest.java 91 (Checkstyle:PlusStatementCheck)
     [echo] 3: Add the string 'from ' to the previous literal string: ./commerce-test/src/testIntegration/java/com/liferay/commerce/internal/util/test/CommerceShippingHelperTest.java 156 (Checkstyle:PlusStatementCheck)
     [echo] 4: Variable 'commerceCatalog' is unused: ./commerce-test/src/testIntegration/java/com/liferay/commerce/price/list/test/util/CommercePriceListTestUtil.java 62 (Checkstyle:UnusedVariableCheck)
     [echo] 5: ./commerce-test/src/testIntegration/java/com/liferay/commerce/discount/test/CommerceOrderDiscountTest.java expected:&lt;... discount on the " +[
     [echo] 				"total price"
     [echo] 		).when(
     [echo] 			"I try to get the final price of the order"
     [echo] 		).then(
     [echo] 			"The final price will be calculated taking into consideration " +
     [echo] 				"the discounts"
     [echo] 		);
     [echo] 
     [echo] 		CommerceCurrency commerceCurrency =
     [echo] 			CommerceCurrencyTestUtil.addCommerceCurrency();
     [echo] 
     [echo] 		CommerceChannel commerceChannel = CommerceTestUtil.addCommerceChannel(
     [echo] 			commerceCurrency.getCode());
     [echo] 
     [echo] 		CommerceOrder commerceOrder = CommerceTestUtil.addB2CCommerceOrder(
     [echo] 			_user.getUserId(), _commerceAccount.getCommerceAccountId(),
     [echo] 			commerceChannel.getSiteGroupId(), commerceCurrency);
     [echo] 
     [echo] 		_commerceOrders.add(commerceOrder);
     [echo] 
     [echo] 		commerceOrder.setCommerceCurrencyId(
     [echo] 			commerceCurrency.getCommerceCurrencyId());
     [echo] 
     [echo] 		_commerceOrderLocalService.updateCommerceOrder(commerceOrder);
     [echo] 
     [echo] 		CPInstance cpInstanceDiscount = CPTestUtil.addCPInstanceWithSku();
     [echo] 
     [echo] 		CPInstance cpInstancePlain = CPTestUtil.addCPInstanceWithSku();
     [echo] 
     [echo] 		cpInstanceDiscount.setPrice(BigDecimal.valueOf(25));
     [echo] 		cpInstancePlain.setPrice(BigDecimal.valueOf(10));
     [echo] </code></pre></li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/158//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/158//testReport">here</a>.</h5></div></html>

2019-10-28 08:42 UTC, riccardo-alberti commented
ci:test

2019-10-28 08:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/146/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-18.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/146/jenkins-report.html">here</a>.</b></p>

2019-10-28 09:07 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 21 minutes 12 seconds 553 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/3e663171759b65ab67458498b0397d1edcd4f310">3e663171759b65ab67458498b0397d1edcd4f310</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :x:<pre><code>     [echo] &gt; Task :apps:commerce:commerce-shipping-engine-fixed-service:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-shipping-engine-fixed-test:pmdTestIntegration
     [echo] &gt; Task :apps:commerce:commerce-shipping-engine-fixed-web:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-shipping-origin-locator:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-shipping-origin-locator-api:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-shipping-web:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-subscription-web:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-taglib:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-tax-api:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-tax-engine-fixed-api:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-tax-engine-fixed-service:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-tax-engine-fixed-test:pmdTestIntegration
     [echo] &gt; Task :apps:commerce:commerce-tax-engine-fixed-web:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-tax-service:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-tax-test:pmdTestIntegration
     [echo] &gt; Task :apps:commerce:commerce-tax-web:pmdTestIntegration NO-SOURCE
     [echo] &gt; Task :apps:commerce:commerce-test:pmdTestIntegration FAILED
     [echo] 18 actionable tasks: 18 executed
     [echo] Gradle build finished at 2019-10-28 09:03:51.116.
     [echo] 
     [echo] See the profiling report at: file:///opt/dev/projects/github/liferay-portal-7.1.x/modules/apps/commerce/build/reports/profile/profile-2019-10-28-09-03-33.html
     [echo] A fine-grained performance profile is available: use the --scan option.
     [echo] 
      [for] subrepository-pmd-jdk8: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:27: Subrepository task FAILED: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-test-batch.xml:5644: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-common.xml:1043: Unable to execute Gradle task: pmdMain.
     [echo] </code></pre></li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [echo] java.lang.Exception: Found 5 formatting issues:
     [echo] 1: Reference to method 'addWarehouseCommerceChannelRel' does not need 'CommerceTestUtil.': ./commerce-test-util/src/main/java/com/liferay/commerce/test/util/CommerceTestUtil.java 254 (Checkstyle:SelfReferenceCheck)
     [echo] 2: Add the string 'from ' to the previous literal string: ./commerce-test/src/testIntegration/java/com/liferay/commerce/internal/util/test/CommerceShippingHelperTest.java 91 (Checkstyle:PlusStatementCheck)
     [echo] 3: Add the string 'from ' to the previous literal string: ./commerce-test/src/testIntegration/java/com/liferay/commerce/internal/util/test/CommerceShippingHelperTest.java 156 (Checkstyle:PlusStatementCheck)
     [echo] 4: Variable 'commerceCatalog' is unused: ./commerce-test/src/testIntegration/java/com/liferay/commerce/price/list/test/util/CommercePriceListTestUtil.java 62 (Checkstyle:UnusedVariableCheck)
     [echo] 5: ./commerce-test/src/testIntegration/java/com/liferay/commerce/discount/test/CommerceOrderDiscountTest.java expected:&lt;... discount on the " +[
     [echo] 				"total price"
     [echo] 		).when(
     [echo] 			"I try to get the final price of the order"
     [echo] 		).then(
     [echo] 			"The final price will be calculated taking into consideration " +
     [echo] 				"the discounts"
     [echo] 		);
     [echo] 
     [echo] 		CommerceCurrency commerceCurrency =
     [echo] 			CommerceCurrencyTestUtil.addCommerceCurrency();
     [echo] 
     [echo] 		CommerceChannel commerceChannel = CommerceTestUtil.addCommerceChannel(
     [echo] 			commerceCurrency.getCode());
     [echo] 
     [echo] 		CommerceOrder commerceOrder = CommerceTestUtil.addB2CCommerceOrder(
     [echo] 			_user.getUserId(), _commerceAccount.getCommerceAccountId(),
     [echo] 			commerceChannel.getSiteGroupId(), commerceCurrency);
     [echo] 
     [echo] 		_commerceOrders.add(commerceOrder);
     [echo] 
     [echo] 		commerceOrder.setCommerceCurrencyId(
     [echo] 			commerceCurrency.getCommerceCurrencyId());
     [echo] 
     [echo] 		_commerceOrderLocalService.updateCommerceOrder(commerceOrder);
     [echo] 
     [echo] 		CPInstance cpInstanceDiscount = CPTestUtil.addCPInstanceWithSku();
     [echo] 
     [echo] 		CPInstance cpInstancePlain = CPTestUtil.addCPInstanceWithSku();
     [echo] 
     [echo] 		cpInstanceDiscount.setPrice(BigDecimal.valueOf(25));
     [echo] 		cpInstancePlain.setPrice(BigDecimal.valueOf(10));
     [echo] </code></pre></li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/129//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/129//testReport">here</a>.</h5></div></html>

2019-10-30 10:05 UTC, riccardo-alberti commented
ci:test

2019-10-30 10:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/197/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/197/jenkins-report.html">here</a>.</b></p>

2019-10-30 10:35 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 25 minutes 9 seconds 624 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/f8b4ae86eb3da22d26e26c3d1c6c00738b6760a1">f8b4ae86eb3da22d26e26c3d1c6c00738b6760a1</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-9.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/37//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-9.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/37//testReport">here</a>.</h5></div></html>

2019-10-30 12:08 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:default - 3 out of 13 jobs passed in 2 hours 48 seconds 20 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/f8b4ae86eb3da22d26e26c3d1c6c00738b6760a1">f8b4ae86eb3da22d26e26c3d1c6c00738b6760a1</a></p><details><summary><strong>ci:test:default - 3 out of 13 jobs PASSED</strong></summary><div><h4>10 Failed Jobs:</h4><ul><li><a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/197/"><strike><strong>test-subrepository-acceptance-pullrequest(7.1.x)</strong></strike></a></li><li><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/690/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/829/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/828/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/635/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</strong></strike></a></li><li><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/691/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</strong></strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/638/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</strong></strike></a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/830/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</strong></strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/637/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</strong></strike></a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/831/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</strong></strike></a></li></ul></div><details><summary><strong>3 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/636/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/71/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-9.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/37/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details></details><h5>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/197/jenkins-report.html">here</a>.</h5><hr/><h4>Failures (upstream comparison is not available):</h4><ol><li><div><h5><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/690/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/690//consoleText">AXIS_VARIABLE=0,label_exp=!master #690</a><div><p>Startup error: <strong>Unresolved Requirement(s)</strong></p><pre><code>     [exec] 	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:425)
     [exec] 	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1577)
     [exec] 	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
     [exec] 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
     [exec] 	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:424)
     [exec] 	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:367)
     [exec] 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:929)
     [exec] 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:831)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     [exec] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1377)
     [exec] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1367)
     [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
     [exec] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
     [exec] 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:902)
     [exec] 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     [exec] 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:423)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     [exec] 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:928)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     [exec] 	at org.apache.catalina.startup.Catalina.start(Catalina.java:634)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:350)
     [exec] 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)</code></pre></div></div></li></ol></div></li><li><div><h5><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/829/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/829//consoleText">AXIS_VARIABLE=0,label_exp=!master #829</a><div><p>Startup error: <strong>Unresolved Requirement(s)</strong></p><pre><code>     [exec] 	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:425)
     [exec] 	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1577)
     [exec] 	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
     [exec] 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
     [exec] 	at org.apache.c [...]

2019-11-01 03:05 UTC, ethanbustad commented
ci:test

2019-11-01 03:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/129/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/129/jenkins-report.html">here</a>.</b></p>

2019-11-01 03:35 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 25 minutes 31 seconds 187 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/03a66d693f8eeab135933e18aa1126a40c2be4a5">03a66d693f8eeab135933e18aa1126a40c2be4a5</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/57//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/57//testReport">here</a>.</h5></div></html>

2019-11-01 05:02 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:default - 11 out of 13 jobs passed in 1 hour 57 minutes 1 second 946 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/03a66d693f8eeab135933e18aa1126a40c2be4a5">03a66d693f8eeab135933e18aa1126a40c2be4a5</a></p><details><summary><strong>ci:test:default - 11 out of 13 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/129/"><strike><strong>test-subrepository-acceptance-pullrequest(7.1.x)</strong></strike></a></li><li><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/998/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</strong></strike></a></li></ul></div><details><summary><strong>11 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-1.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/580/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/997/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-15.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/385/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/996/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/716/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-6.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/683/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/999/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/717/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/718/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></li><li><a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/77/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/57/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details></details><h5>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/129/jenkins-report.html">here</a>.</h5><hr/><h4>Failures (upstream comparison is not available):</h4><ol><li><div><h5><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/998/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</a></h5><div><h6>Job Results:</h6><p>1 Test Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/998//consoleText">AXIS_VARIABLE=0,label_exp=!master #998</a><ol><li><div><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/998//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CommerceFrontStore_ViewStoreFrontSimpleProduct_">LocalFile.CommerceFrontStore#ViewStoreFrontSimpleProduct</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-7/1572577571184/test-subrepository-acceptance-pullrequest(7.1.x)/129/subrepository-functional-tomcat90-mysql57-jdk8/6/0/LocalFile.CommerceFrontStore_ViewStoreFrontSimpleProduct/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-7/1572577571184/test-subrepository-acceptance-pullrequest(7.1.x)/129/subrepository-functional-tomcat90-mysql57-jdk8/6/0/LocalFile.CommerceFrontStore_ViewStoreFrontSimpleProduct/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-7/1572577571184/test-subrepository-acceptance-pullrequest(7.1.x)/129/subrepository-functional-tomcat90-mysql57-jdk8/6/0/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li></ol></details></html>

2019-11-25 15:53 UTC, riccardo-alberti commented
ci:test

2019-11-25 15:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/171/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-4.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/171/jenkins-report.html">here</a>.</b></p>

2019-11-25 16:21 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 24 minutes 12 seconds 70 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/aadc189412e470fb02505dd4f7f96c27ced41da4">aadc189412e470fb02505dd4f7f96c27ced41da4</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [echo] java.lang.Exception: Found 1 formatting issues:
     [echo] 1: ./commerce-theme-minium/commerce-theme-minium/src/css/minium/components/minium_card.scss expected:&lt;...;
     [echo] 	}
     [echo] 
     [echo] 	&amp;__price {
     [echo] 		[line-height: 1;
     [echo] 		margin-bottom: 20px];
     [echo] 	}
     [echo] 
     [echo] 	&amp;__add-to-wis...&gt; but was:&lt;...;
     [echo] 	}
     [echo] 
     [echo] 	&amp;__price {
     [echo] 		[margin-bottom: 20px;
     [echo] 		line-height: 1];
     [echo] 	}
     [echo] 
     [echo] 	&amp;__add-to-wis...&gt;
     [echo] 
     [echo] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:438)
     [echo] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:266)
     [echo] 
     [echo] FAILURE: Build failed with an exception.
     [echo] 
     [echo] * What went wrong:
     [echo] Execution failed for task ':checkSourceFormatting'.
     [echo] &gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [echo] 
     [echo] * Try:
     [echo] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [echo] 
     [echo] * Exception is:
     [echo] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':checkSourceFormatting'.
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
     [echo] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
     [echo] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
     [echo] 	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)</code></pre></li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/58//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>18 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/58//testReport">here</a>.</h5></div></html>

2019-11-26 20:26 UTC, ethanbustad commented
ci:test

2019-11-26 20:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/141/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/141/jenkins-report.html">here</a>.</b></p>

2019-11-26 21:25 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 51 minutes 38 seconds 337 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/5b86c10206c81d4fee3a4270b3ef98cd5b2e6357">5b86c10206c81d4fee3a4270b3ef98cd5b2e6357</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :x:<pre><code>     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:commerce:commerce-frontend-taglib:npmInstall'.
     [exec] &gt; java.io.IOException: Process '[/opt/dev/projects/github/liferay-portal-7.1.x/modules/apps/commerce/build/node/bin/node, /opt/dev/projects/github/liferay-portal-7.1.x/modules/apps/commerce/build/node/lib/node_modules/npm/bin/npm-cli.js, --production, false, --registry, http://mirrors.lax.liferay.com:4873, --loglevel, warn, --progress, true, install]' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:commerce:commerce-frontend-taglib:npmInstall'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
     [exec] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
     [exec] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
     [exec] 	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
     [exec] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)</code></pre></li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8 -  :x:<pre><code>Test failures detected. See below for details.</code></pre></li></ul><h5>For full console, click <a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/136//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>6 Tests Passed.<br/>1 Test Failed.</p></div></div><ol><li><div><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/136//testReport/com.liferay.portal.modules/ModulesStructureTest/testScanBuildScripts">ModulesStructureTest.testScanBuildScripts</a><pre><code>junit.framework.AssertionFailedError: Version must match the project version (2.0.0) modules/apps/frontend-js/frontend-js-react-web/package.json
	at com.liferay.portal.modules.ModulesStructureTest._testJSONVersion(ModulesStructureTest.java:1472)
	at com.liferay.portal.modules.ModulesStructureTest.access$500(ModulesStructureTest.java:66)
	at com.liferay.portal.modules.ModulesStructureTest$1.preVisitDirectory(ModulesStructureTest.java:255)
	at com.liferay.portal.modules.ModulesStructureTest$1.preVisitDirectory(ModulesStructureTest.java:122)
	at java.nio.file.Files.walkFileTree(Files.java:2677)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.modules.ModulesStructureTest.testScanBuildScripts(ModulesStructureTest.java:120)
</code></pre></div></li></ol><h5>For all test results, click <a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/136//testReport">here</a>.</h5></div></html>

2019-11-26 21:45 UTC, marco-leo commented
ci:test

2019-11-26 21:46 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/58/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/58/jenkins-report.html">here</a>.</b></p>

2019-11-26 22:13 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 25 minutes 43 seconds 458 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/013abbb6d36bf6469d644920de9401991789ee22">013abbb6d36bf6469d644920de9401991789ee22</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :x:<pre><code>Test failures detected. See below for details.</code></pre></li></ul><h5>For full console, click <a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/63//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>17 Tests Passed.<br/>1 Test Failed.</p></div></div><ol><li><div><a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/63//testReport/com.liferay.portal.modules/ModulesStructureTest/testScanBuildScripts">ModulesStructureTest.testScanBuildScripts</a><pre><code>junit.framework.AssertionFailedError: Version must match the project version (2.0.0) modules/apps/frontend-js/frontend-js-react-web/package.json
	at com.liferay.portal.modules.ModulesStructureTest._testJSONVersion(ModulesStructureTest.java:1472)
	at com.liferay.portal.modules.ModulesStructureTest.access$500(ModulesStructureTest.java:66)
	at com.liferay.portal.modules.ModulesStructureTest$1.preVisitDirectory(ModulesStructureTest.java:255)
	at com.liferay.portal.modules.ModulesStructureTest$1.preVisitDirectory(ModulesStructureTest.java:122)
	at java.nio.file.Files.walkFileTree(Files.java:2677)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.modules.ModulesStructureTest.testScanBuildScripts(ModulesStructureTest.java:120)
</code></pre></div></li></ol><h5>For all test results, click <a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/63//testReport">here</a>.</h5></div></html>

2019-11-26 22:30 UTC, ethanbustad requested changes

2019-11-26 22:30 UTC, ethanbustad commented on commerce-test-util/src/main/java/com/liferay/commerce/test/util/CommerceTestUtil.java
> +			LocaleUtil.US.getDisplayLanguage(), null,
`LocaleUtil.US.getDisplayLanguage()` returns probably `English`, but this method expects a languageId. I think we need to change this (and any other instances) to `LocaleUtil.toLanguageId(LocaleUtil.US)`.

2019-11-26 22:30 UTC, ethanbustad commented on commerce-test/src/testIntegration/java/com/liferay/commerce/price/list/test/util/CommercePriceListTestUtil.java
>  				groupId, commerceAccountId, userId);*/
this comment should be removed

2019-11-26 22:30 UTC, ethanbustad commented on commerce-test-util/build.gradle
> -	compileOnly project(":apps:commerce:commerce-shipping-engine-fixed-api")
Why switch these to static dependencies over project dependencies?

2019-11-26 22:30 UTC, ethanbustad commented on commerce-test/src/testIntegration/java/com/liferay/commerce/internal/order/test/CommerceOrderHttpHelperImplTest.java
> +		UserLocalServiceUtil.deleteUser(_user);
Is there a reason we're using `*LocalServiceUtil` here and not injecting the `*LocalService` instances instead? Seems like we should keep consistent by using the instances as much as possible.

2019-11-26 22:30 UTC, ethanbustad commented on commerce-test/src/testIntegration/java/com/liferay/commerce/test/CommercePriceListAccountGroupTest.java
> +				"to the account group associated to it"
`associate[d] with`, not `associate[d] to`

2019-11-26 22:30 UTC, ethanbustad commented on commerce-test/src/testIntegration/java/com/liferay/commerce/test/CommercePriceListAccountGroupTest.java
> +		CommerceAccountGroup accountGroup4 =
These should all be named `commerceAccountGroupX` rather than just `accountGroupX`.

2019-11-26 22:30 UTC, ethanbustad commented on commerce-test/src/testIntegration/java/com/liferay/commerce/test/CommercePriceListAccountGroupTest.java
> +	@Test(expected = Test.None.class)
If this test shouldn't throw an exception, just leave out the `expected` param and leave it with a bare `@Test` annotation

2019-11-26 22:30 UTC, ethanbustad commented on commerce-test/src/testIntegration/java/com/liferay/commerce/test/CommercePriceListAccountGroupTest.java
> +		CommerceAccountGroup commerceAccountGroup1 =
Should be named `commerceAccountGroup` rather than `commerceAccountGroup1`, since there's no `commerceAccountGroup2`

2019-11-27 11:15 UTC, riccardo-alberti commented
ci:test

2019-11-27 11:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/30/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-9.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/30/jenkins-report.html">here</a>.</b></p>

2019-11-27 11:51 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 24 minutes 44 seconds 254 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/3b41d292a28fc64c65a96b3cd8e138166a7c45f7">3b41d292a28fc64c65a96b3cd8e138166a7c45f7</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [exec] java.lang.Exception: Found 2 formatting issues:
     [exec] 1: Use 'LocaleUtil.US': ./commerce-test-util/src/main/java/com/liferay/commerce/test/util/CommerceTestUtil.java 306 (SourceCheck:LocaleUtilCheck)
     [exec] 2: &gt; 80: ./commerce-test/src/testIntegration/java/com/liferay/commerce/test/CommercePriceListAccountGroupTest.java 225 (SourceCheck:JavaLongLinesCheck)
     [exec] 
     [exec] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:438)
     [exec] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:266)
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':checkSourceFormatting'.
     [exec] &gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':checkSourceFormatting'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
     [exec] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
     [exec] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
     [exec] 	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
     [exec] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)</code></pre></li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/135//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>18 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/135//testReport">here</a>.</h5></div></html>

2019-11-28 17:21 UTC, riccardo-alberti commented
ci:test

2019-11-28 17:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/163/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/163/jenkins-report.html">here</a>.</b></p>

2019-11-28 17:54 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 24 minutes 44 seconds 393 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/a32979ffb3f94b0494e2a80d70b9eed30abc8196">a32979ffb3f94b0494e2a80d70b9eed30abc8196</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [exec] java.lang.Exception: Found 8 formatting issues:
     [exec] 1: Truncated message :
     [exec] ./headless/headless-commerce/headless-commerce-bom-impl/rest-openapi.yaml expected:&lt;...              $ref: ["#/components/schemas/Error"
     [exec]                 application/xml:
     [exec]                     schema:
     [exec]                         $ref: "#/components/schemas/Error"
     [exec]             description:
     [exec]                 The specified resource was not found
     [exec]         UnauthorizedError:
     [exec]             content:
     [exec]                 application/json:
     [exec]                     schema:
     [exec]                         $ref: "#/components/schemas/Error"
     [exec]                 application/xml:
     [exec]                     schema:
     [exec]                         $ref: "#/components/schemas/Error"
     [exec]             description:
     [exec]                 Authentication information is missing or invalid
     [exec]     schemas:
     [exec]         Area:
     [exec]             properties:
     [exec]                 breadcrumbs:
     [exec]                     example:
     [exec]                         - id: 31130
     [exec]                           name: Item 1
     [exec]                           slug: /Item-1
     [exec]                           street2: /Item/31130
     [exec]                           thumbnail: /schema.jpg
     [exec]                     items:
     [exec]                         $ref: "#/components/schemas/Breadcrumb"
     [exec]                     type: array
     [exec]                 data:
     [exec]                     $ref: "#/components/schemas/AreaData"
     [exec]             type: object
     [exec]         AreaData:
     [exec]             properties:
     [exec]                 id:
     [exec]                     example: Name 1
     [exec]                     type: string
     [exec]                 imageUrl:
     [exec]                     example: Name 1
     [exec]                     type: string
     [exec]                 name:
     [exec]                     example: Name 1
     [exec]                     type: string
     [exec]                 products:
     [exec]                     example:
     [exec]                         - id: 29130
     [exec]                           name: Product 1
     [exec]                           price: $ 12.99
     [exec]                           sku: SKU01</code></pre></li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/144//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>18 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/144//testReport">here</a>.</h5></div></html>

2019-12-05 13:35 UTC, closed without merging