COMMERCE-2316
liferay/com-liferay-commerce pull request #1596
Opened 2019-10-25 16:05 UTC by Commando18

2019-10-25 16:05 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2019-10-25 16:05 UTC, Commando18 commented
ci:test

2019-10-25 16:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/206/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-5.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/206/jenkins-report.html">here</a>.</b></p>

2019-10-25 16:34 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 26 minutes 12 seconds 171 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/7823f4eee3fe92e16fff8ea5782a97df1d3f9994">7823f4eee3fe92e16fff8ea5782a97df1d3f9994</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/200//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/200//testReport">here</a>.</h5></div></html>

2019-10-25 17:36 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test - 11 out of 13 jobs passed in 1 hour 30 minutes 55 seconds 883 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/7823f4eee3fe92e16fff8ea5782a97df1d3f9994">7823f4eee3fe92e16fff8ea5782a97df1d3f9994</a></p>11 out of 13 jobs PASSED<div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/206/"><strike><strong>test-subrepository-acceptance-pullrequest(7.1.x)</strong></strike></a></li><li><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/745/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</strong></strike></a></li></ul></div><details><summary><strong>11 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/801/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/623/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/802/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/731/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/744/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/624/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/803/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/732/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/746/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></li><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/58/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/200/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-5.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/206/jenkins-report.html">here</a>.</h5><hr/><h4>Failures (upstream comparison is not available):</h4><ol><li><div><h5><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/745/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</a></h5><div><h6>Job Results:</h6><p>1 Test Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/745//consoleText">AXIS_VARIABLE=0,label_exp=!master #745</a><ol><li><div><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/745//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CommerceFrontStore_ViewStoreFrontSimpleProduct_">LocalFile.CommerceFrontStore#ViewStoreFrontSimpleProduct</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-5/1572019580915/test-subrepository-acceptance-pullrequest(7.1.x)/206/subrepository-functional-tomcat90-mysql57-jdk8/6/0/LocalFile.CommerceFrontStore_ViewStoreFrontSimpleProduct/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-5/1572019580915/test-subrepository-acceptance-pullrequest(7.1.x)/206/subrepository-functional-tomcat90-mysql57-jdk8/6/0/LocalFile.CommerceFrontStore_ViewStoreFrontSimpleProduct/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-5/1572019580915/test-subrepository-acceptance-pullrequest(7.1.x)/206/subrepository-functional-tomcat90-mysql57-jdk8/6/0/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li></ol></details></html>

2019-10-25 18:10 UTC, ethanbustad commented
ci:test
tests should be fixed in upstream now

2019-10-25 18:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/160/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-4.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/160/jenkins-report.html">here</a>.</b></p>

2019-10-25 18:38 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 25 minutes 32 seconds 97 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/fcdbb7a76849c112f5888f4e0b9f71d1beae6a95">fcdbb7a76849c112f5888f4e0b9f71d1beae6a95</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/124//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/124//testReport">here</a>.</h5></div></html>

2019-10-25 19:31 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test - 13 out of 13 jobs passed in 1 hour 20 minutes 49 seconds 928 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/fcdbb7a76849c112f5888f4e0b9f71d1beae6a95">fcdbb7a76849c112f5888f4e0b9f71d1beae6a95</a></p>13 out of 13 jobs PASSED<details><summary><strong>13 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/160/">test-subrepository-acceptance-pullrequest(7.1.x)</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/858/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/932/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/680/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/532/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/737/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/398/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/589/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-6.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/626/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/791/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/859/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></li><li><a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/88/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/124/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/160/jenkins-report.html">here</a>.</h5></details></html>

2019-10-25 20:46 UTC, ethanbustad approved these changes

2019-12-05 17:32 UTC, marco-leo requested changes

2019-12-05 17:32 UTC, marco-leo commented on commerce-service/src/main/java/com/liferay/commerce/service/impl/CommerceOrderLocalServiceImpl.java
> +						MessageBusUtil.sendMessage(
@Commando18 This is a check that make sense to put in the consume quantity method of the inventory engine, and I would like to get an integration test with this fix that cover it

2019-12-06 15:53 UTC, marco-leo commented
ci:test

2019-12-06 15:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/165/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-17.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/165/jenkins-report.html">here</a>.</b></p>

2019-12-06 16:16 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 14 minutes 8 seconds 364 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/3f56476a9113411925a1cf0d98f23dc25c201c3c">3f56476a9113411925a1cf0d98f23dc25c201c3c</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :x:<pre><code>     [exec] * What went wrong:
     [exec] 42 actionable tasks: 42 executed
     [exec] Execution failed for task ':apps:commerce:commerce-frontend-taglib:npmInstall'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal-7.1.x/modules/apps/commerce/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:commerce:commerce-frontend-taglib:npmInstall'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
     [exec] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
     [exec] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
     [exec] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
     [exec] 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
     [exec] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)</code></pre></li><li>subrepository-semantic-versioning-jdk8 -  :x:<pre><code>     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:commerce:commerce-frontend-taglib:npmInstall'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal-7.1.x/modules/apps/commerce/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:commerce:commerce-frontend-taglib:npmInstall'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
     [exec] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
     [exec] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
     [exec] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
     [exec] 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
     [exec] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)</code></pre></li><li>central-requirements-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/153//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>7 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/153//testReport">here</a>.</h5></div></html>

2019-12-09 15:50 UTC, Commando18 commented
ci:test

2019-12-09 15:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/124/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/124/jenkins-report.html">here</a>.</b></p>

2019-12-09 16:37 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 38 minutes 19 seconds 638 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/752283dfccb8e901542452b57df692f6e9fef786">752283dfccb8e901542452b57df692f6e9fef786</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/139//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>22 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/139//testReport">here</a>.</h5></div></html>

2019-12-09 18:00 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:default - 4 out of 13 jobs passed in 2 hours 9 minutes 30 seconds 504 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/752283dfccb8e901542452b57df692f6e9fef786">752283dfccb8e901542452b57df692f6e9fef786</a></p><details><summary><strong>ci:test:default - 4 out of 13 jobs PASSED</strong></summary><div><h4>9 Failed Jobs:</h4><ul><li><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/124/"><strike><strong>test-subrepository-acceptance-pullrequest(7.1.x)</strong></strike></a></li><li><a href="https://test-1-6.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/701/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/915/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-6.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/700/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</strong></strike></a></li><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/647/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</strong></strike></a></li><li><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/650/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</strong></strike></a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/917/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</strong></strike></a></li><li><a href="https://test-1-6.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/702/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</strong></strike></a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/918/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</strong></strike></a></li></ul></div><details><summary><strong>4 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/649/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/916/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/95/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/139/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details></details><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/124/jenkins-report.html">here</a>.</h5><hr/><h4>Failures (upstream comparison is not available):</h4><ol><li><div><h5><a href="https://test-1-6.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/701/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-6.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/701//consoleText">AXIS_VARIABLE=0,label_exp=!master #701</a><pre><code>     [exec] * What went wrong:
     [exec] 
     [exec] Project directory '/opt/dev/projects/github/liferay-portal-7.1.x/modules/dxp/apps/commerce' is not part of the build defined by settings file '/opt/dev/projects/github/liferay-portal-7.1.x/modules/settings.gradle'. If this is an unrelated build, it must have its own settings file.
     [exec] 
     [exec] * Try:
     [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal-7.1.x/modules/dxp/apps/commerce/reports/profile/profile-2019-12-09-09-53-26.html
     [exec] A fine-grained performance profile is available: use the --scan option.
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.InvalidUserDataException: Project directory '/opt/dev/projects/github/liferay-portal-7.1.x/modules/dxp/apps/commerce' is not part of the build defined by settings file '/opt/dev/projects/github/liferay-portal-7.1.x/modules/settings.gradle'. If this is an unrelated build, it must have its own settings file.
     [exec] 	at org.gradle.initialization.AbstractProjectSpec.selectProject(AbstractProjectSpec.java:42)
     [exec] 	at org.gradle.initialization.DefaultSettingsLoader.setDefaultProject(DefaultSettingsLoader.java:88)
     [exec] 	at org.gradle.initialization.DefaultSettingsLoader.findAndLoadSettings(DefaultSettingsLoader.java:52)
     [exec] 	at org.gradle.initialization.SettingsAttachingSettingsLoader.findAndLoadSettings(SettingsAttachingSettingsLoader.java:35)
     [exec] 	at org.gradle.internal.composite.CommandLineIncludedBuildSettingsLoader.findAndLoadSettings(CommandLineIncludedBuildSettingsLoader.java:34)
     [exec] 	at org.gradle.internal.composite.ChildBuildRegisteringSettingsLoader.findAndLoadSettings(ChildBuildRegisteringSettingsLoader.java:47)
     [exec] 	at org.gradle.internal.composite.CompositeBuildSettingsLoader.findAndLoadSettings(CompositeBuildSettingsLoader.java:35)
     [exec] 	at org.gradle.initialization.DefaultSettingsPreparer.prepareSettings(DefaultSettingsPreparer.java:36)
     [exec] 	at org.gradle.initialization.BuildOperatingFiringSettingsPreparer$LoadBuild.doLoadBuild(BuildOperatingFiringSettingsPreparer.java:59)
     [exec] 	at org.gradle.initialization.BuildOperatingFiringSettingsPreparer$LoadBuild.run(BuildOperatingFiringSettingsPreparer.java:54)</code></pre></div></li></ol></div></li><li><div><h5><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/915/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/915//consoleText">AXIS_VARIABLE=0,label_exp=!master #915</a><pre><code>     [exec] * What went wrong:
     [exec] Project directory '/opt/dev/projects/github/liferay-portal-7.1.x/modules/dxp/apps/commerce' is not part of the build defined by settings file '/opt/dev/projects/github/liferay-portal-7.1.x/modules/settings.gradle'. If this is an unrelated build, it must have its own settings file.
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.InvalidUserDataException: Project directory '/opt/dev/projects/github/liferay-portal-7.1.x/modules/dxp/apps [...]

2019-12-09 23:29 UTC, ethanbustad approved these changes

2019-12-09 23:29 UTC, ethanbustad commented on commerce-service/src/main/java/com/liferay/commerce/service/impl/CommerceOrderLocalServiceImpl.java
> +				"OrderItemId ",
should these keys have a trailing space in them?

2019-12-09 23:29 UTC, ethanbustad commented on commerce-service/src/main/java/com/liferay/commerce/service/impl/CommerceOrderLocalServiceImpl.java
> +				"OrderItemId ",
Oh... looks like they had a trailing space before? Weird, but alright.

2019-12-10 23:27 UTC, merged