COMMERCE-2401 Define default account role
liferay/com-liferay-commerce pull request #1627
Opened 2019-11-05 18:48 UTC by Commando18

2019-11-05 18:48 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2019-11-05 18:48 UTC, Commando18 commented
ci:test

2019-11-05 18:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/193/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-20.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/193/jenkins-report.html">here</a>.</b></p>

2019-11-05 19:02 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 9 minutes 16 seconds 33 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/7a209ffa2b542f9dbe51955cedafc1ba0f4cb2b8">7a209ffa2b542f9dbe51955cedafc1ba0f4cb2b8</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :x:<pre><code>subrepository-compile-jdk8
   [delete] Deleting: /opt/dev/projects/github/liferay-portal-7.1.x/null2101519854.properties

subrepository-compile-jdk8:
 [sync-dir] Synchronizing /opt/dev/projects/github/liferay-binaries-cache-2020/.gradle/caches/modules-2/files-2.1 into /opt/dev/projects/github/liferay-portal-7.1.x/.gradle/caches/modules-2/files-2.1
 [sync-dir] 0 files synchronized in 297ms
     [echo] ${gradle.output.error}
      [for] subrepository-compile-jdk8: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:27: Subrepository task FAILED: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-test-batch.xml:5665: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-common.xml:859: exec returned: 1
     [echo] </code></pre></li><li>subrepository-semantic-versioning-jdk8 -  :x:<pre><code>subrepository-semantic-versioning-jdk8:
     [echo] Deleting stale baseline log files.
     [echo] Executing baseline on /opt/dev/projects/github/liferay-portal-7.1.x/modules/dxp/apps/commerce.
 [sync-dir] Synchronizing /opt/dev/projects/github/liferay-binaries-cache-2020/.gradle/caches/modules-2/files-2.1 into /opt/dev/projects/github/liferay-portal-7.1.x/.gradle/caches/modules-2/files-2.1
 [sync-dir] 0 files synchronized in 314ms
     [echo] ${gradle.output.error}
      [for] subrepository-semantic-versioning-jdk8: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:27: Subrepository task FAILED: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-test-batch.xml:5733: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-common.xml:859: exec returned: 1
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:120: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:13: Keepgoing execution: 2 of 3 iterations failed.
[beanshell] 3675 GitHub API calls out of 5000 remain. GitHub API call limit will reset in 20 minutes 40 seconds 735 ms.
[beanshell]     https://api.github.com/repos/liferay/com-liferay-commerce/pulls/1627
[beanshell] Executing commands: cat /tmp/960953860.txt | mail -v -s "CI Failure has occurred" -r "ci_failure_notification" "qa-slave-verify-fail@liferay.com"
     [echo] A CI failure has occurred. QA Engineering has been notified. Please try again later or contact QA Engineering for an update.

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:11244: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:127: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:120: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:13: Keepgoing execution: 2 of 3 iterations failed.</code></pre></li><li>central-requirements-jdk8 -  :x:<pre><code>Test failures detected. See below for details.</code></pre></li></ul><h5>For full console, click <a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/131//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>6 Tests Passed.<br/>1 Test Failed.</p></div></div><ol><li><div><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/131//testReport/com.liferay.portal.modules/ModulesStructureTest/testScanBuildScripts">ModulesStructureTest.testScanBuildScripts</a></div></li></ol><h5>For all test results, click <a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/131//testReport">here</a>.</h5></div></html>

2019-11-05 20:19 UTC, ethanbustad requested changes

2019-11-05 20:19 UTC, ethanbustad commented on build.gradle
> +		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.defaults", version: "6.1.77"
We should remove this commit. This should be fixed by https://github.com/brianchandotcom/liferay-portal/pull/80545.

2019-11-05 20:19 UTC, ethanbustad commented on commerce-account-api/src/main/java/com/liferay/commerce/account/constants/CommerceAccountConstants.java
> +
All of these `*_ROLE_NAME` constants should probably be named `ROLE_NAME_*` instead. Ideally the specifics should come last -- and this actually goes for some of the other constants in this file. Examples of what I mean:

    ACCOUNT_BUYER_ROLE_NAME -> ROLE_NAME_ACCOUNT_BUYER
    ACCOUNT_GROUP_GUEST_NAME -> ACCOUNT_GROUP_NAME_GUEST
    ACCOUNT_ORDER_MANAGER_ROLE_NAME -> ROLE_NAME_ACCOUNT_ORDER_MANAGER
    DEFAULT_PARENT_ACCOUNT_ID -> ACCOUNT_ID_PARENT_DEFAULT (maybe?)
    GUEST_ACCOUNT_ID -> ACCOUNT_ID_GUEST

This type of naming makes it so similar constants are grouped together, which is very much desired in a class like this.

2019-11-05 20:19 UTC, ethanbustad commented on commerce-account-service/src/main/java/com/liferay/commerce/account/service/impl/CommerceAccountUserRelLocalServiceImpl.java
> +		Set<Long> roleIdSet = new HashSet<>();
Why do we need this `Set`? It looks like it only ever has 1 entry, and it's only used to create an array, so we might as well just directly create an array of 1, yeah?

2019-11-05 20:19 UTC, ethanbustad commented on commerce-lang/src/main/resources/content/Language.properties
> +apply-default-role-to-existing-users=Apply Default Role To Existing Users
value should be `Apply Default Role to Existing Users` -- lowercase `t` in `to`

2019-11-06 11:06 UTC, Commando18 commented
ci:test

2019-11-06 11:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/316/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-22.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/316/jenkins-report.html">here</a>.</b></p>

2019-11-06 11:09 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:default - 0 out of 1 jobs passed in 2 minutes 2 seconds 31 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/7a209ffa2b542f9dbe51955cedafc1ba0f4cb2b8">7a209ffa2b542f9dbe51955cedafc1ba0f4cb2b8</a></p><details><summary><strong>ci:test:default - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/316/"><strike><strong>test-subrepository-acceptance-pullrequest(7.1.x)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-22.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/316/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/316/">test-subrepository-acceptance-pullrequest(7.1.x)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><div><p>The sender branch SHA could not be found on <strong><a href="https://github.com/Commando18/com-liferay-commerce/tree/COMMERCE-2401">Commando18/COMMERCE-2401</a></strong>. The sender branch may have been force pushed or deleted after the pull request test was initiated.</p><pre><code>fatal: Not a valid branch point: '7ab477e120f2cc14c861406e39ed9f21a7fb1336'.</code></pre></div></div></li></ol></details></html>

2019-11-06 11:45 UTC, Commando18 commented
ci:test

2019-11-06 11:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/220/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-5.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/220/jenkins-report.html">here</a>.</b></p>

2019-11-06 11:58 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 9 minutes 4 seconds 360 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/7a209ffa2b542f9dbe51955cedafc1ba0f4cb2b8">7a209ffa2b542f9dbe51955cedafc1ba0f4cb2b8</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :x:<pre><code>subrepository-compile-jdk8
   [delete] Deleting: /opt/dev/projects/github/liferay-portal-7.1.x/null4741841.properties

subrepository-compile-jdk8:
 [sync-dir] Synchronizing /opt/dev/projects/github/liferay-binaries-cache-2020/.gradle/caches/modules-2/files-2.1 into /opt/dev/projects/github/liferay-portal-7.1.x/.gradle/caches/modules-2/files-2.1
 [sync-dir] 0 files synchronized in 479ms
     [echo] ${gradle.output.error}
      [for] subrepository-compile-jdk8: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:27: Subrepository task FAILED: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-test-batch.xml:5698: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-common.xml:859: exec returned: 1
     [echo] </code></pre></li><li>subrepository-semantic-versioning-jdk8 -  :x:<pre><code>subrepository-semantic-versioning-jdk8:
     [echo] Deleting stale baseline log files.
     [echo] Executing baseline on /opt/dev/projects/github/liferay-portal-7.1.x/modules/dxp/apps/commerce.
 [sync-dir] Synchronizing /opt/dev/projects/github/liferay-binaries-cache-2020/.gradle/caches/modules-2/files-2.1 into /opt/dev/projects/github/liferay-portal-7.1.x/.gradle/caches/modules-2/files-2.1
 [sync-dir] 0 files synchronized in 347ms
     [echo] ${gradle.output.error}
      [for] subrepository-semantic-versioning-jdk8: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:27: Subrepository task FAILED: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-test-batch.xml:5766: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-common.xml:859: exec returned: 1
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:120: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:13: Keepgoing execution: 2 of 3 iterations failed.
[beanshell] 3420 GitHub API calls out of 5000 remain. GitHub API call limit will reset in 8 minutes 53 seconds 339 ms.
[beanshell]     https://api.github.com/repos/liferay/com-liferay-commerce/pulls/1627
[beanshell] Executing commands: cat /tmp/-1707378238.txt | mail -v -s "CI Failure has occurred" -r "ci_failure_notification" "qa-slave-verify-fail@liferay.com"
     [echo] A CI failure has occurred. QA Engineering has been notified. Please try again later or contact QA Engineering for an update.

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:11244: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:127: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:120: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:13: Keepgoing execution: 2 of 3 iterations failed.</code></pre></li><li>central-requirements-jdk8 -  :x:<pre><code>Test failures detected. See below for details.</code></pre></li></ul><h5>For full console, click <a href="https://test-1-15.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/39//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>6 Tests Passed.<br/>1 Test Failed.</p></div></div><ol><li><div><a href="https://test-1-15.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/39//testReport/com.liferay.portal.modules/ModulesStructureTest/testScanBuildScripts">ModulesStructureTest.testScanBuildScripts</a><pre><code>junit.framework.AssertionFailedError: Incorrect "project.path.prefix" in modules/dxp/apps/commerce/gradle.properties expected:&lt;:[dxp]:apps:commerce&gt; but was:&lt;:[private]:apps:commerce&gt;
	at com.liferay.portal.modules.ModulesStructureTest._testGitRepoBuildScripts(ModulesStructureTest.java:1180)
	at com.liferay.portal.modules.ModulesStructureTest.access$200(ModulesStructureTest.java:65)
	at com.liferay.portal.modules.ModulesStructureTest$1.preVisitDirectory(ModulesStructureTest.java:159)
	at com.liferay.portal.modules.ModulesStructureTest$1.preVisitDirectory(ModulesStructureTest.java:121)
	at java.nio.file.Files.walkFileTree(Files.java:2677)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.modules.ModulesStructureTest.testScanBuildScripts(ModulesStructureTest.java:119)
</code></pre></div></li></ol><h5>For all test results, click <a href="https://test-1-15.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/39//testReport">here</a>.</h5></div></html>

2019-11-06 23:06 UTC, merged

2019-11-06 23:06 UTC, marco-leo commented
@ethanbustad Merging, feel free to ask more changes