COMMERCE-2401 Fixed default account roles association
liferay/com-liferay-commerce pull request #1641
Opened 2019-11-07 16:29 UTC by Commando18

2019-11-07 16:29 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2019-11-07 16:29 UTC, Commando18 commented
ci:test

2019-11-07 16:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/201/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/201/jenkins-report.html">here</a>.</b></p>

2019-11-07 16:43 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 9 minutes 45 seconds 289 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/79ef92b9cd10dfcdac4248b0b4f134dd019aaf36">79ef92b9cd10dfcdac4248b0b4f134dd019aaf36</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :x:<pre><code>subrepository-compile-jdk8
   [delete] Deleting: /opt/dev/projects/github/liferay-portal-7.1.x/null217890612.properties

subrepository-compile-jdk8:
 [sync-dir] Synchronizing /opt/dev/projects/github/liferay-binaries-cache-2020/.gradle/caches/modules-2/files-2.1 into /opt/dev/projects/github/liferay-portal-7.1.x/.gradle/caches/modules-2/files-2.1
 [sync-dir] 0 files synchronized in 293ms
     [echo] ${gradle.output.error}
      [for] subrepository-compile-jdk8: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:27: Subrepository task FAILED: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-test-batch.xml:5691: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-common.xml:859: exec returned: 1
     [echo] </code></pre></li><li>subrepository-semantic-versioning-jdk8 -  :x:<pre><code>subrepository-semantic-versioning-jdk8:
     [echo] Deleting stale baseline log files.
     [echo] Executing baseline on /opt/dev/projects/github/liferay-portal-7.1.x/modules/dxp/apps/commerce.
 [sync-dir] Synchronizing /opt/dev/projects/github/liferay-binaries-cache-2020/.gradle/caches/modules-2/files-2.1 into /opt/dev/projects/github/liferay-portal-7.1.x/.gradle/caches/modules-2/files-2.1
 [sync-dir] 0 files synchronized in 315ms
     [echo] ${gradle.output.error}
      [for] subrepository-semantic-versioning-jdk8: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:27: Subrepository task FAILED: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-test-batch.xml:5759: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-common.xml:859: exec returned: 1
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:120: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:13: Keepgoing execution: 2 of 3 iterations failed.
[beanshell] 3875 GitHub API calls out of 5000 remain. GitHub API call limit will reset in 14 minutes 20 seconds 956 ms.
[beanshell]     https://api.github.com/repos/liferay/com-liferay-commerce/pulls/1641
[beanshell] Executing commands: cat /tmp/-1952259827.txt | mail -v -s "CI Failure has occurred" -r "ci_failure_notification" "qa-slave-verify-fail@liferay.com"
     [echo] A CI failure has occurred. QA Engineering has been notified. Please try again later or contact QA Engineering for an update.

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:11244: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:127: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:120: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:13: Keepgoing execution: 2 of 3 iterations failed.</code></pre></li><li>central-requirements-jdk8 -  :x:<pre><code>Test failures detected. See below for details.</code></pre></li></ul><h5>For full console, click <a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/126//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>6 Tests Passed.<br/>1 Test Failed.</p></div></div><ol><li><div><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/126//testReport/com.liferay.portal.modules/ModulesStructureTest/testScanBuildScripts">ModulesStructureTest.testScanBuildScripts</a><pre><code>junit.framework.AssertionFailedError: Incorrect "project.path.prefix" in modules/dxp/apps/commerce/gradle.properties expected:&lt;:[dxp]:apps:commerce&gt; but was:&lt;:[private]:apps:commerce&gt;
	at com.liferay.portal.modules.ModulesStructureTest._testGitRepoBuildScripts(ModulesStructureTest.java:1180)
	at com.liferay.portal.modules.ModulesStructureTest.access$200(ModulesStructureTest.java:65)
	at com.liferay.portal.modules.ModulesStructureTest$1.preVisitDirectory(ModulesStructureTest.java:159)
	at com.liferay.portal.modules.ModulesStructureTest$1.preVisitDirectory(ModulesStructureTest.java:121)
	at java.nio.file.Files.walkFileTree(Files.java:2677)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.modules.ModulesStructureTest.testScanBuildScripts(ModulesStructureTest.java:119)
</code></pre></div></li></ol><h5>For all test results, click <a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/126//testReport">here</a>.</h5></div></html>

2019-11-13 18:42 UTC, ethanbustad requested changes

2019-11-13 18:42 UTC, ethanbustad commented on commerce-account-api/src/main/java/com/liferay/commerce/account/configuration/CommerceAccountServiceConfiguration.java
> +	@Meta.AD(deflt = "", name = "site-roles", required = false)
I believe `deflt = ""` is the default, so there's no need to specify this.

2019-11-13 18:42 UTC, ethanbustad commented on commerce-account-service/src/main/java/com/liferay/commerce/account/service/impl/CommerceAccountUserRelLocalServiceImpl.java
> +			Role role = rolePersistence.fetchByC_N(
Can't we use `roleLocalService.fetchRole` here? That'd be better

2019-11-13 18:42 UTC, ethanbustad commented on commerce-account-service/src/main/java/com/liferay/commerce/account/service/impl/CommerceAccountUserRelLocalServiceImpl.java
> +			if (role.getType() != RoleConstants.TYPE_SITE) {
These 2 `continue` blocks should be combined

2019-12-06 15:16 UTC, marco-leo commented
@Commando18

2019-12-09 15:03 UTC, Commando18 commented
Fixed, thanks @ethanbustad 

cc @marco-leo

2019-12-09 15:03 UTC, Commando18 commented
ci:test

2019-12-09 15:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/152/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/152/jenkins-report.html">here</a>.</b></p>

2019-12-09 15:51 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 38 minutes 36 seconds 962 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/752283dfccb8e901542452b57df692f6e9fef786">752283dfccb8e901542452b57df692f6e9fef786</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [exec] java.lang.Exception: Found 1 formatting issues:
     [exec] 1: Illegal call to class 'com.liferay.portal.kernel.service.persistence.RolePersistence', see LPS-68923: ./commerce-account-service/src/main/java/com/liferay/commerce/account/service/impl/CommerceAccountUserRelLocalServiceImpl.java 168 (Checkstyle:PersistenceCallCheck)
     [exec] 
     [exec] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:438)
     [exec] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:266)
     [exec] Illegal call to class 'com.liferay.portal.kernel.service.persistence.RolePersistence', see LPS-68923: ./commerce-account-service/src/main/java/com/liferay/commerce/account/service/impl/CommerceAccountUserRelLocalServiceImpl.java 168 (Checkstyle:PersistenceCallCheck)
     [exec] 
     [exec] 
     [exec] &gt; Task :checkSourceFormatting FAILED
     [exec] Gradle build finished at 2019-12-09 15:48:42.859.
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':checkSourceFormatting'.
     [exec] &gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':checkSourceFormatting'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
     [exec] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
     [exec] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)</code></pre></li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/197//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>22 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/197//testReport">here</a>.</h5></div></html>

2019-12-09 18:21 UTC, ethanbustad commented on commerce-account-service/src/main/java/com/liferay/commerce/account/service/impl/CommerceAccountUserRelLocalServiceImpl.java
> +			Role role = rolePersistence.fetchByC_N(
@Commando18 looks like this line is still the same, and SF doesn't allow it. Can you make the change?

2019-12-10 22:49 UTC, marco-leo commented
ci:test

2019-12-10 22:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-13.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/117/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-13.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/117/jenkins-report.html">here</a>.</b></p>

2019-12-10 22:53 UTC, ethanbustad commented
@Commando18 there's still one change to make from my last review, which is causing the validation failure

2019-12-10 23:38 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 26 minutes 51 seconds 548 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/eccfe22d5f94c701d022c3e5071d5e9d40af940d">eccfe22d5f94c701d022c3e5071d5e9d40af940d</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [exec] java.lang.Exception: Found 1 formatting issues:
     [exec] 1: Illegal call to class 'com.liferay.portal.kernel.service.persistence.RolePersistence', see LPS-68923: ./commerce-account-service/src/main/java/com/liferay/commerce/account/service/impl/CommerceAccountUserRelLocalServiceImpl.java 168 (Checkstyle:PersistenceCallCheck)
     [exec] 
     [exec] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:438)
     [exec] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:266)
     [exec] Gradle build finished at 2019-12-10 23:35:48.739.
     [exec] 1 actionable task: 1 executed
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':checkSourceFormatting'.
     [exec] &gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':checkSourceFormatting'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
     [exec] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
     [exec] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
     [exec] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)</code></pre></li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/152//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>22 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/152//testReport">here</a>.</h5></div></html>

2019-12-11 20:24 UTC, ethanbustad commented
Rebased, fixed SF issues, and sent along to https://github.com/liferay/com-liferay-commerce/pull/1793.

2019-12-11 20:24 UTC, closed without merging