COMMERCE-2115 fixed checked payment method
liferay/com-liferay-commerce pull request #1650
Opened 2019-11-08 17:00 UTC by andrea-ale-sbarra

2019-11-08 17:00 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2019-11-08 17:00 UTC, andrea-ale-sbarra commented
ci:test

2019-11-08 17:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/202/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/202/jenkins-report.html">here</a>.</b></p>

2019-11-08 17:13 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 8 minutes 2 seconds 785 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/feaa68509b8f3c9707374cf7dd835a43ba0b02fd">feaa68509b8f3c9707374cf7dd835a43ba0b02fd</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :x:<pre><code>subrepository-compile-jdk8
   [delete] Deleting: /opt/dev/projects/github/liferay-portal-7.1.x/null1269108911.properties

subrepository-compile-jdk8:
 [sync-dir] Synchronizing /opt/dev/projects/github/liferay-binaries-cache-2020/.gradle/caches/modules-2/files-2.1 into /opt/dev/projects/github/liferay-portal-7.1.x/.gradle/caches/modules-2/files-2.1
 [sync-dir] 0 files synchronized in 370ms
     [echo] ${gradle.output.error}
      [for] subrepository-compile-jdk8: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:27: Subrepository task FAILED: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-test-batch.xml:5691: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-common.xml:859: exec returned: 1
     [echo] </code></pre></li><li>subrepository-semantic-versioning-jdk8 -  :x:<pre><code>subrepository-semantic-versioning-jdk8:
     [echo] Deleting stale baseline log files.
     [echo] Executing baseline on /opt/dev/projects/github/liferay-portal-7.1.x/modules/dxp/apps/commerce.
 [sync-dir] Synchronizing /opt/dev/projects/github/liferay-binaries-cache-2020/.gradle/caches/modules-2/files-2.1 into /opt/dev/projects/github/liferay-portal-7.1.x/.gradle/caches/modules-2/files-2.1
 [sync-dir] 0 files synchronized in 332ms
     [echo] ${gradle.output.error}
      [for] subrepository-semantic-versioning-jdk8: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:27: Subrepository task FAILED: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-test-batch.xml:5759: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-common.xml:859: exec returned: 1
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:120: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:13: Keepgoing execution: 2 of 3 iterations failed.
[beanshell] 4925 GitHub API calls out of 5000 remain. GitHub API call limit will reset in 55 minutes 57 seconds 161 ms.
[beanshell]     https://api.github.com/repos/liferay/com-liferay-commerce/pulls/1650
[beanshell] Executing commands: cat /tmp/2056651563.txt | mail -v -s "CI Failure has occurred" -r "ci_failure_notification" "qa-slave-verify-fail@liferay.com"
     [echo] A CI failure has occurred. QA Engineering has been notified. Please try again later or contact QA Engineering for an update.

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:11244: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:127: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:120: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:13: Keepgoing execution: 2 of 3 iterations failed.</code></pre></li><li>central-requirements-jdk8 -  :x:<pre><code>Test failures detected. See below for details.</code></pre></li></ul><h5>For full console, click <a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/124//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>6 Tests Passed.<br/>1 Test Failed.</p></div></div><ol><li><div><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/124//testReport/com.liferay.portal.modules/ModulesStructureTest/testScanBuildScripts">ModulesStructureTest.testScanBuildScripts</a><pre><code>junit.framework.AssertionFailedError: Incorrect "project.path.prefix" in modules/dxp/apps/commerce/gradle.properties expected:&lt;:[dxp]:apps:commerce&gt; but was:&lt;:[private]:apps:commerce&gt;
	at com.liferay.portal.modules.ModulesStructureTest._testGitRepoBuildScripts(ModulesStructureTest.java:1180)
	at com.liferay.portal.modules.ModulesStructureTest.access$200(ModulesStructureTest.java:65)
	at com.liferay.portal.modules.ModulesStructureTest$1.preVisitDirectory(ModulesStructureTest.java:159)
	at com.liferay.portal.modules.ModulesStructureTest$1.preVisitDirectory(ModulesStructureTest.java:121)
	at java.nio.file.Files.walkFileTree(Files.java:2677)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.modules.ModulesStructureTest.testScanBuildScripts(ModulesStructureTest.java:119)
</code></pre></div></li></ol><h5>For all test results, click <a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/124//testReport">here</a>.</h5></div></html>

2019-11-08 23:44 UTC, marco-leo requested changes

2019-11-08 23:44 UTC, marco-leo commented on commerce-checkout-web/src/main/resources/META-INF/resources/checkout_step/payment_method.jsp
> +							<aui:input checked="<%= commercePaymentMethod.getKey().equals(commercePaymentMethodKey) %>" label="<%= commercePaymentMethod.getName(locale) %>" name="commercePaymentMethodKey" type="radio" va
@andrea-ale-sbarra avoid chain, better do commercePaymentMethodKey.equals(commercePaymentMethod.getKey())

2019-11-11 08:42 UTC, andrea-ale-sbarra commented
ci:test

2019-11-11 08:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/134/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/134/jenkins-report.html">here</a>.</b></p>

2019-11-11 08:54 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 7 minutes 24 seconds 288 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/e2cd4d2caaa0285f9a6d42b5ab7208f88c680f24">e2cd4d2caaa0285f9a6d42b5ab7208f88c680f24</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :x:<pre><code>subrepository-compile-jdk8
   [delete] Deleting: /opt/dev/projects/github/liferay-portal-7.1.x/null744896244.properties

subrepository-compile-jdk8:
 [sync-dir] Synchronizing /opt/dev/projects/github/liferay-binaries-cache-2020/.gradle/caches/modules-2/files-2.1 into /opt/dev/projects/github/liferay-portal-7.1.x/.gradle/caches/modules-2/files-2.1
 [sync-dir] 0 files synchronized in 310ms
     [echo] ${gradle.output.error}
      [for] subrepository-compile-jdk8: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:27: Subrepository task FAILED: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-test-batch.xml:5691: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-common.xml:859: exec returned: 1
     [echo] </code></pre></li><li>subrepository-semantic-versioning-jdk8 -  :x:<pre><code>subrepository-semantic-versioning-jdk8:
     [echo] Deleting stale baseline log files.
     [echo] Executing baseline on /opt/dev/projects/github/liferay-portal-7.1.x/modules/dxp/apps/commerce.
 [sync-dir] Synchronizing /opt/dev/projects/github/liferay-binaries-cache-2020/.gradle/caches/modules-2/files-2.1 into /opt/dev/projects/github/liferay-portal-7.1.x/.gradle/caches/modules-2/files-2.1
 [sync-dir] 0 files synchronized in 299ms
     [echo] ${gradle.output.error}
      [for] subrepository-semantic-versioning-jdk8: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:27: Subrepository task FAILED: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-test-batch.xml:5759: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-common.xml:859: exec returned: 1
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:120: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:13: Keepgoing execution: 2 of 3 iterations failed.
[beanshell] 3926 GitHub API calls out of 5000 remain. GitHub API call limit will reset in 7 minutes 41 seconds 947 ms.
[beanshell]     https://api.github.com/repos/liferay/com-liferay-commerce/pulls/1650
[beanshell] Executing commands: cat /tmp/-1418285645.txt | mail -v -s "CI Failure has occurred" -r "ci_failure_notification" "qa-slave-verify-fail@liferay.com"
     [echo] A CI failure has occurred. QA Engineering has been notified. Please try again later or contact QA Engineering for an update.

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:11244: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:127: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:120: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:13: Keepgoing execution: 2 of 3 iterations failed.</code></pre></li><li>central-requirements-jdk8 -  :x:<pre><code>Test failures detected. See below for details.</code></pre></li></ul><h5>For full console, click <a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/139//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>6 Tests Passed.<br/>1 Test Failed.</p></div></div><ol><li><div><a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/139//testReport/com.liferay.portal.modules/ModulesStructureTest/testScanBuildScripts">ModulesStructureTest.testScanBuildScripts</a></div></li></ol><h5>For all test results, click <a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/139//testReport">here</a>.</h5></div></html>

2019-11-12 21:58 UTC, merged

2019-11-12 23:41 UTC, ethanbustad commented on commerce-checkout-web/src/main/resources/META-INF/resources/checkout_step/payment_method.jsp
> +
@andrea-ale-sbarra looks like an extra line got in here -- can you remove in a follow-up PR?