Commerce 2468
liferay/com-liferay-commerce pull request #1689
Opened 2019-11-20 15:31 UTC by andrea-ale-sbarra

2019-11-20 15:31 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2019-11-20 15:31 UTC, andrea-ale-sbarra commented
ci:test

2019-11-20 15:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/184/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/184/jenkins-report.html">here</a>.</b></p>

2019-11-20 15:33 UTC, andrea-ale-sbarra commented on headless/headless-commerce/headless-commerce-admin-inventory-impl/src/main/java/com/liferay/headless/commerce/admin/inventory/internal/resource/v1_0/WarehouseItemResourceImpl.java
> +			start = new Date();
@marco-leo not 100% about this change, but I think it make sense.. let me know what do you think. Thank you.

2019-11-20 15:35 UTC, andrea-ale-sbarra commented on headless/headless-commerce/headless-commerce-admin-inventory-impl/src/main/java/com/liferay/headless/commerce/admin/inventory/internal/resource/v1_0/WarehouseItemResourceImpl.java
> -	public WarehouseItem postWarehouseItemByExternalReferenceCode(
@marco-leo also about this I'm not 100% sure, but in the end I think the use case is well covered with other methods, plus this was very tricky and confusing.. Let me know what do you think about this. Thank you!

2019-11-20 15:43 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 9 minutes 2 seconds 167 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/aadc189412e470fb02505dd4f7f96c27ced41da4">aadc189412e470fb02505dd4f7f96c27ced41da4</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :x:<pre><code>     [echo] * What went wrong:
     [echo] Could not resolve all files for configuration ':apps:commerce:commerce-account-web:compileClasspath'.
     [echo] &gt; Could not download com.liferay.frontend.taglib.jar (com.liferay:com.liferay.frontend.taglib:3.2.0)
     [echo]    &gt; Could not get resource 'http://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.frontend.taglib/3.2.0/com.liferay.frontend.taglib-3.2.0.jar'.
     [echo]       &gt; Could not GET 'http://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.frontend.taglib/3.2.0/com.liferay.frontend.taglib-3.2.0.jar'. Received status code 522 from server: Unassigned
     [echo] 
     [echo] * Try:
     [echo] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [echo] 
     [echo] * Exception is:
     [echo] org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':apps:commerce:commerce-account-web:compileClasspath'.
     [echo] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1054)
     [echo] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1700(DefaultConfiguration.java:123)
     [echo] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:1028)
     [echo] 	at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:76)
     [echo] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.iterator(DefaultConfiguration.java:439)
     [echo] 	at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter$FileCollectionVisitorImpl.visitCollection(DefaultFileSystemSnapshotter.java:257)
     [echo] 	at org.gradle.api.internal.file.AbstractFileCollection.visitRootElements(AbstractFileCollection.java:282)
     [echo] 	at org.gradle.api.internal.file.CompositeFileCollection.visitRootElements(CompositeFileCollection.java:206)
     [echo] 	at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter.snapshot(DefaultFileSystemSnapshotter.java:142)
     [echo] 	at org.gradle.internal.fingerprint.impl.AbstractFileCollectionFingerprinter.fingerprint(AbstractFileCollectionFingerprinter.java:54)</code></pre></li><li>subrepository-semantic-versioning-jdk8 -  :x:<pre><code>subrepository-semantic-versioning-jdk8:
     [echo] Deleting stale baseline log files.
     [echo] Executing baseline on /opt/dev/projects/github/liferay-portal-7.1.x/modules/apps/commerce.
 [sync-dir] Synchronizing /opt/dev/projects/github/liferay-binaries-cache-2020/.gradle/caches/modules-2/files-2.1 into /opt/dev/projects/github/liferay-portal-7.1.x/.gradle/caches/modules-2/files-2.1
 [sync-dir] 0 files synchronized in 375ms
     [echo] ${gradle.output.error}
      [for] subrepository-semantic-versioning-jdk8: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:27: Subrepository task FAILED: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-test-batch.xml:5774: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-common.xml:859: exec returned: 1
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:120: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:13: Keepgoing execution: 2 of 3 iterations failed.
[beanshell] 4493 GitHub API calls out of 5000 remain. GitHub API call limit will reset in 43 minutes 2 seconds 804 ms.
[beanshell]     https://api.github.com/repos/liferay/com-liferay-commerce/pulls/1689
[beanshell] Executing commands: cat /tmp/-738020414.txt | mail -v -s "CI Failure has occurred" -r "ci_failure_notification" "qa-slave-verify-fail@liferay.com"
     [echo] A CI failure has occurred. QA Engineering has been notified. Please try again later or contact QA Engineering for an update.

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:11304: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:127: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:120: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:13: Keepgoing execution: 2 of 3 iterations failed.</code></pre></li><li>central-requirements-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/223//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>7 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/223//testReport">here</a>.</h5></div></html>

2019-11-22 10:42 UTC, andrea-ale-sbarra commented
@ethanbustad Sorry ethan, but I don't really understand these issues, please help me

2019-11-24 22:12 UTC, marco-leo commented
@andrea-ale-sbarra let's talk over those changes

2019-11-25 10:21 UTC, andrea-ale-sbarra commented
ci:test

2019-11-25 10:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/228/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-5.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/228/jenkins-report.html">here</a>.</b></p>

2019-11-25 10:23 UTC, andrea-ale-sbarra commented
@marco-leo I restored the post method and fixed the validation on that

2019-11-25 10:42 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 18 minutes 11 seconds 427 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/aadc189412e470fb02505dd4f7f96c27ced41da4">aadc189412e470fb02505dd4f7f96c27ced41da4</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :x:<pre><code>     [echo] * What went wrong:
     [echo] Execution failed for task ':apps:commerce:headless:headless-commerce:headless-commerce-admin-catalog-api:baseline'.
     [echo] &gt; Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal-7.1.x/tools/sdk/dist/com.liferay.headless.commerce.admin.catalog.api-5.0.0.jar against /opt/dev/projects/github/liferay-portal-7.1.x/.gradle/caches/modules-2/files-2.1/com.liferay.commerce/com.liferay.headless.commerce.admin.catalog.api/4.0.0/aefb6c0dd45bf4d09775bfa70fdbfb7187fb9779/com.liferay.headless.commerce.admin.catalog.api-4.0.0.jar
     [echo] 
     [echo] * Try:
     [echo] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [echo] 
     [echo] * Exception is:
     [echo] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:commerce:headless:headless-commerce:headless-commerce-admin-catalog-api:baseline'.
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
     [echo] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
     [echo] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
     [echo] 	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
     [echo] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)</code></pre></li><li>central-requirements-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/227//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>7 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/227//testReport">here</a>.</h5></div></html>

2019-11-25 13:56 UTC, marco-leo requested changes

2019-11-25 13:56 UTC, marco-leo commented on headless/headless-commerce/headless-commerce-admin-inventory-impl/src/main/java/com/liferay/headless/commerce/admin/inventory/internal/resource/v1_0/WarehouseItemResourceImpl.java
> +		Response.ResponseBuilder responseBuilder = Response.noContent();
Empty line

2019-11-25 14:04 UTC, andrea-ale-sbarra commented
ci:test

2019-11-25 14:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/113/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/113/jenkins-report.html">here</a>.</b></p>

2019-11-25 14:31 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 21 minutes 11 seconds 222 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/aadc189412e470fb02505dd4f7f96c27ced41da4">aadc189412e470fb02505dd4f7f96c27ced41da4</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [echo] java.lang.Exception: Found 388 formatting issues:
     [echo] 1: Incorrect dependency 'com.liferay.commerce.account.item.selector.api': ./commerce-account-group-admin-web/build.gradle 4 (SourceCheck:GradleDependencyArtifactsCheck)
     [echo] 2: Incorrect dependency 'com.liferay.commerce.account.item.selector.api': ./commerce-account-item-selector-web/build.gradle 4 (SourceCheck:GradleDependencyArtifactsCheck)
     [echo] 3: Incorrect dependency 'com.liferay.portal.spring.extender': ./commerce-account-service/build.gradle 10 (SourceCheck:GradleDependencyArtifactsCheck)
     [echo] 4: Illegal call to class 'com.liferay.portal.kernel.service.persistence.UserPersistence', see LPS-68923: ./commerce-account-service/src/main/java/com/liferay/commerce/account/service/impl/CommerceAccountUserRelLocalServiceImpl.java 149 (Checkstyle:PersistenceCallCheck)
     [echo] 5: Illegal call to class 'com.liferay.portal.kernel.service.persistence.RolePersistence', see LPS-68923: ./commerce-account-service/src/main/java/com/liferay/commerce/account/service/impl/CommerceAccountUserRelLocalServiceImpl.java 151 (Checkstyle:PersistenceCallCheck)
     [echo] 6: Incorrect dependency 'com.liferay.commerce.frontend.taglib': ./commerce-account-web/build.gradle 4 (SourceCheck:GradleDependencyArtifactsCheck)
     [echo] 7: Incorrect dependency 'com.liferay.commerce.admin.api': ./commerce-address-web/build.gradle 4 (SourceCheck:GradleDependencyArtifactsCheck)
     [echo] 8: Incorrect dependency 'com.liferay.commerce.admin.api': ./commerce-admin-web/build.gradle 4 (SourceCheck:GradleDependencyArtifactsCheck)
     [echo] 9: Incorrect dependency 'com.liferay.commerce.application.list': ./commerce-admin-web/build.gradle 5 (SourceCheck:GradleDependencyArtifactsCheck)
     [echo] 10: Incorrect dependency 'com.liferay.commerce.currency.api': ./commerce-api/build.gradle 5 (SourceCheck:GradleDependencyArtifactsCheck)
     [echo] 11: Incorrect dependency 'com.liferay.commerce.price.list.api': ./commerce-api/build.gradle 6 (SourceCheck:GradleDependencyArtifactsCheck)
     [echo] 12: Javadoc comment at column 0 has parse error. Details: no viable alternative at input '\t *' while parsing JAVADOC_TAG: ./commerce-api/src/main/java/com/liferay/commerce/payment/engine/CommercePaymentEngine.java 45 (Checkstyle:MissingDeprecatedCheck)</code></pre></li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/229//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>10 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/229//testReport">here</a>.</h5></div></html>

2019-11-25 19:31 UTC, ethanbustad commented
Hey @andrea-ale-sbarra, no problem, these are unusual errors :)

Any time you see something like `Could not GET 'http://repository-cdn.liferay.com`, it's just a network error in CI -- just execute the tests again.

2019-11-26 09:54 UTC, andrea-ale-sbarra commented
ci:test

2019-11-26 09:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/32/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/32/jenkins-report.html">here</a>.</b></p>

2019-11-26 10:39 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 41 minutes 1 second 492 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/5b86c10206c81d4fee3a4270b3ef98cd5b2e6357">5b86c10206c81d4fee3a4270b3ef98cd5b2e6357</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [exec] java.lang.Exception: Found 4 formatting issues:
     [exec] 1: No need to pass default value '0': ./headless/headless-commerce/headless-commerce-admin-inventory-impl/src/main/java/com/liferay/headless/commerce/admin/inventory/internal/resource/v1_0/WarehouseItemResourceImpl.java 226 (SourceCheck:GetterUtilCheck)
     [exec] 2: No need to pass default value '0': ./headless/headless-commerce/headless-commerce-admin-inventory-impl/src/main/java/com/liferay/headless/commerce/admin/inventory/internal/resource/v1_0/WarehouseItemResourceImpl.java 253 (SourceCheck:GetterUtilCheck)
     [exec] 3: &gt; 80: ./headless/headless-commerce/headless-commerce-admin-inventory-impl/src/main/java/com/liferay/headless/commerce/admin/inventory/internal/resource/v1_0/WarehouseItemResourceImpl.java 342 (SourceCheck:JavaLongLinesCheck)
     [exec] 4: ./headless/headless-commerce/headless-commerce-admin-inventory-impl/src/main/java/com/liferay/headless/commerce/admin/inventory/internal/resource/v1_0/WarehouseItemResourceImpl.java expected:&lt;...WarehouseItemId());
     [exec] []
     [exec] 		Response.Response...&gt; but was:&lt;...WarehouseItemId());
     [exec] [		]
     [exec] 		Response.Response...&gt;
     [exec] 
     [exec] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:438)
     [exec] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:266)
     [exec] 
     [exec] &gt; Task :checkSourceFormatting FAILED
     [exec] 1 actionable task: 1 executed
     [exec] Gradle build finished at 2019-11-26 10:37:39.236.
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':checkSourceFormatting'.
     [exec] &gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':checkSourceFormatting'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)</code></pre></li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-13.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/104//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>18 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-13.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/104//testReport">here</a>.</h5></div></html>

2019-11-26 11:42 UTC, andrea-ale-sbarra commented
ci:test

2019-11-26 11:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/167/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/167/jenkins-report.html">here</a>.</b></p>

2019-11-26 12:16 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 30 minutes 29 seconds 975 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/5b86c10206c81d4fee3a4270b3ef98cd5b2e6357">5b86c10206c81d4fee3a4270b3ef98cd5b2e6357</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-19.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/149//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>18 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-19.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/149//testReport">here</a>.</h5></div></html>

2019-11-26 13:25 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:default - 11 out of 13 jobs passed in 1 hour 42 minutes 55 seconds 546 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/5b86c10206c81d4fee3a4270b3ef98cd5b2e6357">5b86c10206c81d4fee3a4270b3ef98cd5b2e6357</a></p><details><summary><strong>ci:test:default - 11 out of 13 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-6.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/167/"><strike><strong>test-subrepository-acceptance-pullrequest(7.1.x)</strong></strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/643/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</strong></strike></a></li></ul></div><details><summary><strong>11 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/642/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/423/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/424/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/421/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/422/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/426/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/644/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/425/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/645/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/97/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-19.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/149/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details></details><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/167/jenkins-report.html">here</a>.</h5><hr/><h4>Failures (upstream comparison is not available):</h4><ol><li><div><h5><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/643/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</a></h5><div><h6>Job Results:</h6><p>1 Test Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/643//consoleText">AXIS_VARIABLE=0,label_exp=!master #643</a><ol><li><div><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/643//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CommerceFrontStore_ViewStoreFrontSimpleProduct_">LocalFile.CommerceFrontStore#ViewStoreFrontSimpleProduct</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-6/1574768605067/test-subrepository-acceptance-pullrequest(7.1.x)/167/subrepository-functional-tomcat90-mysql57-jdk8/6/0/LocalFile.CommerceFrontStore_ViewStoreFrontSimpleProduct/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-6/1574768605067/test-subrepository-acceptance-pullrequest(7.1.x)/167/subrepository-functional-tomcat90-mysql57-jdk8/6/0/LocalFile.CommerceFrontStore_ViewStoreFrontSimpleProduct/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-6/1574768605067/test-subrepository-acceptance-pullrequest(7.1.x)/167/subrepository-functional-tomcat90-mysql57-jdk8/6/0/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li></ol></details></html>

2019-11-26 16:02 UTC, merged