COMMERCE-2495 Added coupon code taglib
liferay/com-liferay-commerce pull request #1723
Opened 2019-12-02 10:28 UTC by Commando18

2019-12-02 10:28 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2019-12-02 10:28 UTC, Commando18 commented
ci:test

2019-12-02 10:28 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/157/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-17.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/157/jenkins-report.html">here</a>.</b></p>

2019-12-02 11:10 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 30 minutes 42 seconds 23 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/feac275e7002a6c87d8f088d2f7d95946156c206">feac275e7002a6c87d8f088d2f7d95946156c206</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-10.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/47//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>18 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-10.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/47//testReport">here</a>.</h5></div></html>

2019-12-02 11:13 UTC, marco-leo requested changes

2019-12-02 11:13 UTC, marco-leo commented on commerce-frontend-impl/src/main/java/com/liferay/commerce/frontend/internal/cart/CommerceCartResource.java
> +	public Response getOrder(
getOrder?

2019-12-02 11:13 UTC, marco-leo commented on commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/CouponCodeTag.java
> +			_commerceOrder = commerceContext.getCommerceOrder();
pass order Id by taglib parameter

2019-12-02 11:13 UTC, marco-leo commented on commerce-frontend-taglib/src/main/resources/META-INF/resources/coupon_code/page.jsp
> +			A.one('#<portlet:namespace />couponCodeIconRemove').on(
avoid usage of Alloy

2019-12-02 12:12 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:default - 10 out of 13 jobs passed in 1 hour 44 minutes 4 seconds 983 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/feac275e7002a6c87d8f088d2f7d95946156c206">feac275e7002a6c87d8f088d2f7d95946156c206</a></p><details><summary><strong>ci:test:default - 10 out of 13 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/157/"><strike><strong>test-subrepository-acceptance-pullrequest(7.1.x)</strong></strike></a></li><li><a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/615/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</strong></strike></a></li><li><a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/616/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</strong></strike></a></li></ul></div><details><summary><strong>10 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/730/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/731/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/614/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/729/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/919/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/732/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/731/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/920/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/87/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-10.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/47/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details></details><h5>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/157/jenkins-report.html">here</a>.</h5><hr/><h4>Failures (upstream comparison is not available):</h4><ol><li><div><h5><a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/615/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</a></h5><div><h6>Job Results:</h6><p>1 Test Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/615//consoleText">AXIS_VARIABLE=0,label_exp=!master #615</a><ol><li><div><a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/615//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CommerceFrontStore_ViewStoreFrontSimpleProduct_">LocalFile.CommerceFrontStore#ViewStoreFrontSimpleProduct</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-17/1575282528932/test-subrepository-acceptance-pullrequest(7.1.x)/157/subrepository-functional-tomcat90-mysql57-jdk8/6/0/LocalFile.CommerceFrontStore_ViewStoreFrontSimpleProduct/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-17/1575282528932/test-subrepository-acceptance-pullrequest(7.1.x)/157/subrepository-functional-tomcat90-mysql57-jdk8/6/0/LocalFile.CommerceFrontStore_ViewStoreFrontSimpleProduct/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-17/1575282528932/test-subrepository-acceptance-pullrequest(7.1.x)/157/subrepository-functional-tomcat90-mysql57-jdk8/6/0/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li><li><div><h5><a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/616/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>3 Tests Failed.</p></div><ol><li><div><a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/616//consoleText">AXIS_VARIABLE=0,label_exp=!master #616</a><div><p>Please fix <strong>semantic versioning</strong> on <strong><a href="https://github.com/Commando18/com-liferay-commerce/tree/COMMERCE-2495">Commando18/COMMERCE-2495</a></strong><pre><code>     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.trash.kernel.service.persistence       CHANGED    1.1.0      1.1.0      1.1.1      VERSION INCREASE REQUIRED
     [exec] 	~   class      com.liferay.trash.kernel.service.persistence.TrashEntryUtil
     [exec] 		+   annotated  aQute.bnd.annotation.ProviderType
     [exec] 	~   class      com.liferay.trash.kernel.service.persistence.TrashVersionUtil
     [exec] 		+   annotated  aQute.bnd.annotation.ProviderType
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal-7.1.x/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal-7.1.x/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/2.126.0/69bd50c1ebacc90c2ad5fe8a37ff11b214c9729/com.liferay.portal.kernel-2.126.0.jar</code></pre></p></div></div></li><li><div><a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=1,label_exp=!master/616//consoleText">AXIS_VARIABLE=1,label_exp=!master #616</a><div><p>Please fix <strong>semantic versioning</strong> on <strong><a href="https://github.com/Commando18/com-liferay-commerce/tree/COMMERCE-2495">Commando18/COMMERCE-2495</a></strong><pre><code>     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.trash.kernel.service.persistence       CHANGED    1.1.0      1.1.0      1.1.1      VERSION INCREASE REQUIRED
     [exec] 	~   class      com.liferay.trash.kernel.service.pe [...]

2019-12-02 14:35 UTC, Commando18 commented on commerce-frontend-impl/src/main/java/com/liferay/commerce/frontend/internal/cart/CommerceCartResource.java
> +	public Response getOrder(
Changed in applyCouponCode

2019-12-02 14:35 UTC, Commando18 commented on commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/CouponCodeTag.java
> +			_commerceOrder = commerceContext.getCommerceOrder();
Did it, thanks

2019-12-02 14:35 UTC, Commando18 commented on commerce-frontend-taglib/src/main/resources/META-INF/resources/coupon_code/page.jsp
> +			A.one('#<portlet:namespace />couponCodeIconRemove').on(
Did it aswell

2019-12-02 14:35 UTC, Commando18 commented
ci:test

2019-12-02 14:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/84/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/84/jenkins-report.html">here</a>.</b></p>

2019-12-02 14:51 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 7 minutes 31 seconds 175 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/847031134a89198c8b3e676882ea81882bc0e833">847031134a89198c8b3e676882ea81882bc0e833</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :x:<pre><code>subrepository-compile-jdk8
   [delete] Deleting: /opt/dev/projects/github/liferay-portal-7.1.x/null612770556.properties

subrepository-compile-jdk8:
 [sync-dir] Synchronizing /opt/dev/projects/github/liferay-binaries-cache-2020/.gradle/caches/modules-2/files-2.1 into /opt/dev/projects/github/liferay-portal-7.1.x/.gradle/caches/modules-2/files-2.1
 [sync-dir] 0 files synchronized in 296ms
      [for] subrepository-compile-jdk8: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:27: Subrepository task FAILED: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-test-batch.xml:5738: The following error occurred while executing this line:
      [for] /opt/dev/projects/github/liferay-portal-7.1.x/build-common.xml:859: exec returned: 1
     [echo] </code></pre></li><li>subrepository-semantic-versioning-jdk8 -  :x:<pre><code>[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498)
[beanshell] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[beanshell] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[beanshell] 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
[beanshell] 	at net.sf.antcontrib.logic.TryCatchTask$CatchBlock.execute(TryCatchTask.java:137)
[beanshell] 	at net.sf.antcontrib.logic.TryCatchTask.execute(TryCatchTask.java:225)
[beanshell] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[beanshell] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498)
[beanshell] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[beanshell] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[beanshell] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[beanshell] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[beanshell] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
[beanshell] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
[beanshell] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[beanshell] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
[beanshell] 	at org.apache.tools.ant.Main.runBuild(Main.java:851)
[beanshell] 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
[beanshell] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
[beanshell] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
     [echo] A CI failure has occurred. QA Engineering has been notified. Please try again later or contact QA Engineering for an update.

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:11314: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:127: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:120: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-acceptance-validation.xml:13: Keepgoing execution: 2 of 3 iterations failed.</code></pre></li><li>central-requirements-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/258//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>7 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/258//testReport">here</a>.</h5></div></html>

2019-12-03 05:18 UTC, ethanbustad commented
ci:test

2019-12-03 05:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/170/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/170/jenkins-report.html">here</a>.</b></p>

2019-12-03 06:00 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 32 minutes 30 seconds 198 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/62b896bab8a7f1b755b0f0b108253a24deaf8cf0">62b896bab8a7f1b755b0f0b108253a24deaf8cf0</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/136//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>18 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/136//testReport">here</a>.</h5></div></html>

2019-12-03 07:05 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:default - 10 out of 13 jobs passed in 1 hour 46 minutes 44 seconds 61 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/62b896bab8a7f1b755b0f0b108253a24deaf8cf0">62b896bab8a7f1b755b0f0b108253a24deaf8cf0</a></p><details><summary><strong>ci:test:default - 10 out of 13 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/170/"><strike><strong>test-subrepository-acceptance-pullrequest(7.1.x)</strong></strike></a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/872/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</strong></strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/667/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</strong></strike></a></li></ul></div><details><summary><strong>10 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/871/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/870/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/665/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/663/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/664/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/1026/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/666/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/1025/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/37/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/136/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details></details><h5>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/170/jenkins-report.html">here</a>.</h5><hr/><h4>Failures (upstream comparison is not available):</h4><ol><li><div><h5><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/872/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</a></h5><div><h6>Job Results:</h6><p>1 Test Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/872//consoleText">AXIS_VARIABLE=0,label_exp=!master #872</a><ol><li><div><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/872//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CommerceFrontStore_ViewStoreFrontSimpleProduct_">LocalFile.CommerceFrontStore#ViewStoreFrontSimpleProduct</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-16/1575350366088/test-subrepository-acceptance-pullrequest(7.1.x)/170/subrepository-functional-tomcat90-mysql57-jdk8/6/0/LocalFile.CommerceFrontStore_ViewStoreFrontSimpleProduct/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-16/1575350366088/test-subrepository-acceptance-pullrequest(7.1.x)/170/subrepository-functional-tomcat90-mysql57-jdk8/6/0/LocalFile.CommerceFrontStore_ViewStoreFrontSimpleProduct/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-16/1575350366088/test-subrepository-acceptance-pullrequest(7.1.x)/170/subrepository-functional-tomcat90-mysql57-jdk8/6/0/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li><li><div><h5><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/667/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>3 Tests Failed.</p></div><ol><li><div><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/667//consoleText">AXIS_VARIABLE=0,label_exp=!master #667</a><pre><code>     [exec] * Where:
     [exec] Build file '/opt/dev/projects/github/liferay-portal-7.1.x/modules/dxp/apps/commerce/build.gradle' line: 15
     [exec] 
     [exec] * What went wrong:
     [exec] A problem occurred evaluating project ':dxp:apps:commerce'.
     [exec] &gt; Failed to apply plugin [class 'com.liferay.gradle.plugins.defaults.LiferayDefaultsPlugin']
     [exec]    &gt; Please run the following command to setup the build profile for DXP:
     [exec]      /opt/dev/projects/github/liferay-portal-7.1.x$ ant setup-profile-dxp
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.GradleScriptException: A problem occurred evaluating project ':dxp:apps:commerce'.
     [exec] 	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
     [exec] 	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:227)
     [exec] 	at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
     [exec] 	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:232)
     [exec] 	at org.gradle.configuration.BuildOperationScriptPlugin$1$1.run(BuildOperationScriptPlugin.java:69)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
     [exec] 	at org. [...]

2019-12-05 16:25 UTC, marco-leo commented
@gianmarcobrunialti this should be transformed in a InfoRenderComponent

2019-12-05 16:25 UTC, merged

2019-12-05 22:04 UTC, gianmarcobrunialti commented
@marco-leo Alright.