Commerce 2525
liferay/com-liferay-commerce pull request #1766
Opened 2019-12-06 14:02 UTC by riccardo-ferrari

2019-12-06 14:02 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2019-12-06 14:02 UTC, riccardo-ferrari commented
ci:test

2019-12-06 14:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/174/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/174/jenkins-report.html">here</a>.</b></p>

2019-12-06 14:39 UTC, marco-leo requested changes

2019-12-06 14:39 UTC, marco-leo commented on commerce-product-service/src/main/java/com/liferay/commerce/product/internal/model/listener/LayoutModelListener.java
> +			_cpDisplayLayoutLocalService.deleteCPDisplayLayout(cpDisplayLayout);
@riccardo-ferrari when we use finders autogenerated from service builder, it autogenerates a method to delete by too. We can expose that method instead, so we avoid to fetch and cycle

2019-12-06 14:39 UTC, marco-leo commented on commerce-product-service/src/main/java/com/liferay/commerce/product/internal/upgrade/v1_11_1/CPDisplayLayoutUpgradeProcess.java
> +		CPDisplayLayoutLocalService cpDisplayLayoutLocalService,
can't inject this service, as it will create dependency and the module won't start

2019-12-06 14:39 UTC, marco-leo commented on commerce-product-service/src/main/java/com/liferay/commerce/product/internal/upgrade/v1_11_1/CPDisplayLayoutUpgradeProcess.java
> +		List<CPDisplayLayout> cpDisplayLayouts =
need to substitute this with a SQL query

2019-12-06 14:39 UTC, marco-leo commented on commerce-product-service/src/main/java/com/liferay/commerce/product/internal/upgrade/v1_11_1/CPDisplayLayoutUpgradeProcess.java
> +				_cpDisplayLayoutLocalService.deleteCPDisplayLayout(
Need to substitute this with a SQL query

2019-12-06 14:39 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 29 minutes 50 seconds 2 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/f0b7efb7cc11c6a0608e39e4bc47272b0ff77e9e">f0b7efb7cc11c6a0608e39e4bc47272b0ff77e9e</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/175//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>18 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/175//testReport">here</a>.</h5></div></html>

2019-12-06 15:46 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:default - 4 out of 13 jobs passed in 1 hour 43 minutes 992 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/f0b7efb7cc11c6a0608e39e4bc47272b0ff77e9e">f0b7efb7cc11c6a0608e39e4bc47272b0ff77e9e</a></p><details><summary><strong>ci:test:default - 4 out of 13 jobs PASSED</strong></summary><div><h4>9 Failed Jobs:</h4><ul><li><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/174/"><strike><strong>test-subrepository-acceptance-pullrequest(7.1.x)</strong></strike></a></li><li><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/890/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/889/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/838/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</strong></strike></a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/756/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</strong></strike></a></li><li><a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/809/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</strong></strike></a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/755/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</strong></strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/615/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</strong></strike></a></li><li><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/1129/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</strong></strike></a></li></ul></div><details><summary><strong>4 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/808/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/1128/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/68/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/175/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details></details><h5>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/174/jenkins-report.html">here</a>.</h5><hr/><h4>Failures (upstream comparison is not available):</h4><ol><li><div><h5><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/890/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/890//consoleText">AXIS_VARIABLE=0,label_exp=!master #890</a><pre><code>     [exec] * What went wrong:
     [exec] Project directory '/opt/dev/projects/github/liferay-portal-7.1.x/modules/dxp/apps/commerce' is not part of the build defined by settings file '/opt/dev/projects/github/liferay-portal-7.1.x/modules/settings.gradle'. If this is an unrelated build, it must have its own settings file.
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.InvalidUserDataException: Project directory '/opt/dev/projects/github/liferay-portal-7.1.x/modules/dxp/apps/commerce' is not part of the build defined by settings file '/opt/dev/projects/github/liferay-portal-7.1.x/modules/settings.gradle'. If this is an unrelated build, it must have its own settings file.
     [exec] 	at org.gradle.initialization.AbstractProjectSpec.selectProject(AbstractProjectSpec.java:42)
     [exec] 	at org.gradle.initialization.DefaultSettingsLoader.setDefaultProject(DefaultSettingsLoader.java:88)
     [exec] 	at org.gradle.initialization.DefaultSettingsLoader.findAndLoadSettings(DefaultSettingsLoader.java:52)
     [exec] 	at org.gradle.initialization.SettingsAttachingSettingsLoader.findAndLoadSettings(SettingsAttachingSettingsLoader.java:35)
     [exec] 	at org.gradle.internal.composite.CommandLineIncludedBuildSettingsLoader.findAndLoadSettings(CommandLineIncludedBuildSettingsLoader.java:34)
     [exec] 	at org.gradle.internal.composite.ChildBuildRegisteringSettingsLoader.findAndLoadSettings(ChildBuildRegisteringSettingsLoader.java:47)
     [exec] 	at org.gradle.internal.composite.CompositeBuildSettingsLoader.findAndLoadSettings(CompositeBuildSettingsLoader.java:35)
     [exec] 	at org.gradle.initialization.DefaultSettingsPreparer.prepareSettings(DefaultSettingsPreparer.java:36)
     [exec] 	at org.gradle.initialization.BuildOperatingFiringSettingsPreparer$LoadBuild.doLoadBuild(BuildOperatingFiringSettingsPreparer.java:59)
     [exec] 	at org.gradle.initialization.BuildOperatingFiringSettingsPreparer$LoadBuild.run(BuildOperatingFiringSettingsPreparer.java:54)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)</code></pre></div></li></ol></div></li><li><div><h5><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/889/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/889//consoleText">AXIS_VARIABLE=0,label_exp=!master #889</a><pre><code>     [exec] * What went wrong:
     [exec] Project directory '/opt/dev/projects/github/liferay-portal-7.1.x/modules/dxp/apps/commerce' is not part of the build defined by settings file '/opt/dev/projects/github/liferay-portal-7.1.x/modules/settings.gradle'. If this is an unrelated build, it must have its own settings file.
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.InvalidUserDataException: Project directory '/opt/dev/pro [...]

2019-12-06 23:36 UTC, riccardo-ferrari commented
redirected

2019-12-06 23:36 UTC, closed without merging

2019-12-09 19:08 UTC, ethanbustad commented
Sent to https://github.com/liferay/com-liferay-commerce/pull/1777.