Commerce 2369 Shipment Refactor
liferay/com-liferay-commerce pull request #1771
Opened 2019-12-06 15:47 UTC by alecsloan

2019-12-06 15:47 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2019-12-06 15:51 UTC, alecsloan commented
ci:test

2019-12-06 15:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/215/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-20.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/215/jenkins-report.html">here</a>.</b></p>

2019-12-06 16:11 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 12 minutes 50 seconds 693 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/3f56476a9113411925a1cf0d98f23dc25c201c3c">3f56476a9113411925a1cf0d98f23dc25c201c3c</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :x:<pre><code>     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:commerce:commerce-api:baseline'.
     [exec] &gt; Could not resolve all files for configuration ':apps:commerce:commerce-api:baseline'.
     [exec]    &gt; Could not resolve com.liferay.commerce:com.liferay.commerce.api:(,10.0.0).
     [exec]      Required by:
     [exec]          project :apps:commerce:commerce-api
     [exec]       &gt; Failed to list versions for com.liferay.commerce:com.liferay.commerce.api.
     [exec]          &gt; Unable to load Maven meta-data from http://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/commerce/com.liferay.commerce.api/maven-metadata.xml.
     [exec]             &gt; Could not get resource 'http://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/commerce/com.liferay.commerce.api/maven-metadata.xml'.
     [exec]                &gt; Could not GET 'http://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/commerce/com.liferay.commerce.api/maven-metadata.xml'.
     [exec]                   &gt; squid.lax.liferay.com: Name or service not known
     [exec]       &gt; Failed to list versions for com.liferay.commerce:com.liferay.commerce.api.
     [exec]          &gt; Unable to load Maven meta-data from http://repository-cdn.liferay.com/nexus/service/local/repo_groups/private/content/com/liferay/commerce/com.liferay.commerce.api/maven-metadata.xml.
     [exec]             &gt; Could not get resource 'http://repository-cdn.liferay.com/nexus/service/local/repo_groups/private/content/com/liferay/commerce/com.liferay.commerce.api/maven-metadata.xml'.
     [exec]                &gt; Could not GET 'http://repository-cdn.liferay.com/nexus/service/local/repo_groups/private/content/com/liferay/commerce/com.liferay.commerce.api/maven-metadata.xml'.
     [exec]                   &gt; squid.lax.liferay.com
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:commerce:commerce-api:baseline'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
     [exec] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)</code></pre></li><li>central-requirements-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/176//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>7 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/176//testReport">here</a>.</h5></div></html>

2019-12-06 19:24 UTC, marco-leo commented
ci:test

2019-12-06 19:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/176/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/176/jenkins-report.html">here</a>.</b></p>

2019-12-06 19:52 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 25 minutes 41 seconds 753 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/3f56476a9113411925a1cf0d98f23dc25c201c3c">3f56476a9113411925a1cf0d98f23dc25c201c3c</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/179//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>18 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/179//testReport">here</a>.</h5></div></html>

2019-12-06 20:53 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:default - 4 out of 13 jobs passed in 1 hour 29 minutes 517 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/3f56476a9113411925a1cf0d98f23dc25c201c3c">3f56476a9113411925a1cf0d98f23dc25c201c3c</a></p><details><summary><strong>ci:test:default - 4 out of 13 jobs PASSED</strong></summary><div><h4>9 Failed Jobs:</h4><ul><li><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/176/"><strike><strong>test-subrepository-acceptance-pullrequest(7.1.x)</strong></strike></a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/884/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/847/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/848/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</strong></strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/616/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</strong></strike></a></li><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/637/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</strong></strike></a></li><li><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/849/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</strong></strike></a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/760/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</strong></strike></a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/885/"><strike><strong>test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</strong></strike></a></li></ul></div><details><summary><strong>4 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/895/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/811/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/87/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/179/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details></details><h5>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/176/jenkins-report.html">here</a>.</h5><hr/><h4>Failures (upstream comparison is not available):</h4><ol><li><div><h5><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/884/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/884//consoleText">AXIS_VARIABLE=0,label_exp=!master #884</a><pre><code>     [exec] * What went wrong:
     [exec] Project directory '/opt/dev/projects/github/liferay-portal-7.1.x/modules/dxp/apps/commerce' is not part of the build defined by settings file '/opt/dev/projects/github/liferay-portal-7.1.x/modules/settings.gradle'. If this is an unrelated build, it must have its own settings file.
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.InvalidUserDataException: Project directory '/opt/dev/projects/github/liferay-portal-7.1.x/modules/dxp/apps/commerce' is not part of the build defined by settings file '/opt/dev/projects/github/liferay-portal-7.1.x/modules/settings.gradle'. If this is an unrelated build, it must have its own settings file.
     [exec] 	at org.gradle.initialization.AbstractProjectSpec.selectProject(AbstractProjectSpec.java:42)
     [exec] 	at org.gradle.initialization.DefaultSettingsLoader.setDefaultProject(DefaultSettingsLoader.java:88)
     [exec] 	at org.gradle.initialization.DefaultSettingsLoader.findAndLoadSettings(DefaultSettingsLoader.java:52)
     [exec] 	at org.gradle.initialization.SettingsAttachingSettingsLoader.findAndLoadSettings(SettingsAttachingSettingsLoader.java:35)
     [exec] 	at org.gradle.internal.composite.CommandLineIncludedBuildSettingsLoader.findAndLoadSettings(CommandLineIncludedBuildSettingsLoader.java:34)
     [exec] 	at org.gradle.internal.composite.ChildBuildRegisteringSettingsLoader.findAndLoadSettings(ChildBuildRegisteringSettingsLoader.java:47)
     [exec] 	at org.gradle.internal.composite.CompositeBuildSettingsLoader.findAndLoadSettings(CompositeBuildSettingsLoader.java:35)
     [exec] 	at org.gradle.initialization.DefaultSettingsPreparer.prepareSettings(DefaultSettingsPreparer.java:36)
     [exec] 	at org.gradle.initialization.BuildOperatingFiringSettingsPreparer$LoadBuild.doLoadBuild(BuildOperatingFiringSettingsPreparer.java:59)
     [exec] 	at org.gradle.initialization.BuildOperatingFiringSettingsPreparer$LoadBuild.run(BuildOperatingFiringSettingsPreparer.java:54)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)</code></pre></div></li></ol></div></li><li><div><h5><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/847/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>0 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/AXIS_VARIABLE=0,label_exp=!master/847//consoleText">AXIS_VARIABLE=0,label_exp=!master #847</a><pre><code>     [exec] * What went wrong:
     [exec] Project directory '/opt/dev/projects/github/liferay-portal-7.1.x/modules/dxp/apps/commerce' is not part of the build defined by settings file '/opt/dev/projects/github/liferay-portal-7.1.x/modules/settings.gradle'. If this is an unrelated build, it must have its own settings file.
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.InvalidUserDataException: Project directory '/opt/dev/projects/ [...]

2019-12-09 23:17 UTC, marco-leo commented
ci:test

2019-12-09 23:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/142/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/142/jenkins-report.html">here</a>.</b></p>

2019-12-10 00:08 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 25 minutes 38 seconds 322 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/85f2c7e8024baf7017deca5b0d79f567fd084807">85f2c7e8024baf7017deca5b0d79f567fd084807</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :x:<pre><code>     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:commerce:commerce-frontend-taglib:npmInstall'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal-7.1.x/modules/apps/commerce/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:commerce:commerce-frontend-taglib:npmInstall'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
     [exec] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
     [exec] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
     [exec] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
     [exec] 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
     [exec] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)</code></pre></li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/144//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>7 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-7.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/144//testReport">here</a>.</h5></div></html>

2019-12-10 01:05 UTC, ethanbustad requested changes

2019-12-10 01:05 UTC, ethanbustad commented on commerce-shipment-web/src/main/resources/META-INF/resources/shipment_action.jsp
> +						width: 450
sort, please :)

2019-12-10 01:05 UTC, ethanbustad commented on commerce-shipment-web/src/main/resources/META-INF/resources/shipment_item_action.jsp
> +						width: 450
same here, and I assume also the following edited JSPs

2019-12-10 01:05 UTC, ethanbustad commented on commerce-shipment-web/src/main/resources/content/Language.properties
> +order-ids=Order Ids
`d` should be capitalized -- `Order IDs`

2019-12-10 01:05 UTC, ethanbustad commented on commerce-test/src/testIntegration/java/com/liferay/commerce/shipment/test/CommerceShipmentItemTest.java
> +		CommerceCurrency commerceCurrency =
I think this needs to be cleaned up

2019-12-10 01:05 UTC, ethanbustad commented on commerce-test/src/testIntegration/java/com/liferay/commerce/shipment/test/CommerceShipmentItemTest.java
> +			"That shipment should contain the shipment Item"
`Shipment Item` for consistency (instead of `shipment Item`)

2019-12-11 18:03 UTC, ethanbustad commented
Rebased, made the requested changes, and sent along to https://github.com/liferay/com-liferay-commerce/pull/1791.

2019-12-11 18:03 UTC, closed without merging