COMMERCE-553 Default image config
liferay/com-liferay-commerce pull request #505
Opened 2019-01-31 01:37 UTC by ethanbustad

2019-01-31 01:37 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2019-01-31 01:38 UTC, ethanbustad commented
ci:test

2019-01-31 01:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/110/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/110/jenkins-report.html">here</a>.</b></p>

2019-01-31 02:02 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 21 minutes 3 seconds 654 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/6679b2b8fa87ba7cbf57f26b9c565b5c970e7f3c">6679b2b8fa87ba7cbf57f26b9c565b5c970e7f3c</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :x:<pre><code>Test failures detected. See below for details.</code></pre></li></ul><h5>For full console, click <a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/87//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>14 Tests Passed.<br/>2 Tests Failed.</p></div></div><ol><li><div><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/87//testReport/com.liferay.portal.modules/ModulesStructureTest/testScanIgnoreFiles">ModulesStructureTest.testScanIgnoreFiles</a><pre><code>junit.framework.AssertionFailedError: Forbidden "**/docroot/WEB-INF/tld/" in modules/apps/analytics/.gitignore
	at com.liferay.portal.modules.ModulesStructureTest._testGitIgnoreFile(ModulesStructureTest.java:947)
	at com.liferay.portal.modules.ModulesStructureTest.access$1100(ModulesStructureTest.java:67)
	at com.liferay.portal.modules.ModulesStructureTest$4.visitFile(ModulesStructureTest.java:406)
	at com.liferay.portal.modules.ModulesStructureTest$4.visitFile(ModulesStructureTest.java:360)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.modules.ModulesStructureTest.testScanIgnoreFiles(ModulesStructureTest.java:358)
</code></pre></div></li><li><div><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/87//testReport/com.liferay.portal.modules/ModulesStructureTest/testScanBuildScripts">ModulesStructureTest.testScanBuildScripts</a><pre><code>junit.framework.AssertionFailedError: Forbidden modules/apps/analytics/gradle.properties
	at com.liferay.portal.modules.ModulesStructureTest$1.preVisitDirectory(ModulesStructureTest.java:173)
	at com.liferay.portal.modules.ModulesStructureTest$1.preVisitDirectory(ModulesStructureTest.java:123)
	at java.nio.file.Files.walkFileTree(Files.java:2677)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.modules.ModulesStructureTest.testScanBuildScripts(ModulesStructureTest.java:121)
</code></pre></div></li></ol><h5>For all test results, click <a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/87//testReport">here</a>.</h5></div></html>

2019-01-31 16:48 UTC, ethanbustad commented
ci:test

2019-01-31 16:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/16/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/16/jenkins-report.html">here</a>.</b></p>

2019-01-31 17:15 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 24 minutes 11 seconds 181 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/6679b2b8fa87ba7cbf57f26b9c565b5c970e7f3c">6679b2b8fa87ba7cbf57f26b9c565b5c970e7f3c</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :x:<pre><code>Test failures detected. See below for details.</code></pre></li></ul><h5>For full console, click <a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/45//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>14 Tests Passed.<br/>2 Tests Failed.</p></div></div><ol><li><div><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/45//testReport/com.liferay.portal.modules/ModulesStructureTest/testScanIgnoreFiles">ModulesStructureTest.testScanIgnoreFiles</a><pre><code>junit.framework.AssertionFailedError: Forbidden "**/docroot/WEB-INF/tld/" in modules/apps/apio-architect/.gitignore
	at com.liferay.portal.modules.ModulesStructureTest._testGitIgnoreFile(ModulesStructureTest.java:947)
	at com.liferay.portal.modules.ModulesStructureTest.access$1100(ModulesStructureTest.java:67)
	at com.liferay.portal.modules.ModulesStructureTest$4.visitFile(ModulesStructureTest.java:406)
	at com.liferay.portal.modules.ModulesStructureTest$4.visitFile(ModulesStructureTest.java:360)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.modules.ModulesStructureTest.testScanIgnoreFiles(ModulesStructureTest.java:358)
</code></pre></div></li><li><div><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/45//testReport/com.liferay.portal.modules/ModulesStructureTest/testScanBuildScripts">ModulesStructureTest.testScanBuildScripts</a><pre><code>junit.framework.AssertionFailedError: Forbidden modules/apps/apio-architect/gradle.properties
	at com.liferay.portal.modules.ModulesStructureTest$1.preVisitDirectory(ModulesStructureTest.java:173)
	at com.liferay.portal.modules.ModulesStructureTest$1.preVisitDirectory(ModulesStructureTest.java:123)
	at java.nio.file.Files.walkFileTree(Files.java:2677)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.modules.ModulesStructureTest.testScanBuildScripts(ModulesStructureTest.java:121)
</code></pre></div></li></ol><h5>For all test results, click <a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/45//testReport">here</a>.</h5></div></html>

2019-01-31 21:39 UTC, alecsloan commented
@nealrobbins Looping you in so you can know when this is merged in.

2019-01-31 23:43 UTC, marco-leo commented
@nealrobbins This will add the default image concept please document it

2019-01-31 23:58 UTC, marco-leo requested changes
We should change all initializer as well like breccia to add this default image configurator

2019-01-31 23:58 UTC, marco-leo commented on commerce-media-api/build.gradle
> +	compileOnly project(":apps:commerce:commerce-api")
@alecsloan  We can't add this dependency because we are implicitly creating a dependency between commerce-api and commerce-product-x modules

2019-02-01 16:57 UTC, nealrobbins commented
> @nealrobbins This will add the default image concept please document it

Got it, thanks.

2019-02-01 17:52 UTC, alecsloan commented
@marco-leo @nealrobbins @ethanbustad new pull (#513) reflects changes

2019-02-01 19:13 UTC, closed without merging