COMMERCE-819 Move commerceMediaDefaultImageConfiguration to internal
liferay/com-liferay-commerce pull request #576
Opened 2019-02-19 23:55 UTC by alecsloan

Let me know if you have any questions.

2019-02-19 23:55 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2019-02-19 23:55 UTC, alecsloan commented
ci:test

2019-02-19 23:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/70/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/70/jenkins-report.html">here</a>.</b></p>

2019-02-19 23:58 UTC, alecsloan commented
Force push reflects ticket number change. Should be COMMERCE-553 not COMMERE-819

2019-02-20 00:09 UTC, ethanbustad requested changes

2019-02-20 00:09 UTC, ethanbustad commented on commerce-media-impl/bnd.bnd
> +Export-Package: com.liferay.commerce.media.impl
no need to export

2019-02-20 00:09 UTC, ethanbustad commented on commerce-media-impl/src/main/java/com/liferay/commerce/media/impl/CatalogCommerceMediaDefaultImage.java
> +package com.liferay.commerce.media.impl;
move to internal package

2019-02-20 00:09 UTC, ethanbustad commented on commerce-media-api/src/main/java/com/liferay/commerce/media/CommerceMediaDefaultImage.java
> +	public void updateConfiguration(String fileEntryId, long groupId)
we should try to think of a way to avoid passing `fileEntryId` here -- fileEntry is implementation-specific

2019-02-20 00:09 UTC, ethanbustad commented on commerce-media-impl/src/main/java/com/liferay/commerce/media/impl/CatalogCommerceMediaDefaultImage.java
> +		return Long.valueOf(settings.getValue("defaultFileEntryId", "0"));
Use `GetterUtil.getLong` rather than `Long.valueOf`

2019-02-20 00:09 UTC, ethanbustad commented on commerce-media-api/src/main/java/com/liferay/commerce/media/CommerceMediaDefaultImage.java
> +	public long getConfiguration(long groupId) throws PortalException;
I think.... this should return a `CPMedia`

2019-02-20 00:18 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 20 minutes 28 seconds 693 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/bde2f05111e843a7fd1345bf6c8f1f159663baca">bde2f05111e843a7fd1345bf6c8f1f159663baca</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :heavy_check_mark:</li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/45//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>39 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/45//testReport">here</a>.</h5></div></html>

2019-02-20 00:23 UTC, ethanbustad commented on commerce-media-api/src/main/java/com/liferay/commerce/media/CommerceMediaDefaultImage.java
> +	public void updateConfiguration(String fileEntryId, long groupId)
Multiple methods with different type options

groupId + {fileEntryId,inputStream,bytes}

2019-02-20 01:26 UTC, ethanbustad commented
ci:test

2019-02-20 01:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x-next">7.1.x-next</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/27/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/27/jenkins-report.html">here</a>.</b></p>

2019-02-20 01:52 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 16 minutes 59 seconds 240 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/bde2f05111e843a7fd1345bf6c8f1f159663baca">bde2f05111e843a7fd1345bf6c8f1f159663baca</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :heavy_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :heavy_check_mark:</li><li>subrepository-pmd-jdk8 -  :heavy_check_mark:</li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [echo] java.lang.Exception: Found 1 formatting issues:
     [echo] 1: ./commerce-media-impl/src/main/java/com/liferay/commerce/media/internal/CommerceCatalogDefaultImageImpl.java expected:&lt;...gs.SettingsFactory;
     [echo] [import com.liferay.portal.kernel.util.GetterUtil;
     [echo] 
     [echo] import org.osgi.service.component.annotations.Component;
     [echo] import org.osgi.service.component.annotations.Reference;
     [echo] 
     [echo] /**
     [echo]  * @author Alec Sloan
     [echo]  */
     [echo] @Component(immediate = true, service = CommerceCatalogDefaultImage.class)
     [echo] public class CommerceCatalogDefaultImageImpl
     [echo] 	implements CommerceCatalogDefaultImage {
     [echo] 
     [echo] 	@Override
     [echo] 	public long getDefaultCatalogFileEntryId(long groupId)
     [echo] 		throws PortalException {
     [echo] 
     [echo] 		Settings settings = _settingsFactory.getSettings(
     [echo] 			new GroupServiceSettingsLocator(
     [echo] 				groupId, CommerceMediaConstants.SERVICE_NAME));
     [echo] 
     [echo] 		return GetterUtil.getLong(]settings.getValue("d...&gt; but was:&lt;...gs.SettingsFactory;
     [echo] [
     [echo] import com.liferay.portal.kernel.util.GetterUtil;
     [echo] import org.osgi.service.component.annotations.Component;
     [echo] import org.osgi.service.component.annotations.Reference;
     [echo] 
     [echo] /**
     [echo]  * @author Alec Sloan
     [echo]  */
     [echo] @Component(
     [echo] 	immediate = true,
     [echo] 	service = CommerceCatalogDefaultImage.class
     [echo] )
     [echo] public class CommerceCatalogDefaultImageImpl
     [echo] 	implements CommerceCatalogDefaultImage {
     [echo] 
     [echo] 	@Override
     [echo] 	public long getDefaultCatalogFileEntryId(long groupId) throws PortalException {
     [echo] 		Settings settings = _settingsFactory.getSettings(
     [echo] 			new GroupServiceSettingsLocator(
     [echo] 				groupId, CommerceMediaConstants.SERVICE_NAME));
     [echo] 
     [echo] 		return GetterUtil.getLong(
     [echo] 			]settings.getValue("d...&gt;
     [echo] 
     [echo] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:430)
     [echo] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:258)
     [echo] 
     [echo] FAILURE: Build failed with an exception.
     [echo] 
     [echo] * What went wrong:
     [echo] Execution failed for task ':checkSourceFormatting'.</code></pre></li><li>central-requirements-jdk8/subrepository-unit-jdk8 -  :heavy_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-1.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/42//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>39 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-1.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/42//testReport">here</a>.</h5></div></html>

2019-02-20 01:57 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test - 17 out of 17 jobs passed in 2 hours 1 minute 30 seconds 711 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/bde2f05111e843a7fd1345bf6c8f1f159663baca">bde2f05111e843a7fd1345bf6c8f1f159663baca</a></p>17 out of 17 jobs PASSED<details><summary><strong>17 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/70/">test-subrepository-acceptance-pullrequest(7.1.x)</a></li><li><a href="https://test-1-1.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/201/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/243/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-19.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/313/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/147/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/422/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/10</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/376/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/222/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-18.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/171/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-4.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/138/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/223/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/314/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/7</a></li><li><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/242/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/8</a></li><li><a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/293/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-functional-tomcat90-mysql57-jdk8/9</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/377/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql57-jdk8</a></li><li><a href="https://test-1-12.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/13/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/45/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/70/jenkins-report.html">here</a>.</h5></details></html>

2019-02-20 02:46 UTC, merged