COMMERCE-176
liferay/com-liferay-commerce pull request #66
Opened 2018-08-03 17:28 UTC by Commando18

2018-08-03 17:28 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2018-08-03 20:55 UTC, Ithildir commented
ci:test

2018-08-03 20:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-20.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/3/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-20.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/3/jenkins-report.html">here</a>.</b></p>

2018-08-03 20:56 UTC, Ithildir approved these changes

2018-08-03 21:15 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 15 minutes 55 seconds 983 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/4475c8b5440b6b259440f04109ebca9e022e8078">4475c8b5440b6b259440f04109ebca9e022e8078</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :white_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :white_check_mark:</li><li>subrepository-pmd-jdk8 -  :white_check_mark:</li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [echo] Exception in thread "main" java.lang.Exception: Found 26 formatting issues:
     [echo] 1: Use a project dependency instead of a module dependency: ./commerce-price-list-test/build.gradle 9 (SourceCheck:GradleTestDependencyVersionCheck)
     [echo] 2: Use a project dependency instead of a module dependency: ./commerce-price-list-test/build.gradle 10 (SourceCheck:GradleTestDependencyVersionCheck)
     [echo] 3: Use a project dependency instead of a module dependency: ./commerce-product-service/build.gradle 37 (SourceCheck:GradleTestDependencyVersionCheck)
     [echo] 4: Use a project dependency instead of a module dependency: ./commerce-product-test/build.gradle 9 (SourceCheck:GradleTestDependencyVersionCheck)
     [echo] 5: Use a project dependency instead of a module dependency: ./commerce-product-test/build.gradle 10 (SourceCheck:GradleTestDependencyVersionCheck)
     [echo] 6: Use a project dependency instead of a module dependency: ./commerce-product-type-virtual-test/build.gradle 3 (SourceCheck:GradleTestDependencyVersionCheck)
     [echo] 7: Use a project dependency instead of a module dependency: ./commerce-product-type-virtual-test/build.gradle 4 (SourceCheck:GradleTestDependencyVersionCheck)
     [echo] 8: Use a project dependency instead of a module dependency: ./commerce-product-type-virtual-test/build.gradle 5 (SourceCheck:GradleTestDependencyVersionCheck)
     [echo] 9: Use a project dependency instead of a module dependency: ./commerce-test/build.gradle 9 (SourceCheck:GradleTestDependencyVersionCheck)
     [echo] 10: Use a project dependency instead of a module dependency: ./commerce-test/build.gradle 10 (SourceCheck:GradleTestDependencyVersionCheck)
     [echo] 11: Use a project dependency instead of a module dependency: ./commerce-test/build.gradle 11 (SourceCheck:GradleTestDependencyVersionCheck)
     [echo] 12: Use a project dependency instead of a module dependency: ./commerce-user-segment-test/build.gradle 9 (SourceCheck:GradleTestDependencyVersionCheck)
     [echo] 13: ./commerce-currency-test/build.gradle expected:&amp;lt;....kernel", version: "[default]"
     [echo] 	testIntegrationCo...&gt; but was:&amp;lt;....kernel", version: "[3.5.0]"
     [echo] 	testIntegrationCo...&gt;
     [echo] 14: ./commerce-shipping-engine-fixed-test/build.gradle expected:&amp;lt;....kernel", version: "[default]"
     [echo] 	testIntegrationCo...&gt; but was:&amp;lt;....kernel", version: "[3.5.0]"
     [echo] 	testIntegrationCo...&gt;</code></pre></li></ul><h5>For full console, click <a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/2//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>3 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-16.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/2//testReport">here</a>.</h5></div></html>

2018-08-06 20:24 UTC, ethanbustad requested changes
Please see the comments I've made on the various files included in this PR.

Also, in general:
* `<#assign` tags in `.ftl` files should be reviewed for consistency in spaces, indentation, newlines, quotes, and sorting. I made comments regarding this in several files, but not everywhere. I'm sure I would've missed some if I'd tried to mention all of them. It'll be best to just look over all of the tags to make sure they're all consistent.
* There are some un-localized values in some of the FTL templates (e.g. `Model $number`, `SKU $value`). Is this intended, or should we localize these? If it's just dummy content I could see leaving these values untranslated, but I'm not sure how far it makes sense to go with that idea.
* I think we have some duplicate image files. There are some instances of names like `${name}.jpg`, `${name}(1).jpg`, sometimes up to `(5)`. I took a look and the files seem to be identical. Do we need to include these duplicates?

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/java/com/liferay/commerce/initializer/breccia/internal/BrecciaSiteInitializer.java
> +	private ServiceContext _getServiceContext(long groupId)
Hey @Commando18, can you re-sort the variable declarations in this method?
* `User user` should be declared just before `serviceContext.setTimeZone`, since that's the first time it's used.
* `Group group` should be declared just before `serviceContext.setCompanyId` (same reason)

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/categories.json
> +[
Hey @Commando18, is there any reason to not sort this JSONArray in alphabetical order?

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/journal-articles.json
> +[
Can we alpha-sort this file as well?

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/layouts.json
> +				"layoutColumnPos": "2",
This `"2"` shouldn't be a String, right? Or at least, we should make these values consistent -- `"layoutColumnPos"` should always be a String, or always be a Number.

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/layouts.json
> +		"layoutTemplateId": "commerce_max_width_1_column",
What do you think of alphabetizing this file by `layoutTemplateId`?

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/display_templates/BRECCIA_COMMERCE_CART_CONTENT_TOTAL.ftl
> +	orderId = '${commerceCartContentTotalDisplayContext.getCommerceOrderId()}'
These should be `"` double quotes rather than `'` single quotes (wherever we're assigning variables, unless maybe there's a nested `"`).

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/display_templates/BRECCIA_COMMERCE_CATEGORY_NAVIGATION_SIMPLE.ftl
> +		<div class="commerce-component-header product-detail-header"> <h2 class="component-title">Explore Categories</h2> </div>
This `<h2>` should be on a new line.

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/display_templates/catalog_display_template.ftl
> +				cpDefinitionId = cpSearchResultsDisplayContext.getCPDefinitionId(curDocument)
Tabbing++

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/display_templates/catalog_display_template.ftl
> +						cpInstance =  cpSearchResultsDisplayContext.getDefaultCPInstance(curDocument)
Tabbing

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/display_templates/catalog_display_template.ftl
> +							cpInstanceId =  cpInstance.getCPInstanceId()
Tabbing

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/display_templates/catalog_display_template.ftl
> +								<#if isIgnoreSKUCombinations>
Tabbing--

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/display_templates/catalog_display_template.ftl
> +								<#if isIgnoreSKUCombinations>
Tabbing--

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/display_templates/product_display_search_results_template.ftl
> +				cpDefinitionId = cpSearchResultsDisplayContext.getCPDefinitionId(curDocument)
Tabbing needs adjustment in this file as well.

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/display_templates/product_display_search_results_template.ftl
> +				cpDefinitionId = cpSearchResultsDisplayContext.getCPDefinitionId(curDocument)
Actually, should this file be identical to `catalog_display_template.ftl`? It looks like it is atm.

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/display_templates/catalog_display_template.ftl
> +				cpDefinitionId = cpSearchResultsDisplayContext.getCPDefinitionId(curDocument)
These variables should also be sorted if possible

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/display_templates/product_display_template.ftl
> +	defaultImage = (simpleCPTypeDisplayContext.getDefaultImage())!""
These parentheses are unnecessary, right?

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/display_templates/product_display_template.ftl
> +				cpInstanceId =  cpInstance.getCPInstanceId()
Extra space

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/display_templates/product_display_template.ftl
> +								imagesIndex=1
Spacing

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/display_templates/product_display_template.ftl
> +									imagesIndex=imagesIndex + 1
spacing

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/display_templates/product_display_template.ftl
> +											activeClass=""
spacing

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/display_templates/product_display_template.ftl
> +												activeClass="active "
spacing

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/display_templates/BRECCIA_COMMERCE_CART_CONTENT.ftl
> +							cpDefinition = curCommerceOrderItem.getCPDefinition()
These variables should be sorted.

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/display_templates/BRECCIA_COMMERCE_CART_CONTENT_TOTAL.ftl
> +	<#assign
Is there a rule for when an `<#assign>` tag with only one variable should be all inline? Sometimes we do

    <#assign var = value />

and sometimes we do

    <#assign
        var = value
    />

We should stick to a single pattern if possible.

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/journal_articles/NEW_ARRIVALS.ftl
> +.newestTitle{
This section should be indented like a normal `.css` file.

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/journal_articles/NEW_ARRIVALS.ftl
> +${HTMLNewest.getData()}
Tabbing++

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/META-INF/resources/render/view.jsp
> +	<%
Tabbing--

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-breccia/src/main/resources/META-INF/resources/render/list_entry/search_result.jsp
> +									<span class="available-variants"><%= cpSkus.size() %> <liferay-ui:message key="variants-available" /></span>
The `cpSkus.size()` here should be included as a variable in the lang key -- i.e. `x-variants-available`. Some languages may indicate the number at the end of the phrase, rather than the beginning.

In general, nothing should be concatenated to translated language values -- it should always be included as part of the translation.

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-util/src/main/java/com/liferay/commerce/initializer/util/CPDefinitionsImporter.java
> +					"No options defined has sku contributor for " +
This should be "No options defined have...", not "has".

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-util/src/main/java/com/liferay/commerce/initializer/util/CPDefinitionsImporter.java
> +						"CPDefinition: " + cpDefinition.getCPDefinitionId());
There should not be a colon here (see https://docs.google.com/document/d/1ZhLmXOb52ShY1WelpRsAPByzQPilZ8RqP2LZNUi4Z84/edit#heading=h.qrdpygu4iv3m).

2018-08-06 20:24 UTC, ethanbustad commented on commerce-initializer-util/src/main/java/com/liferay/commerce/initializer/util/CPDefinitionsImporter.java
> +			// Commerce product instance
The logic in this section should be sorted.

2018-08-06 20:24 UTC, ethanbustad commented on commerce-theme-breccia/src/css/_main_variables.scss
> +	scaling-navbar: true,
These values should be sorted.

Same throughout the rest of the file.

2018-08-06 20:24 UTC, ethanbustad commented on commerce-theme-breccia/src/css/components/_product-detail.scss
> +.liferayzoom img {
This and the following few selectors should be nested under `.liferayzoom`.

2018-08-06 20:24 UTC, ethanbustad commented on commerce-theme-breccia/src/css/components/_product-detail.scss
> +	.liferayzoom--adjacent {
This should be sorted above `.product-detail-image` a few lines up.

2018-08-06 20:24 UTC, ethanbustad commented on commerce-theme-breccia/src/css/components/_widget.scss
> +	.title {
These nested selectors should be sorted alphabetically.

Same throughout the file.

2018-08-06 20:24 UTC, ethanbustad commented on commerce-theme-breccia/src/css/portlet/_portlet_decorators.scss
> +.portlet-decorate {
Nested selectors should be sorted.

2018-08-06 20:24 UTC, ethanbustad commented on commerce-theme-breccia/src/css/portlet/_portlet_hello_world.scss
> +	.portlet-body {
Sorting

2018-08-06 20:24 UTC, ethanbustad commented on commerce-theme-breccia/src/css/portlet/_variables_custom.scss
> +$portlet-content-border-radius: 0 0 8px 8px;
This should be sorted above.

2018-08-06 20:24 UTC, ethanbustad commented on commerce-theme-breccia/src/css/portlet/_variables_custom.scss
> +$portlet-topper-border-radius: 4px 4px 0 0;
This should be included with the rest of the `$portlet-topper-*` variables.

2018-08-06 20:24 UTC, ethanbustad commented on commerce-theme-breccia/src/WEB-INF/liferay-look-and-feel.xml
> +		<version>7.1.0+</version>
Should be `7.1.10+`.

2018-08-06 20:24 UTC, ethanbustad commented on commerce-theme-breccia/src/WEB-INF/liferay-plugin-package.properties
> +liferay-versions=7.1.0+
`7.1.10+`

2018-08-06 20:24 UTC, ethanbustad commented on commerce-theme-breccia/src/css/_custom.scss
> +.easyzoom img {
This selector and following: nest under `.easyzoom`.

2018-08-06 20:24 UTC, ethanbustad commented on commerce-theme-breccia/src/css/_custom.scss
> +.easyzoom-flyout {
Sort alphabetically.

2018-08-06 20:24 UTC, ethanbustad commented on commerce-theme-breccia/src/css/_custom.scss
> +.easyzoom--adjacent .easyzoom-flyout {
Sort alphabetically.

2018-08-06 20:24 UTC, ethanbustad commented on commerce-theme-breccia/src/css/_custom.scss
> +	.easyzoom--adjacent {
sort

2018-08-07 17:33 UTC, Commando18 commented
ci:retest

2018-08-07 17:34 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/5/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/5/jenkins-report.html">here</a>.</b></p>

2018-08-07 17:52 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 14 minutes 46 seconds 617 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/f0e59929b8d8b30cab6c1ac6103b1feadf55f001">f0e59929b8d8b30cab6c1ac6103b1feadf55f001</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :white_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :white_check_mark:</li><li>subrepository-pmd-jdk8 -  :white_check_mark:</li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [echo] Exception in thread "main" java.lang.Exception: Found 1 formatting issues:
     [echo] 1: ./commerce-theme-breccia/src/WEB-INF/liferay-plugin-package.properties expected:&lt;...iferay-versions=7.1.[]0+
     [echo] long-description=...&gt; but was:&lt;...iferay-versions=7.1.[1]0+
     [echo] long-description=...&gt;
     [echo] 
     [echo] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:394)
     [echo] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:234)
     [echo] 
     [echo] FAILURE: Build failed with an exception.
     [echo] 
     [echo] * What went wrong:
     [echo] Execution failed for task ':checkSourceFormatting'.
     [echo] &gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [echo] 
     [echo] * Try:
     [echo] Run with --info or --debug option to get more log output.
     [echo] 
     [echo] * Exception is:
     [echo] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':checkSourceFormatting'.
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
     [echo] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
     [echo] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
     [echo] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)</code></pre></li></ul><h5>For full console, click <a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/5//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>3 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/5//testReport">here</a>.</h5></div></html>

2018-08-07 23:22 UTC, marco-leo commented
@Commando18 I have to assume that you changed all as @ethanbustad suggested?

2018-08-08 13:03 UTC, Commando18 commented
@marco-leo I just missed the css files, >I will sort them now

2018-08-08 15:49 UTC, Commando18 commented
@marco-leo @ethanbustad I should have fixed everything. Let me know if it looks fine now :)

2018-08-08 16:18 UTC, ethanbustad commented
@Commando18 thanks for all those changes!

I only see a couple small formatting issues still, but I don't think it's worth delaying getting this merged. So :+1: from me!

2018-08-08 16:18 UTC, ethanbustad approved these changes

2018-08-08 16:26 UTC, Commando18 commented
@ethanbustad Thanks!
@marco-leo Ready to be merged then :)

2018-08-08 16:26 UTC, merged