COMMERCE-574 Fixed shipments admin portlet
liferay/com-liferay-commerce pull request #78
Opened 2018-08-21 10:29 UTC by Commando18

2018-08-21 10:29 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2018-08-21 10:30 UTC, Commando18 commented
ci:test

2018-08-21 10:34 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/6/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-22.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/6/jenkins-report.html">here</a>.</b></p>

2018-08-21 10:51 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 13 minutes 2 seconds 779 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/b118f87f779642e73236021f13df95d9c8e3c574">b118f87f779642e73236021f13df95d9c8e3c574</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :white_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :x:<pre><code>     [echo] 	&amp;lt;   class      com.liferay.commerce.service.CommerceShipmentServiceUtil
     [echo] 		+   method     updateCommerceShipment(long,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,long,long,java.lang.String,java.lang.String,java.lang.String,int,int,int,int,int,int,int,int,int,int,int)
     [echo] 			+   access     static
     [echo] 			+   return     com.liferay.commerce.model.CommerceShipment
     [echo] 	&amp;lt;   class      com.liferay.commerce.service.CommerceShipmentServiceWrapper
     [echo] 		+   method     updateCommerceShipment(long,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,long,long,java.lang.String,java.lang.String,java.lang.String,int,int,int,int,int,int,int,int,int,int,int)
     [echo] 			+   return     com.liferay.commerce.model.CommerceShipment
     [echo] 	&amp;lt;   interface  com.liferay.commerce.service.CommerceShipmentLocalService
     [echo] 		~   method     updateCommerceShipment(long,java.lang.String,java.lang.String,int,int,int,int,int,int,int,int,int,int,int)
     [echo] 			-   annotated  com.liferay.portal.kernel.search.Indexable
     [echo] 				-   property   type='REINDEX'
     [echo] 		+   method     updateCommerceShipment(long,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,long,long,java.lang.String,java.lang.String,java.lang.String,int,int,int,int,int,int,int,int,int,int,int)
     [echo] 			+   access     abstract
     [echo] 			+   annotated  com.liferay.portal.kernel.search.Indexable
     [echo] 				+   property   type='REINDEX'
     [echo] 			+   return     com.liferay.commerce.model.CommerceShipment
     [echo] 	&amp;lt;   interface  com.liferay.commerce.service.CommerceShipmentService
     [echo] 		+   method     updateCommerceShipment(long,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,long,long,java.lang.String,java.lang.String,java.lang.String,int,int,int,int,int,int,int,int,int,int,int)
     [echo] 			+   access     abstract
     [echo] 			+   return     com.liferay.commerce.model.CommerceShipment
     [echo] :apps:commerce:commerce-api:baseline FAILED
     [echo] :apps:commerce:commerce-api:syncVersions
     [echo] 
     [echo] BUILD FAILED
     [echo] 
     [echo] </code></pre></li></ul><h5>For full console, click <a href="https://test-1-21.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/5//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><h5>No tests were run.</h5></div></html>

2018-08-21 15:58 UTC, ethanbustad commented
@Commando18 can you run `gradlew baseline`, and commit and push the changes? That should fix the CI failure.

2018-08-24 11:50 UTC, Commando18 commented
ci:retest

2018-08-24 11:51 UTC, Commando18 commented
@ethanbustad did it, thanks!

2018-08-24 11:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-19.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/7/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-19.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/7/jenkins-report.html">here</a>.</b></p>

2018-08-24 12:11 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 15 minutes 52 seconds 186 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/7bcc5271975110c281d530ba53eca6d9f0705e82">7bcc5271975110c281d530ba53eca6d9f0705e82</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :white_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :white_check_mark:</li><li>subrepository-pmd-jdk8 -  :white_check_mark:</li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [echo] Exception in thread "main" java.lang.Exception: Found 3 formatting issues:
     [echo] 1: ./commerce-shipment-web/src/main/resources/META-INF/resources/shipment/details.jsp expected:&lt;... name="description" []/&gt;
     [echo] 
     [echo] 					&lt;aui:input ...&gt; but was:&lt;... name="description" [ ]/&gt;
     [echo] 
     [echo] 					&lt;aui:input ...&gt;
     [echo] 2: ./commerce-product-service/src/main/java/com/liferay/commerce/product/internal/catalog/rule/AssetCategoryCPRuleTypeImpl.java expected:&lt;...kernel.service.Asset[]EntryLocalService;
     [echo] i...&gt; but was:&lt;...kernel.service.Asset[CategoryLocalService;
     [echo] import com.liferay.asset.kernel.service.Asset]EntryLocalService;
     [echo] i...&gt;
     [echo] 3: ./commerce-service/src/main/java/com/liferay/commerce/internal/product/content/contributor/PriceCPContentContributor.java expected:&lt;...om.liferay.commerce.[]service.CPDefinition...&gt; but was:&lt;...om.liferay.commerce.[product.util.CPContentContributorRegistry;
     [echo] import com.liferay.commerce.]service.CPDefinition...&gt;
     [echo] 
     [echo] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:395)
     [echo] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:234)
     [echo] 
     [echo] FAILURE: Build failed with an exception.
     [echo] 
     [echo] * What went wrong:
     [echo] Execution failed for task ':checkSourceFormatting'.
     [echo] &gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [echo] 
     [echo] * Try:
     [echo] Run with --info or --debug option to get more log output.
     [echo] 
     [echo] * Exception is:
     [echo] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':checkSourceFormatting'.
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
     [echo] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)</code></pre></li></ul><h5>For full console, click <a href="https://test-1-19.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/3//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>3 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-19.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/3//testReport">here</a>.</h5></div></html>

2018-08-24 15:43 UTC, ethanbustad commented
@Commando18 looks like it needs `gradlew formatSource`, too :/

There's a chance the above failure doesn't show up with `formatSource` locally. If so, trust the CI version for now and make the change manually -- I'm trying to get it resolved so we get the same results in CI and locally.

2018-08-27 08:08 UTC, Commando18 commented
ci:retest

2018-08-27 08:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/11/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-22.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/11/jenkins-report.html">here</a>.</b></p>

2018-08-27 08:30 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 17 minutes 50 seconds 555 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/7bcc5271975110c281d530ba53eca6d9f0705e82">7bcc5271975110c281d530ba53eca6d9f0705e82</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :white_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :white_check_mark:</li><li>subrepository-pmd-jdk8 -  :white_check_mark:</li><li>subrepository-source-format-jdk8 -  :white_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/5//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>3 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/5//testReport">here</a>.</h5></div></html>

2018-08-27 09:03 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test - 6 out of 6 jobs passed in 54 minutes 14 seconds 101 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/7bcc5271975110c281d530ba53eca6d9f0705e82">7bcc5271975110c281d530ba53eca6d9f0705e82</a></p>6 out of 6 jobs PASSED<details><summary><strong>6 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/11/">test-subrepository-acceptance-pullrequest(7.1.x)</a></li><li><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/1/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat80-mysql56-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/2/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/3/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql56-jdk8</a></li><li><a href="https://test-1-9.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/3/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-22.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/5/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-22.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/11/jenkins-report.html">here</a>.</h5></details></html>

2018-08-27 22:35 UTC, ethanbustad requested changes

2018-08-27 22:35 UTC, ethanbustad commented on commerce-service/src/main/java/com/liferay/commerce/service/impl/CommerceShipmentLocalServiceImpl.java
> +		CommerceShipment commerceShipment =
Can you sort this down below `String phoneNumber = null;`?

2018-08-27 22:35 UTC, ethanbustad commented on commerce-service/src/main/java/com/liferay/commerce/service/impl/CommerceShipmentLocalServiceImpl.java
> +			name.equals(commerceAddress.getName()) &&
Couldn't these variables be passed in as `null`? We check for nullness in `commerceAddressLocalService.addCommerceAddress`, so it seems like we shouldn't break here if these values are `null`. We could just sidestep the issue with `Objects.equals`.

2018-08-27 22:35 UTC, ethanbustad commented on commerce-shipment-web/src/main/resources/META-INF/resources/shipment/details.jsp
> +CommerceAddress commerceAddress = commerceShipment.fetchCommerceAddress();
Can you sort this below `long commerceRegionId = 0;`?

2018-08-27 22:35 UTC, ethanbustad commented on commerce-shipment-web/src/main/resources/META-INF/resources/shipment/details.jsp
> +				{
Indentation is a bit off here (162-172)

2018-08-27 22:35 UTC, ethanbustad commented on commerce-shipping-web/src/main/resources/META-INF/resources/edit_shipping_settings.jsp
> +		boolean checked = false;
Ideally this should be sorted above `String key = entry.getKey();`.

2018-08-29 08:10 UTC, Commando18 commented
ci:retest

2018-08-29 08:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/11/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/11/jenkins-report.html">here</a>.</b></p>

2018-08-29 08:30 UTC, liferay-continuous-integration commented
<html><h1>Validation FAILED.</h1><p>Build Time: 16 minutes 9 seconds 981 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/4f16d4adbad6c584daaf7936cd3799b1cb6a0bf5">4f16d4adbad6c584daaf7936cd3799b1cb6a0bf5</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :white_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :white_check_mark:</li><li>subrepository-pmd-jdk8 -  :white_check_mark:</li><li>subrepository-source-format-jdk8 -  :x:<pre><code>     [echo] Exception in thread "main" java.lang.Exception: Found 1 formatting issues:
     [echo] 1: ./commerce-shipping-web/src/main/resources/META-INF/resources/edit_shipping_settings.jsp expected:&lt;...ators.entrySet()) {
     [echo] [		boolean checked = false;
     [echo] 
     [echo] 		String key = entry.getKey();
     [echo] 		]CommerceShippingOrig...&gt; but was:&lt;...ators.entrySet()) {
     [echo] [        boolean checked = false;
     [echo] 
     [echo]         String key = entry.getKey();
     [echo]         ]CommerceShippingOrig...&gt;
     [echo] 
     [echo] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:395)
     [echo] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:234)
     [echo] 
     [echo] FAILURE: Build failed with an exception.
     [echo] 
     [echo] * What went wrong:
     [echo] Execution failed for task ':checkSourceFormatting'.
     [echo] &gt; Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [echo] 
     [echo] * Try:
     [echo] Run with --info or --debug option to get more log output.
     [echo] 
     [echo] * Exception is:
     [echo] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':checkSourceFormatting'.
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
     [echo] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)</code></pre></li></ul><h5>For full console, click <a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/7//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>3 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/7//testReport">here</a>.</h5></div></html>

2018-08-29 08:59 UTC, Commando18 commented
ci:retest

2018-08-29 09:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/7/">test-subrepository-acceptance-pullrequest(7.1.x)</a></p><p><b>For more details click <a href="https://test-1-17.liferay.com//userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/7/jenkins-report.html">here</a>.</b></p>

2018-08-29 09:17 UTC, liferay-continuous-integration commented
<html><h1>Validation PASSED. Running batch tests.</h1><p>Build Time: 11 minutes 36 seconds 685 ms</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/4f16d4adbad6c584daaf7936cd3799b1cb6a0bf5">4f16d4adbad6c584daaf7936cd3799b1cb6a0bf5</a></p><h6>Task Summary:</h6><ul><li>subrepository-compile-jdk8 -  :white_check_mark:</li><li>subrepository-semantic-versioning-jdk8 -  :white_check_mark:</li><li>subrepository-pmd-jdk8 -  :white_check_mark:</li><li>subrepository-source-format-jdk8 -  :white_check_mark:</li></ul><h5>For full console, click <a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/8//consoleText">here</a>.</h5><hr/><div><h6>Test Results:</h6><div><div><p>3 Tests Passed.<br/>0 Tests Failed.</p></div></div><h5>For all test results, click <a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/8//testReport">here</a>.</h5></div></html>

2018-08-29 09:45 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test - 6 out of 6 jobs passed in 44 minutes 30 seconds 338 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/com-liferay-commerce/tree/7.1.x">7.1.x</a><br/>Branch GIT ID: <a href="https://github.com/liferay/com-liferay-commerce/commit/4f16d4adbad6c584daaf7936cd3799b1cb6a0bf5">4f16d4adbad6c584daaf7936cd3799b1cb6a0bf5</a></p>6 out of 6 jobs PASSED<details><summary><strong>6 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-17.liferay.com/job/test-subrepository-acceptance-pullrequest(7.1.x)/7/">test-subrepository-acceptance-pullrequest(7.1.x)</a></li><li><a href="https://test-1-11.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/12/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/11/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-assemble-jdk8</a></li><li><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(7.1.x)/16/">test-subrepository-acceptance-pullrequest-batch(7.1.x)/subrepository-integration-mysql56-jdk8</a></li><li><a href="https://test-1-23.liferay.com/job/test-subrepository-acceptance-pullrequest-dist(7.1.x)/3/">test-subrepository-acceptance-pullrequest-dist(7.1.x)/jdk8</a></li><li><a href="https://test-1-2.liferay.com/job/test-subrepository-acceptance-pullrequest-validation(7.1.x)/8/">test-subrepository-acceptance-pullrequest-validation(7.1.x)/jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-subrepository-acceptance-pullrequest(7.1.x)/builds/7/jenkins-report.html">here</a>.</h5></details></html>

2018-08-30 08:45 UTC, merged